# https://taskfile.dev

version: '3'

vars:
  GENERATOR: "go"
  BUNDLEDSPEC: ".api/bundled.yaml"
  GENERATORCONFIG: ".openapi-generator/go/config-client-go.yaml"
  GENERATORIGNOREFILE: ".openapi-generator/.openapi-generator-ignore"
  TEMPLATEDIR: ".openapi-generator/go/templates"
  SPECREPO: "https://github.com/gomorpheus/morpheus-openapi"
  OUTPUTDIR: "sdk"

tasks:
  default:
    silent: true
    cmds:
      - task -l

  install-redocly:
    internal: true
    cmds:
      - npm i -g @redocly/cli@1.34.3
  
  install-openapi-generator:
    internal: true
    cmds:
      - npm install @openapitools/openapi-generator-cli -g
      - openapi-generator-cli version-manager set 7.12.0

  # perform tooling installations in parallel
  install-tools:
    desc: install redocly, openapi-generator
    deps: [install-redocly, install-openapi-generator]

  generate:
    desc: generate a Go SDK from the local OpenAPI spec
    env:
      _JAVA_OPTIONS: -DmaxYamlCodePoints=99999999
    cmds:
      - if [ ! -d {{.OUTPUTDIR}} ]; then mkdir {{.OUTPUTDIR}}; fi
      - cp {{.GENERATORIGNOREFILE}} {{.OUTPUTDIR}}
      - cmd: >-
          openapi-generator-cli generate 
          -g {{.GENERATOR}}
          -i {{.BUNDLEDSPEC}}
          -c {{.GENERATORCONFIG}}
          {{if .TEMPLATEDIR -}}-t {{.TEMPLATEDIR}} {{end}}
          -o {{.OUTPUTDIR}}
  
  clone-spec:
    silent: true
    internal: true
    cmds:
      - git clone {{.SPECREPO}}

  bundle-spec:
    internal: true
    cmds:
      - >-
        redocly bundle 
        --dereferenced 
        --output {{.BUNDLEDSPEC}}
        morpheus-openapi/openapi.yaml
  
  update-spec:
    desc: "update OpenAPI spec to match the morpheus-openapi GITREF"
    vars:
      GITREF: '{{if (empty .GITREF)}}main{{else}}{{.GITREF}}{{end}}'
    dir: morpheus-openapi
    cmds:
      - task: clone-spec
      - defer: rm -rf ../morpheus-openapi
      - git checkout {{.GITREF}}
      - task: bundle-spec
      - git rev-parse HEAD > ../.api/latest-commit-sha
  
  update-client:
    desc: "update Go SDK to match the morpheus-openapi GITREF"
    cmds:
      - task: update-spec
      - task: generate
