// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// AccountsItemUsersPostRequestBody_user payload for creating a new user
type AccountsItemUsersPostRequestBody_user struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Email address
    email *string
    // The user's first name (optional)
    firstName *string
    // The user's last name (optional)
    lastName *string
    // Linux SSH Key, user settings for provisioning
    linuxKeyPairId *int64
    // Linux Password, user settings for provisioning
    linuxPassword *string
    // Linux Username, user settings for provisioning
    linuxUsername *string
    // Password to apply to the user
    password *string
    // Receive Notifications?
    receiveNotifications *bool
    // Array of objects with id of the role(s) to assign to the user.
    roles []AccountsItemUsersPostRequestBody_user_rolesable
    // Username (unique per tenant).
    username *string
    // Windows Password, user settings for provisioning
    windowsPassword *string
    // Windows Username, user settings for provisioning
    windowsUsername *string
}
// NewAccountsItemUsersPostRequestBody_user instantiates a new AccountsItemUsersPostRequestBody_user and sets the default values.
func NewAccountsItemUsersPostRequestBody_user()(*AccountsItemUsersPostRequestBody_user) {
    m := &AccountsItemUsersPostRequestBody_user{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAccountsItemUsersPostRequestBody_userFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAccountsItemUsersPostRequestBody_userFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAccountsItemUsersPostRequestBody_user(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *AccountsItemUsersPostRequestBody_user) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetEmail gets the email property value. Email address
// returns a *string when successful
func (m *AccountsItemUsersPostRequestBody_user) GetEmail()(*string) {
    return m.email
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AccountsItemUsersPostRequestBody_user) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["email"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEmail(val)
        }
        return nil
    }
    res["firstName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFirstName(val)
        }
        return nil
    }
    res["lastName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLastName(val)
        }
        return nil
    }
    res["linuxKeyPairId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLinuxKeyPairId(val)
        }
        return nil
    }
    res["linuxPassword"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLinuxPassword(val)
        }
        return nil
    }
    res["linuxUsername"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLinuxUsername(val)
        }
        return nil
    }
    res["password"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPassword(val)
        }
        return nil
    }
    res["receiveNotifications"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetReceiveNotifications(val)
        }
        return nil
    }
    res["roles"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateAccountsItemUsersPostRequestBody_user_rolesFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]AccountsItemUsersPostRequestBody_user_rolesable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(AccountsItemUsersPostRequestBody_user_rolesable)
                }
            }
            m.SetRoles(res)
        }
        return nil
    }
    res["username"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUsername(val)
        }
        return nil
    }
    res["windowsPassword"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWindowsPassword(val)
        }
        return nil
    }
    res["windowsUsername"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWindowsUsername(val)
        }
        return nil
    }
    return res
}
// GetFirstName gets the firstName property value. The user's first name (optional)
// returns a *string when successful
func (m *AccountsItemUsersPostRequestBody_user) GetFirstName()(*string) {
    return m.firstName
}
// GetLastName gets the lastName property value. The user's last name (optional)
// returns a *string when successful
func (m *AccountsItemUsersPostRequestBody_user) GetLastName()(*string) {
    return m.lastName
}
// GetLinuxKeyPairId gets the linuxKeyPairId property value. Linux SSH Key, user settings for provisioning
// returns a *int64 when successful
func (m *AccountsItemUsersPostRequestBody_user) GetLinuxKeyPairId()(*int64) {
    return m.linuxKeyPairId
}
// GetLinuxPassword gets the linuxPassword property value. Linux Password, user settings for provisioning
// returns a *string when successful
func (m *AccountsItemUsersPostRequestBody_user) GetLinuxPassword()(*string) {
    return m.linuxPassword
}
// GetLinuxUsername gets the linuxUsername property value. Linux Username, user settings for provisioning
// returns a *string when successful
func (m *AccountsItemUsersPostRequestBody_user) GetLinuxUsername()(*string) {
    return m.linuxUsername
}
// GetPassword gets the password property value. Password to apply to the user
// returns a *string when successful
func (m *AccountsItemUsersPostRequestBody_user) GetPassword()(*string) {
    return m.password
}
// GetReceiveNotifications gets the receiveNotifications property value. Receive Notifications?
// returns a *bool when successful
func (m *AccountsItemUsersPostRequestBody_user) GetReceiveNotifications()(*bool) {
    return m.receiveNotifications
}
// GetRoles gets the roles property value. Array of objects with id of the role(s) to assign to the user.
// returns a []AccountsItemUsersPostRequestBody_user_rolesable when successful
func (m *AccountsItemUsersPostRequestBody_user) GetRoles()([]AccountsItemUsersPostRequestBody_user_rolesable) {
    return m.roles
}
// GetUsername gets the username property value. Username (unique per tenant).
// returns a *string when successful
func (m *AccountsItemUsersPostRequestBody_user) GetUsername()(*string) {
    return m.username
}
// GetWindowsPassword gets the windowsPassword property value. Windows Password, user settings for provisioning
// returns a *string when successful
func (m *AccountsItemUsersPostRequestBody_user) GetWindowsPassword()(*string) {
    return m.windowsPassword
}
// GetWindowsUsername gets the windowsUsername property value. Windows Username, user settings for provisioning
// returns a *string when successful
func (m *AccountsItemUsersPostRequestBody_user) GetWindowsUsername()(*string) {
    return m.windowsUsername
}
// Serialize serializes information the current object
func (m *AccountsItemUsersPostRequestBody_user) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("email", m.GetEmail())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("firstName", m.GetFirstName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("lastName", m.GetLastName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("linuxKeyPairId", m.GetLinuxKeyPairId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("linuxPassword", m.GetLinuxPassword())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("linuxUsername", m.GetLinuxUsername())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("password", m.GetPassword())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("receiveNotifications", m.GetReceiveNotifications())
        if err != nil {
            return err
        }
    }
    if m.GetRoles() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetRoles()))
        for i, v := range m.GetRoles() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("roles", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("username", m.GetUsername())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("windowsPassword", m.GetWindowsPassword())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("windowsUsername", m.GetWindowsUsername())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *AccountsItemUsersPostRequestBody_user) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetEmail sets the email property value. Email address
func (m *AccountsItemUsersPostRequestBody_user) SetEmail(value *string)() {
    m.email = value
}
// SetFirstName sets the firstName property value. The user's first name (optional)
func (m *AccountsItemUsersPostRequestBody_user) SetFirstName(value *string)() {
    m.firstName = value
}
// SetLastName sets the lastName property value. The user's last name (optional)
func (m *AccountsItemUsersPostRequestBody_user) SetLastName(value *string)() {
    m.lastName = value
}
// SetLinuxKeyPairId sets the linuxKeyPairId property value. Linux SSH Key, user settings for provisioning
func (m *AccountsItemUsersPostRequestBody_user) SetLinuxKeyPairId(value *int64)() {
    m.linuxKeyPairId = value
}
// SetLinuxPassword sets the linuxPassword property value. Linux Password, user settings for provisioning
func (m *AccountsItemUsersPostRequestBody_user) SetLinuxPassword(value *string)() {
    m.linuxPassword = value
}
// SetLinuxUsername sets the linuxUsername property value. Linux Username, user settings for provisioning
func (m *AccountsItemUsersPostRequestBody_user) SetLinuxUsername(value *string)() {
    m.linuxUsername = value
}
// SetPassword sets the password property value. Password to apply to the user
func (m *AccountsItemUsersPostRequestBody_user) SetPassword(value *string)() {
    m.password = value
}
// SetReceiveNotifications sets the receiveNotifications property value. Receive Notifications?
func (m *AccountsItemUsersPostRequestBody_user) SetReceiveNotifications(value *bool)() {
    m.receiveNotifications = value
}
// SetRoles sets the roles property value. Array of objects with id of the role(s) to assign to the user.
func (m *AccountsItemUsersPostRequestBody_user) SetRoles(value []AccountsItemUsersPostRequestBody_user_rolesable)() {
    m.roles = value
}
// SetUsername sets the username property value. Username (unique per tenant).
func (m *AccountsItemUsersPostRequestBody_user) SetUsername(value *string)() {
    m.username = value
}
// SetWindowsPassword sets the windowsPassword property value. Windows Password, user settings for provisioning
func (m *AccountsItemUsersPostRequestBody_user) SetWindowsPassword(value *string)() {
    m.windowsPassword = value
}
// SetWindowsUsername sets the windowsUsername property value. Windows Username, user settings for provisioning
func (m *AccountsItemUsersPostRequestBody_user) SetWindowsUsername(value *string)() {
    m.windowsUsername = value
}
type AccountsItemUsersPostRequestBody_userable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetEmail()(*string)
    GetFirstName()(*string)
    GetLastName()(*string)
    GetLinuxKeyPairId()(*int64)
    GetLinuxPassword()(*string)
    GetLinuxUsername()(*string)
    GetPassword()(*string)
    GetReceiveNotifications()(*bool)
    GetRoles()([]AccountsItemUsersPostRequestBody_user_rolesable)
    GetUsername()(*string)
    GetWindowsPassword()(*string)
    GetWindowsUsername()(*string)
    SetEmail(value *string)()
    SetFirstName(value *string)()
    SetLastName(value *string)()
    SetLinuxKeyPairId(value *int64)()
    SetLinuxPassword(value *string)()
    SetLinuxUsername(value *string)()
    SetPassword(value *string)()
    SetReceiveNotifications(value *bool)()
    SetRoles(value []AccountsItemUsersPostRequestBody_user_rolesable)()
    SetUsername(value *string)()
    SetWindowsPassword(value *string)()
    SetWindowsUsername(value *string)()
}
