// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type BillingAccountItemAccountGetResponse_billingInfo struct {
    // The accountId property
    accountId *int64
    // The accountUUID property
    accountUUID *string
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The cost property
    cost *float64
    // The endDate property
    endDate *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The name property
    name *string
    // The price property
    price *float64
    // The priceUnit property
    priceUnit *string
    // The startDate property
    startDate *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The zones property
    zones []BillingAccountItemAccountGetResponse_billingInfo_zonesable
}
// NewBillingAccountItemAccountGetResponse_billingInfo instantiates a new BillingAccountItemAccountGetResponse_billingInfo and sets the default values.
func NewBillingAccountItemAccountGetResponse_billingInfo()(*BillingAccountItemAccountGetResponse_billingInfo) {
    m := &BillingAccountItemAccountGetResponse_billingInfo{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateBillingAccountItemAccountGetResponse_billingInfoFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateBillingAccountItemAccountGetResponse_billingInfoFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewBillingAccountItemAccountGetResponse_billingInfo(), nil
}
// GetAccountId gets the accountId property value. The accountId property
// returns a *int64 when successful
func (m *BillingAccountItemAccountGetResponse_billingInfo) GetAccountId()(*int64) {
    return m.accountId
}
// GetAccountUUID gets the accountUUID property value. The accountUUID property
// returns a *string when successful
func (m *BillingAccountItemAccountGetResponse_billingInfo) GetAccountUUID()(*string) {
    return m.accountUUID
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *BillingAccountItemAccountGetResponse_billingInfo) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCost gets the cost property value. The cost property
// returns a *float64 when successful
func (m *BillingAccountItemAccountGetResponse_billingInfo) GetCost()(*float64) {
    return m.cost
}
// GetEndDate gets the endDate property value. The endDate property
// returns a *Time when successful
func (m *BillingAccountItemAccountGetResponse_billingInfo) GetEndDate()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.endDate
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *BillingAccountItemAccountGetResponse_billingInfo) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["accountId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAccountId(val)
        }
        return nil
    }
    res["accountUUID"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAccountUUID(val)
        }
        return nil
    }
    res["cost"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCost(val)
        }
        return nil
    }
    res["endDate"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEndDate(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["price"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPrice(val)
        }
        return nil
    }
    res["priceUnit"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPriceUnit(val)
        }
        return nil
    }
    res["startDate"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStartDate(val)
        }
        return nil
    }
    res["zones"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateBillingAccountItemAccountGetResponse_billingInfo_zonesFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]BillingAccountItemAccountGetResponse_billingInfo_zonesable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(BillingAccountItemAccountGetResponse_billingInfo_zonesable)
                }
            }
            m.SetZones(res)
        }
        return nil
    }
    return res
}
// GetName gets the name property value. The name property
// returns a *string when successful
func (m *BillingAccountItemAccountGetResponse_billingInfo) GetName()(*string) {
    return m.name
}
// GetPrice gets the price property value. The price property
// returns a *float64 when successful
func (m *BillingAccountItemAccountGetResponse_billingInfo) GetPrice()(*float64) {
    return m.price
}
// GetPriceUnit gets the priceUnit property value. The priceUnit property
// returns a *string when successful
func (m *BillingAccountItemAccountGetResponse_billingInfo) GetPriceUnit()(*string) {
    return m.priceUnit
}
// GetStartDate gets the startDate property value. The startDate property
// returns a *Time when successful
func (m *BillingAccountItemAccountGetResponse_billingInfo) GetStartDate()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.startDate
}
// GetZones gets the zones property value. The zones property
// returns a []BillingAccountItemAccountGetResponse_billingInfo_zonesable when successful
func (m *BillingAccountItemAccountGetResponse_billingInfo) GetZones()([]BillingAccountItemAccountGetResponse_billingInfo_zonesable) {
    return m.zones
}
// Serialize serializes information the current object
func (m *BillingAccountItemAccountGetResponse_billingInfo) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt64Value("accountId", m.GetAccountId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("accountUUID", m.GetAccountUUID())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("cost", m.GetCost())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("endDate", m.GetEndDate())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("price", m.GetPrice())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("priceUnit", m.GetPriceUnit())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("startDate", m.GetStartDate())
        if err != nil {
            return err
        }
    }
    if m.GetZones() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetZones()))
        for i, v := range m.GetZones() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("zones", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAccountId sets the accountId property value. The accountId property
func (m *BillingAccountItemAccountGetResponse_billingInfo) SetAccountId(value *int64)() {
    m.accountId = value
}
// SetAccountUUID sets the accountUUID property value. The accountUUID property
func (m *BillingAccountItemAccountGetResponse_billingInfo) SetAccountUUID(value *string)() {
    m.accountUUID = value
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *BillingAccountItemAccountGetResponse_billingInfo) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCost sets the cost property value. The cost property
func (m *BillingAccountItemAccountGetResponse_billingInfo) SetCost(value *float64)() {
    m.cost = value
}
// SetEndDate sets the endDate property value. The endDate property
func (m *BillingAccountItemAccountGetResponse_billingInfo) SetEndDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.endDate = value
}
// SetName sets the name property value. The name property
func (m *BillingAccountItemAccountGetResponse_billingInfo) SetName(value *string)() {
    m.name = value
}
// SetPrice sets the price property value. The price property
func (m *BillingAccountItemAccountGetResponse_billingInfo) SetPrice(value *float64)() {
    m.price = value
}
// SetPriceUnit sets the priceUnit property value. The priceUnit property
func (m *BillingAccountItemAccountGetResponse_billingInfo) SetPriceUnit(value *string)() {
    m.priceUnit = value
}
// SetStartDate sets the startDate property value. The startDate property
func (m *BillingAccountItemAccountGetResponse_billingInfo) SetStartDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.startDate = value
}
// SetZones sets the zones property value. The zones property
func (m *BillingAccountItemAccountGetResponse_billingInfo) SetZones(value []BillingAccountItemAccountGetResponse_billingInfo_zonesable)() {
    m.zones = value
}
type BillingAccountItemAccountGetResponse_billingInfoable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAccountId()(*int64)
    GetAccountUUID()(*string)
    GetCost()(*float64)
    GetEndDate()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetName()(*string)
    GetPrice()(*float64)
    GetPriceUnit()(*string)
    GetStartDate()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetZones()([]BillingAccountItemAccountGetResponse_billingInfo_zonesable)
    SetAccountId(value *int64)()
    SetAccountUUID(value *string)()
    SetCost(value *float64)()
    SetEndDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetName(value *string)()
    SetPrice(value *float64)()
    SetPriceUnit(value *string)()
    SetStartDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetZones(value []BillingAccountItemAccountGetResponse_billingInfo_zonesable)()
}
