// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CatalogItemTypesCatalogItemTypesGetResponse_catalogItemType_blueprint struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
}
// NewCatalogItemTypesCatalogItemTypesGetResponse_catalogItemType_blueprint instantiates a new CatalogItemTypesCatalogItemTypesGetResponse_catalogItemType_blueprint and sets the default values.
func NewCatalogItemTypesCatalogItemTypesGetResponse_catalogItemType_blueprint()(*CatalogItemTypesCatalogItemTypesGetResponse_catalogItemType_blueprint) {
    m := &CatalogItemTypesCatalogItemTypesGetResponse_catalogItemType_blueprint{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateCatalogItemTypesCatalogItemTypesGetResponse_catalogItemType_blueprintFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCatalogItemTypesCatalogItemTypesGetResponse_catalogItemType_blueprintFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCatalogItemTypesCatalogItemTypesGetResponse_catalogItemType_blueprint(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CatalogItemTypesCatalogItemTypesGetResponse_catalogItemType_blueprint) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CatalogItemTypesCatalogItemTypesGetResponse_catalogItemType_blueprint) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    return res
}
// Serialize serializes information the current object
func (m *CatalogItemTypesCatalogItemTypesGetResponse_catalogItemType_blueprint) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CatalogItemTypesCatalogItemTypesGetResponse_catalogItemType_blueprint) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
type CatalogItemTypesCatalogItemTypesGetResponse_catalogItemType_blueprintable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
