// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type DeploymentsItemWithDeploymentPutRequestBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The deployment property
    deployment DeploymentsItemWithDeploymentPutRequestBody_deploymentable
}
// NewDeploymentsItemWithDeploymentPutRequestBody instantiates a new DeploymentsItemWithDeploymentPutRequestBody and sets the default values.
func NewDeploymentsItemWithDeploymentPutRequestBody()(*DeploymentsItemWithDeploymentPutRequestBody) {
    m := &DeploymentsItemWithDeploymentPutRequestBody{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateDeploymentsItemWithDeploymentPutRequestBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDeploymentsItemWithDeploymentPutRequestBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDeploymentsItemWithDeploymentPutRequestBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *DeploymentsItemWithDeploymentPutRequestBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetDeployment gets the deployment property value. The deployment property
// returns a DeploymentsItemWithDeploymentPutRequestBody_deploymentable when successful
func (m *DeploymentsItemWithDeploymentPutRequestBody) GetDeployment()(DeploymentsItemWithDeploymentPutRequestBody_deploymentable) {
    return m.deployment
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *DeploymentsItemWithDeploymentPutRequestBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["deployment"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateDeploymentsItemWithDeploymentPutRequestBody_deploymentFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDeployment(val.(DeploymentsItemWithDeploymentPutRequestBody_deploymentable))
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *DeploymentsItemWithDeploymentPutRequestBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("deployment", m.GetDeployment())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *DeploymentsItemWithDeploymentPutRequestBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetDeployment sets the deployment property value. The deployment property
func (m *DeploymentsItemWithDeploymentPutRequestBody) SetDeployment(value DeploymentsItemWithDeploymentPutRequestBody_deploymentable)() {
    m.deployment = value
}
type DeploymentsItemWithDeploymentPutRequestBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDeployment()(DeploymentsItemWithDeploymentPutRequestBody_deploymentable)
    SetDeployment(value DeploymentsItemWithDeploymentPutRequestBody_deploymentable)()
}
