// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type HealthGetResponse_health_elastic_master struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The host property
    host *string
    // The id property
    id *string
    // The ip property
    ip *string
    // The node property
    node *string
}
// NewHealthGetResponse_health_elastic_master instantiates a new HealthGetResponse_health_elastic_master and sets the default values.
func NewHealthGetResponse_health_elastic_master()(*HealthGetResponse_health_elastic_master) {
    m := &HealthGetResponse_health_elastic_master{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateHealthGetResponse_health_elastic_masterFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateHealthGetResponse_health_elastic_masterFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewHealthGetResponse_health_elastic_master(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *HealthGetResponse_health_elastic_master) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *HealthGetResponse_health_elastic_master) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["host"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHost(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["ip"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIp(val)
        }
        return nil
    }
    res["node"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNode(val)
        }
        return nil
    }
    return res
}
// GetHost gets the host property value. The host property
// returns a *string when successful
func (m *HealthGetResponse_health_elastic_master) GetHost()(*string) {
    return m.host
}
// GetId gets the id property value. The id property
// returns a *string when successful
func (m *HealthGetResponse_health_elastic_master) GetId()(*string) {
    return m.id
}
// GetIp gets the ip property value. The ip property
// returns a *string when successful
func (m *HealthGetResponse_health_elastic_master) GetIp()(*string) {
    return m.ip
}
// GetNode gets the node property value. The node property
// returns a *string when successful
func (m *HealthGetResponse_health_elastic_master) GetNode()(*string) {
    return m.node
}
// Serialize serializes information the current object
func (m *HealthGetResponse_health_elastic_master) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("host", m.GetHost())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("ip", m.GetIp())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("node", m.GetNode())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *HealthGetResponse_health_elastic_master) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetHost sets the host property value. The host property
func (m *HealthGetResponse_health_elastic_master) SetHost(value *string)() {
    m.host = value
}
// SetId sets the id property value. The id property
func (m *HealthGetResponse_health_elastic_master) SetId(value *string)() {
    m.id = value
}
// SetIp sets the ip property value. The ip property
func (m *HealthGetResponse_health_elastic_master) SetIp(value *string)() {
    m.ip = value
}
// SetNode sets the node property value. The node property
func (m *HealthGetResponse_health_elastic_master) SetNode(value *string)() {
    m.node = value
}
type HealthGetResponse_health_elastic_masterable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetHost()(*string)
    GetId()(*string)
    GetIp()(*string)
    GetNode()(*string)
    SetHost(value *string)()
    SetId(value *string)()
    SetIp(value *string)()
    SetNode(value *string)()
}
