// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ImageBuildsItemListExecutionsGetResponse_imageBuild_config_config struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The nestedVirtualization property
    nestedVirtualization *string
    // The resourcePoolId property
    resourcePoolId *int64
    // The template property
    template *int64
    // The vmwareFolderId property
    vmwareFolderId *string
}
// NewImageBuildsItemListExecutionsGetResponse_imageBuild_config_config instantiates a new ImageBuildsItemListExecutionsGetResponse_imageBuild_config_config and sets the default values.
func NewImageBuildsItemListExecutionsGetResponse_imageBuild_config_config()(*ImageBuildsItemListExecutionsGetResponse_imageBuild_config_config) {
    m := &ImageBuildsItemListExecutionsGetResponse_imageBuild_config_config{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateImageBuildsItemListExecutionsGetResponse_imageBuild_config_configFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateImageBuildsItemListExecutionsGetResponse_imageBuild_config_configFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewImageBuildsItemListExecutionsGetResponse_imageBuild_config_config(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ImageBuildsItemListExecutionsGetResponse_imageBuild_config_config) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ImageBuildsItemListExecutionsGetResponse_imageBuild_config_config) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["nestedVirtualization"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNestedVirtualization(val)
        }
        return nil
    }
    res["resourcePoolId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetResourcePoolId(val)
        }
        return nil
    }
    res["template"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTemplate(val)
        }
        return nil
    }
    res["vmwareFolderId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVmwareFolderId(val)
        }
        return nil
    }
    return res
}
// GetNestedVirtualization gets the nestedVirtualization property value. The nestedVirtualization property
// returns a *string when successful
func (m *ImageBuildsItemListExecutionsGetResponse_imageBuild_config_config) GetNestedVirtualization()(*string) {
    return m.nestedVirtualization
}
// GetResourcePoolId gets the resourcePoolId property value. The resourcePoolId property
// returns a *int64 when successful
func (m *ImageBuildsItemListExecutionsGetResponse_imageBuild_config_config) GetResourcePoolId()(*int64) {
    return m.resourcePoolId
}
// GetTemplate gets the template property value. The template property
// returns a *int64 when successful
func (m *ImageBuildsItemListExecutionsGetResponse_imageBuild_config_config) GetTemplate()(*int64) {
    return m.template
}
// GetVmwareFolderId gets the vmwareFolderId property value. The vmwareFolderId property
// returns a *string when successful
func (m *ImageBuildsItemListExecutionsGetResponse_imageBuild_config_config) GetVmwareFolderId()(*string) {
    return m.vmwareFolderId
}
// Serialize serializes information the current object
func (m *ImageBuildsItemListExecutionsGetResponse_imageBuild_config_config) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("nestedVirtualization", m.GetNestedVirtualization())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("resourcePoolId", m.GetResourcePoolId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("template", m.GetTemplate())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("vmwareFolderId", m.GetVmwareFolderId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ImageBuildsItemListExecutionsGetResponse_imageBuild_config_config) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetNestedVirtualization sets the nestedVirtualization property value. The nestedVirtualization property
func (m *ImageBuildsItemListExecutionsGetResponse_imageBuild_config_config) SetNestedVirtualization(value *string)() {
    m.nestedVirtualization = value
}
// SetResourcePoolId sets the resourcePoolId property value. The resourcePoolId property
func (m *ImageBuildsItemListExecutionsGetResponse_imageBuild_config_config) SetResourcePoolId(value *int64)() {
    m.resourcePoolId = value
}
// SetTemplate sets the template property value. The template property
func (m *ImageBuildsItemListExecutionsGetResponse_imageBuild_config_config) SetTemplate(value *int64)() {
    m.template = value
}
// SetVmwareFolderId sets the vmwareFolderId property value. The vmwareFolderId property
func (m *ImageBuildsItemListExecutionsGetResponse_imageBuild_config_config) SetVmwareFolderId(value *string)() {
    m.vmwareFolderId = value
}
type ImageBuildsItemListExecutionsGetResponse_imageBuild_config_configable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetNestedVirtualization()(*string)
    GetResourcePoolId()(*int64)
    GetTemplate()(*int64)
    GetVmwareFolderId()(*string)
    SetNestedVirtualization(value *string)()
    SetResourcePoolId(value *int64)()
    SetTemplate(value *int64)()
    SetVmwareFolderId(value *string)()
}
