// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type InstancesGetResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The instances property
    instances []InstancesGetResponse_instancesable
    // The meta property
    meta InstancesGetResponse_metaable
}
// NewInstancesGetResponse instantiates a new InstancesGetResponse and sets the default values.
func NewInstancesGetResponse()(*InstancesGetResponse) {
    m := &InstancesGetResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateInstancesGetResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateInstancesGetResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewInstancesGetResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *InstancesGetResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *InstancesGetResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["instances"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateInstancesGetResponse_instancesFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]InstancesGetResponse_instancesable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(InstancesGetResponse_instancesable)
                }
            }
            m.SetInstances(res)
        }
        return nil
    }
    res["meta"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateInstancesGetResponse_metaFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMeta(val.(InstancesGetResponse_metaable))
        }
        return nil
    }
    return res
}
// GetInstances gets the instances property value. The instances property
// returns a []InstancesGetResponse_instancesable when successful
func (m *InstancesGetResponse) GetInstances()([]InstancesGetResponse_instancesable) {
    return m.instances
}
// GetMeta gets the meta property value. The meta property
// returns a InstancesGetResponse_metaable when successful
func (m *InstancesGetResponse) GetMeta()(InstancesGetResponse_metaable) {
    return m.meta
}
// Serialize serializes information the current object
func (m *InstancesGetResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetInstances() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetInstances()))
        for i, v := range m.GetInstances() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("instances", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("meta", m.GetMeta())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *InstancesGetResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetInstances sets the instances property value. The instances property
func (m *InstancesGetResponse) SetInstances(value []InstancesGetResponse_instancesable)() {
    m.instances = value
}
// SetMeta sets the meta property value. The meta property
func (m *InstancesGetResponse) SetMeta(value InstancesGetResponse_metaable)() {
    m.meta = value
}
type InstancesGetResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetInstances()([]InstancesGetResponse_instancesable)
    GetMeta()(InstancesGetResponse_metaable)
    SetInstances(value []InstancesGetResponse_instancesable)()
    SetMeta(value InstancesGetResponse_metaable)()
}
