// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use InstancesItemSchedulesGetResponseable instead.
type InstancesItemSchedulesResponse struct {
    InstancesItemSchedulesGetResponse
}
// NewInstancesItemSchedulesResponse instantiates a new InstancesItemSchedulesResponse and sets the default values.
func NewInstancesItemSchedulesResponse()(*InstancesItemSchedulesResponse) {
    m := &InstancesItemSchedulesResponse{
        InstancesItemSchedulesGetResponse: *NewInstancesItemSchedulesGetResponse(),
    }
    return m
}
// CreateInstancesItemSchedulesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateInstancesItemSchedulesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewInstancesItemSchedulesResponse(), nil
}
// Deprecated: This class is obsolete. Use InstancesItemSchedulesGetResponseable instead.
type InstancesItemSchedulesResponseable interface {
    InstancesItemSchedulesGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
