// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type IntegrationsItemRefreshPostResponse_integrationMember13 struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The config property
    config IntegrationsItemRefreshPostResponse_integrationMember13_configable
    // The credential property
    credential IntegrationsItemRefreshPostResponse_integrationMember13_credentialable
    // The enabled property
    enabled *bool
    // The id property
    id *int64
    // The integrationType property
    integrationType IntegrationsItemRefreshPostResponse_integrationMember13_integrationTypeable
    // The isPlugin property
    isPlugin *bool
    // The lastSync property
    lastSync *string
    // The lastSyncDuration property
    lastSyncDuration *string
    // The name property
    name *string
    // The password property
    password *string
    // The passwordHash property
    passwordHash *string
    // The status property
    status *string
    // The statusDate property
    statusDate *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The statusMessage property
    statusMessage *string
    // The url property
    url *string
    // The username property
    username *string
}
// NewIntegrationsItemRefreshPostResponse_integrationMember13 instantiates a new IntegrationsItemRefreshPostResponse_integrationMember13 and sets the default values.
func NewIntegrationsItemRefreshPostResponse_integrationMember13()(*IntegrationsItemRefreshPostResponse_integrationMember13) {
    m := &IntegrationsItemRefreshPostResponse_integrationMember13{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateIntegrationsItemRefreshPostResponse_integrationMember13FromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateIntegrationsItemRefreshPostResponse_integrationMember13FromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewIntegrationsItemRefreshPostResponse_integrationMember13(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetConfig gets the config property value. The config property
// returns a IntegrationsItemRefreshPostResponse_integrationMember13_configable when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetConfig()(IntegrationsItemRefreshPostResponse_integrationMember13_configable) {
    return m.config
}
// GetCredential gets the credential property value. The credential property
// returns a IntegrationsItemRefreshPostResponse_integrationMember13_credentialable when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetCredential()(IntegrationsItemRefreshPostResponse_integrationMember13_credentialable) {
    return m.credential
}
// GetEnabled gets the enabled property value. The enabled property
// returns a *bool when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetEnabled()(*bool) {
    return m.enabled
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["config"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateIntegrationsItemRefreshPostResponse_integrationMember13_configFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetConfig(val.(IntegrationsItemRefreshPostResponse_integrationMember13_configable))
        }
        return nil
    }
    res["credential"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateIntegrationsItemRefreshPostResponse_integrationMember13_credentialFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCredential(val.(IntegrationsItemRefreshPostResponse_integrationMember13_credentialable))
        }
        return nil
    }
    res["enabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEnabled(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["integrationType"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateIntegrationsItemRefreshPostResponse_integrationMember13_integrationTypeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIntegrationType(val.(IntegrationsItemRefreshPostResponse_integrationMember13_integrationTypeable))
        }
        return nil
    }
    res["isPlugin"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIsPlugin(val)
        }
        return nil
    }
    res["lastSync"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLastSync(val)
        }
        return nil
    }
    res["lastSyncDuration"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLastSyncDuration(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["password"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPassword(val)
        }
        return nil
    }
    res["passwordHash"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPasswordHash(val)
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val)
        }
        return nil
    }
    res["statusDate"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatusDate(val)
        }
        return nil
    }
    res["statusMessage"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatusMessage(val)
        }
        return nil
    }
    res["url"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUrl(val)
        }
        return nil
    }
    res["username"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUsername(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The id property
// returns a *int64 when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetId()(*int64) {
    return m.id
}
// GetIntegrationType gets the integrationType property value. The integrationType property
// returns a IntegrationsItemRefreshPostResponse_integrationMember13_integrationTypeable when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetIntegrationType()(IntegrationsItemRefreshPostResponse_integrationMember13_integrationTypeable) {
    return m.integrationType
}
// GetIsPlugin gets the isPlugin property value. The isPlugin property
// returns a *bool when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetIsPlugin()(*bool) {
    return m.isPlugin
}
// GetLastSync gets the lastSync property value. The lastSync property
// returns a *string when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetLastSync()(*string) {
    return m.lastSync
}
// GetLastSyncDuration gets the lastSyncDuration property value. The lastSyncDuration property
// returns a *string when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetLastSyncDuration()(*string) {
    return m.lastSyncDuration
}
// GetName gets the name property value. The name property
// returns a *string when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetName()(*string) {
    return m.name
}
// GetPassword gets the password property value. The password property
// returns a *string when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetPassword()(*string) {
    return m.password
}
// GetPasswordHash gets the passwordHash property value. The passwordHash property
// returns a *string when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetPasswordHash()(*string) {
    return m.passwordHash
}
// GetStatus gets the status property value. The status property
// returns a *string when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetStatus()(*string) {
    return m.status
}
// GetStatusDate gets the statusDate property value. The statusDate property
// returns a *Time when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetStatusDate()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.statusDate
}
// GetStatusMessage gets the statusMessage property value. The statusMessage property
// returns a *string when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetStatusMessage()(*string) {
    return m.statusMessage
}
// GetUrl gets the url property value. The url property
// returns a *string when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetUrl()(*string) {
    return m.url
}
// GetUsername gets the username property value. The username property
// returns a *string when successful
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) GetUsername()(*string) {
    return m.username
}
// Serialize serializes information the current object
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("config", m.GetConfig())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("credential", m.GetCredential())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("enabled", m.GetEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("integrationType", m.GetIntegrationType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("isPlugin", m.GetIsPlugin())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("lastSync", m.GetLastSync())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("lastSyncDuration", m.GetLastSyncDuration())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("password", m.GetPassword())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("passwordHash", m.GetPasswordHash())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("status", m.GetStatus())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("statusDate", m.GetStatusDate())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("statusMessage", m.GetStatusMessage())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("url", m.GetUrl())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("username", m.GetUsername())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetConfig sets the config property value. The config property
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) SetConfig(value IntegrationsItemRefreshPostResponse_integrationMember13_configable)() {
    m.config = value
}
// SetCredential sets the credential property value. The credential property
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) SetCredential(value IntegrationsItemRefreshPostResponse_integrationMember13_credentialable)() {
    m.credential = value
}
// SetEnabled sets the enabled property value. The enabled property
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) SetEnabled(value *bool)() {
    m.enabled = value
}
// SetId sets the id property value. The id property
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) SetId(value *int64)() {
    m.id = value
}
// SetIntegrationType sets the integrationType property value. The integrationType property
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) SetIntegrationType(value IntegrationsItemRefreshPostResponse_integrationMember13_integrationTypeable)() {
    m.integrationType = value
}
// SetIsPlugin sets the isPlugin property value. The isPlugin property
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) SetIsPlugin(value *bool)() {
    m.isPlugin = value
}
// SetLastSync sets the lastSync property value. The lastSync property
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) SetLastSync(value *string)() {
    m.lastSync = value
}
// SetLastSyncDuration sets the lastSyncDuration property value. The lastSyncDuration property
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) SetLastSyncDuration(value *string)() {
    m.lastSyncDuration = value
}
// SetName sets the name property value. The name property
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) SetName(value *string)() {
    m.name = value
}
// SetPassword sets the password property value. The password property
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) SetPassword(value *string)() {
    m.password = value
}
// SetPasswordHash sets the passwordHash property value. The passwordHash property
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) SetPasswordHash(value *string)() {
    m.passwordHash = value
}
// SetStatus sets the status property value. The status property
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) SetStatus(value *string)() {
    m.status = value
}
// SetStatusDate sets the statusDate property value. The statusDate property
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) SetStatusDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.statusDate = value
}
// SetStatusMessage sets the statusMessage property value. The statusMessage property
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) SetStatusMessage(value *string)() {
    m.statusMessage = value
}
// SetUrl sets the url property value. The url property
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) SetUrl(value *string)() {
    m.url = value
}
// SetUsername sets the username property value. The username property
func (m *IntegrationsItemRefreshPostResponse_integrationMember13) SetUsername(value *string)() {
    m.username = value
}
type IntegrationsItemRefreshPostResponse_integrationMember13able interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetConfig()(IntegrationsItemRefreshPostResponse_integrationMember13_configable)
    GetCredential()(IntegrationsItemRefreshPostResponse_integrationMember13_credentialable)
    GetEnabled()(*bool)
    GetId()(*int64)
    GetIntegrationType()(IntegrationsItemRefreshPostResponse_integrationMember13_integrationTypeable)
    GetIsPlugin()(*bool)
    GetLastSync()(*string)
    GetLastSyncDuration()(*string)
    GetName()(*string)
    GetPassword()(*string)
    GetPasswordHash()(*string)
    GetStatus()(*string)
    GetStatusDate()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetStatusMessage()(*string)
    GetUrl()(*string)
    GetUsername()(*string)
    SetConfig(value IntegrationsItemRefreshPostResponse_integrationMember13_configable)()
    SetCredential(value IntegrationsItemRefreshPostResponse_integrationMember13_credentialable)()
    SetEnabled(value *bool)()
    SetId(value *int64)()
    SetIntegrationType(value IntegrationsItemRefreshPostResponse_integrationMember13_integrationTypeable)()
    SetIsPlugin(value *bool)()
    SetLastSync(value *string)()
    SetLastSyncDuration(value *string)()
    SetName(value *string)()
    SetPassword(value *string)()
    SetPasswordHash(value *string)()
    SetStatus(value *string)()
    SetStatusDate(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetStatusMessage(value *string)()
    SetUrl(value *string)()
    SetUsername(value *string)()
}
