// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use InvoiceLineItemsInvoiceLineItemsGetResponseable instead.
type InvoiceLineItemsInvoiceLineItemsResponse struct {
    InvoiceLineItemsInvoiceLineItemsGetResponse
}
// NewInvoiceLineItemsInvoiceLineItemsResponse instantiates a new InvoiceLineItemsInvoiceLineItemsResponse and sets the default values.
func NewInvoiceLineItemsInvoiceLineItemsResponse()(*InvoiceLineItemsInvoiceLineItemsResponse) {
    m := &InvoiceLineItemsInvoiceLineItemsResponse{
        InvoiceLineItemsInvoiceLineItemsGetResponse: *NewInvoiceLineItemsInvoiceLineItemsGetResponse(),
    }
    return m
}
// CreateInvoiceLineItemsInvoiceLineItemsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateInvoiceLineItemsInvoiceLineItemsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewInvoiceLineItemsInvoiceLineItemsResponse(), nil
}
// Deprecated: This class is obsolete. Use InvoiceLineItemsInvoiceLineItemsGetResponseable instead.
type InvoiceLineItemsInvoiceLineItemsResponseable interface {
    InvoiceLineItemsInvoiceLineItemsGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
