// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type LibraryOptionTypesItemOptionTypesPutRequestBody_optionType_optionList struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // ID of Option List. For use with type select, this will set optionSource to the list.
    id *int64
}
// NewLibraryOptionTypesItemOptionTypesPutRequestBody_optionType_optionList instantiates a new LibraryOptionTypesItemOptionTypesPutRequestBody_optionType_optionList and sets the default values.
func NewLibraryOptionTypesItemOptionTypesPutRequestBody_optionType_optionList()(*LibraryOptionTypesItemOptionTypesPutRequestBody_optionType_optionList) {
    m := &LibraryOptionTypesItemOptionTypesPutRequestBody_optionType_optionList{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateLibraryOptionTypesItemOptionTypesPutRequestBody_optionType_optionListFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateLibraryOptionTypesItemOptionTypesPutRequestBody_optionType_optionListFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewLibraryOptionTypesItemOptionTypesPutRequestBody_optionType_optionList(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *LibraryOptionTypesItemOptionTypesPutRequestBody_optionType_optionList) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *LibraryOptionTypesItemOptionTypesPutRequestBody_optionType_optionList) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. ID of Option List. For use with type select, this will set optionSource to the list.
// returns a *int64 when successful
func (m *LibraryOptionTypesItemOptionTypesPutRequestBody_optionType_optionList) GetId()(*int64) {
    return m.id
}
// Serialize serializes information the current object
func (m *LibraryOptionTypesItemOptionTypesPutRequestBody_optionType_optionList) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt64Value("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *LibraryOptionTypesItemOptionTypesPutRequestBody_optionType_optionList) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetId sets the id property value. ID of Option List. For use with type select, this will set optionSource to the list.
func (m *LibraryOptionTypesItemOptionTypesPutRequestBody_optionType_optionList) SetId(value *int64)() {
    m.id = value
}
type LibraryOptionTypesItemOptionTypesPutRequestBody_optionType_optionListable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetId()(*int64)
    SetId(value *int64)()
}
