// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i774d87b5a417b14ee70d9499d93f0c74f61056e750017b993346984d85d7b6fc "ApiSdk/api/logs"
)

// LogsRequestBuilder builds and executes requests for operations under \api\logs
type LogsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// LogsRequestBuilderGetQueryParameters retrieves logs based on filters provided.
type LogsRequestBuilderGetQueryParameters struct {
    // The Cluster ID(s) for filtering. Accepts multiple values.
    ClusterId *int64 `uriparametername:"clusterId"`
    // The Container ID(s) for filtering. Accepts multiple values.
    Containers *int64 `uriparametername:"containers"`
    // End Date timestamp (ISO 8601)
    EndDateTime *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time `uriparametername:"endDateTime"`
    // Date filter in milliseconds (unix epoch), restricts query to only load logs updated before the time specified.
    EndMs *int64 `uriparametername:"endMs"`
    // Filter by log level. Multiple values can be passed pipe delimited.
    // Deprecated: This property is deprecated, use LevelAsGetLevelQueryParameterType instead
    Level *string `uriparametername:"level"`
    // Filter by log level. Multiple values can be passed pipe delimited.
    LevelAsGetLevelQueryParameterType *i774d87b5a417b14ee70d9499d93f0c74f61056e750017b993346984d85d7b6fc.GetLevelQueryParameterType `uriparametername:"level"`
    // Maximum number of records to return
    Max *int64 `uriparametername:"max"`
    // Filter by message
    Message *string `uriparametername:"message"`
    // Filter by objectId
    ObjectId *int64 `uriparametername:"objectId"`
    // Offset records, the number of records to skip, for paginating requests
    Offset *int64 `uriparametername:"offset"`
    // Sort direction, use 'desc' to reverse sort
    // Deprecated: This property is deprecated, use OrderAsGetOrderQueryParameterType instead
    Order *string `uriparametername:"order"`
    // Sort direction, use 'desc' to reverse sort
    OrderAsGetOrderQueryParameterType *i774d87b5a417b14ee70d9499d93f0c74f61056e750017b993346984d85d7b6fc.GetOrderQueryParameterType `uriparametername:"order"`
    // Alias for phrase
    Query *string `uriparametername:"query"`
    // The Server ID(s) for filtering. Accepts multiple values.
    Servers *int64 `uriparametername:"servers"`
    // Sort order, the name of the property to sort by
    Sort *string `uriparametername:"sort"`
    // Filter by source type
    SourceType *string `uriparametername:"sourceType"`
    // Start Date timestamp (ISO 8601)
    StartDateTime *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time `uriparametername:"startDateTime"`
    // Date filter in milliseconds (unix epoch), restricts query to only load logs updated more recently than the time specified.
    StartMs *int64 `uriparametername:"startMs"`
    // Filter by token
    Token *string `uriparametername:"token"`
    // Filter by code type
    TypeCode *string `uriparametername:"typeCode"`
}
// LogsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type LogsRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *LogsRequestBuilderGetQueryParameters
}
// NewLogsRequestBuilderInternal instantiates a new LogsRequestBuilder and sets the default values.
func NewLogsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*LogsRequestBuilder) {
    m := &LogsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/logs{?clusterId*,containers*,endDateTime*,endMs*,level*,max*,message*,objectId*,offset*,order*,query*,servers*,sort*,sourceType*,startDateTime*,startMs*,token*,typeCode*}", pathParameters),
    }
    return m
}
// NewLogsRequestBuilder instantiates a new LogsRequestBuilder and sets the default values.
func NewLogsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*LogsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewLogsRequestBuilderInternal(urlParams, requestAdapter)
}
// Get retrieves logs based on filters provided.
// Deprecated: This method is obsolete. Use GetAsLogsGetResponse instead.
// returns a LogsResponseable when successful
// returns a Logs4XXError error when the service returns a 4XX status code
// returns a Logs5XXError error when the service returns a 5XX status code
func (m *LogsRequestBuilder) Get(ctx context.Context, requestConfiguration *LogsRequestBuilderGetRequestConfiguration)(LogsResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "4XX": CreateLogs4XXErrorFromDiscriminatorValue,
        "5XX": CreateLogs5XXErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateLogsResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(LogsResponseable), nil
}
// GetAsLogsGetResponse retrieves logs based on filters provided.
// returns a LogsGetResponseable when successful
// returns a Logs4XXError error when the service returns a 4XX status code
// returns a Logs5XXError error when the service returns a 5XX status code
func (m *LogsRequestBuilder) GetAsLogsGetResponse(ctx context.Context, requestConfiguration *LogsRequestBuilderGetRequestConfiguration)(LogsGetResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "4XX": CreateLogs4XXErrorFromDiscriminatorValue,
        "5XX": CreateLogs5XXErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateLogsGetResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(LogsGetResponseable), nil
}
// ToGetRequestInformation retrieves logs based on filters provided.
// returns a *RequestInformation when successful
func (m *LogsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *LogsRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *LogsRequestBuilder when successful
func (m *LogsRequestBuilder) WithUrl(rawUrl string)(*LogsRequestBuilder) {
    return NewLogsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
