// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type MonitoringChecksItemChecksPutResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The check property
    check MonitoringChecksItemChecksPutResponse_checkable
    // The success property
    success *bool
}
// NewMonitoringChecksItemChecksPutResponse instantiates a new MonitoringChecksItemChecksPutResponse and sets the default values.
func NewMonitoringChecksItemChecksPutResponse()(*MonitoringChecksItemChecksPutResponse) {
    m := &MonitoringChecksItemChecksPutResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateMonitoringChecksItemChecksPutResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMonitoringChecksItemChecksPutResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewMonitoringChecksItemChecksPutResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *MonitoringChecksItemChecksPutResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCheck gets the check property value. The check property
// returns a MonitoringChecksItemChecksPutResponse_checkable when successful
func (m *MonitoringChecksItemChecksPutResponse) GetCheck()(MonitoringChecksItemChecksPutResponse_checkable) {
    return m.check
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *MonitoringChecksItemChecksPutResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["check"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateMonitoringChecksItemChecksPutResponse_checkFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCheck(val.(MonitoringChecksItemChecksPutResponse_checkable))
        }
        return nil
    }
    res["success"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSuccess(val)
        }
        return nil
    }
    return res
}
// GetSuccess gets the success property value. The success property
// returns a *bool when successful
func (m *MonitoringChecksItemChecksPutResponse) GetSuccess()(*bool) {
    return m.success
}
// Serialize serializes information the current object
func (m *MonitoringChecksItemChecksPutResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("check", m.GetCheck())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("success", m.GetSuccess())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *MonitoringChecksItemChecksPutResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCheck sets the check property value. The check property
func (m *MonitoringChecksItemChecksPutResponse) SetCheck(value MonitoringChecksItemChecksPutResponse_checkable)() {
    m.check = value
}
// SetSuccess sets the success property value. The success property
func (m *MonitoringChecksItemChecksPutResponse) SetSuccess(value *bool)() {
    m.success = value
}
type MonitoringChecksItemChecksPutResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCheck()(MonitoringChecksItemChecksPutResponse_checkable)
    GetSuccess()(*bool)
    SetCheck(value MonitoringChecksItemChecksPutResponse_checkable)()
    SetSuccess(value *bool)()
}
