// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type NetworksItemNetworksPutRequestBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The network property
    network NetworksItemNetworksPutRequestBody_networkable
}
// NewNetworksItemNetworksPutRequestBody instantiates a new NetworksItemNetworksPutRequestBody and sets the default values.
func NewNetworksItemNetworksPutRequestBody()(*NetworksItemNetworksPutRequestBody) {
    m := &NetworksItemNetworksPutRequestBody{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateNetworksItemNetworksPutRequestBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateNetworksItemNetworksPutRequestBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewNetworksItemNetworksPutRequestBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *NetworksItemNetworksPutRequestBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *NetworksItemNetworksPutRequestBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["network"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateNetworksItemNetworksPutRequestBody_networkFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNetwork(val.(NetworksItemNetworksPutRequestBody_networkable))
        }
        return nil
    }
    return res
}
// GetNetwork gets the network property value. The network property
// returns a NetworksItemNetworksPutRequestBody_networkable when successful
func (m *NetworksItemNetworksPutRequestBody) GetNetwork()(NetworksItemNetworksPutRequestBody_networkable) {
    return m.network
}
// Serialize serializes information the current object
func (m *NetworksItemNetworksPutRequestBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("network", m.GetNetwork())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *NetworksItemNetworksPutRequestBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetNetwork sets the network property value. The network property
func (m *NetworksItemNetworksPutRequestBody) SetNetwork(value NetworksItemNetworksPutRequestBody_networkable)() {
    m.network = value
}
type NetworksItemNetworksPutRequestBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetNetwork()(NetworksItemNetworksPutRequestBody_networkable)
    SetNetwork(value NetworksItemNetworksPutRequestBody_networkable)()
}
