// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type NetworksPoolServersItemPoolServersPutResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The networkPoolServer property
    networkPoolServer NetworksPoolServersItemPoolServersPutResponse_networkPoolServerable
    // The success property
    success *bool
}
// NewNetworksPoolServersItemPoolServersPutResponse instantiates a new NetworksPoolServersItemPoolServersPutResponse and sets the default values.
func NewNetworksPoolServersItemPoolServersPutResponse()(*NetworksPoolServersItemPoolServersPutResponse) {
    m := &NetworksPoolServersItemPoolServersPutResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateNetworksPoolServersItemPoolServersPutResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateNetworksPoolServersItemPoolServersPutResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewNetworksPoolServersItemPoolServersPutResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *NetworksPoolServersItemPoolServersPutResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *NetworksPoolServersItemPoolServersPutResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["networkPoolServer"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateNetworksPoolServersItemPoolServersPutResponse_networkPoolServerFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNetworkPoolServer(val.(NetworksPoolServersItemPoolServersPutResponse_networkPoolServerable))
        }
        return nil
    }
    res["success"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSuccess(val)
        }
        return nil
    }
    return res
}
// GetNetworkPoolServer gets the networkPoolServer property value. The networkPoolServer property
// returns a NetworksPoolServersItemPoolServersPutResponse_networkPoolServerable when successful
func (m *NetworksPoolServersItemPoolServersPutResponse) GetNetworkPoolServer()(NetworksPoolServersItemPoolServersPutResponse_networkPoolServerable) {
    return m.networkPoolServer
}
// GetSuccess gets the success property value. The success property
// returns a *bool when successful
func (m *NetworksPoolServersItemPoolServersPutResponse) GetSuccess()(*bool) {
    return m.success
}
// Serialize serializes information the current object
func (m *NetworksPoolServersItemPoolServersPutResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("networkPoolServer", m.GetNetworkPoolServer())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("success", m.GetSuccess())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *NetworksPoolServersItemPoolServersPutResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetNetworkPoolServer sets the networkPoolServer property value. The networkPoolServer property
func (m *NetworksPoolServersItemPoolServersPutResponse) SetNetworkPoolServer(value NetworksPoolServersItemPoolServersPutResponse_networkPoolServerable)() {
    m.networkPoolServer = value
}
// SetSuccess sets the success property value. The success property
func (m *NetworksPoolServersItemPoolServersPutResponse) SetSuccess(value *bool)() {
    m.success = value
}
type NetworksPoolServersItemPoolServersPutResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetNetworkPoolServer()(NetworksPoolServersItemPoolServersPutResponse_networkPoolServerable)
    GetSuccess()(*bool)
    SetNetworkPoolServer(value NetworksPoolServersItemPoolServersPutResponse_networkPoolServerable)()
    SetSuccess(value *bool)()
}
