// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type NetworksServersItemEdgeClustersGetResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The meta property
    meta NetworksServersItemEdgeClustersGetResponse_metaable
    // The networkEdgeClusters property
    networkEdgeClusters i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable
}
// NewNetworksServersItemEdgeClustersGetResponse instantiates a new NetworksServersItemEdgeClustersGetResponse and sets the default values.
func NewNetworksServersItemEdgeClustersGetResponse()(*NetworksServersItemEdgeClustersGetResponse) {
    m := &NetworksServersItemEdgeClustersGetResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateNetworksServersItemEdgeClustersGetResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateNetworksServersItemEdgeClustersGetResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewNetworksServersItemEdgeClustersGetResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *NetworksServersItemEdgeClustersGetResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *NetworksServersItemEdgeClustersGetResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["meta"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateNetworksServersItemEdgeClustersGetResponse_metaFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMeta(val.(NetworksServersItemEdgeClustersGetResponse_metaable))
        }
        return nil
    }
    res["networkEdgeClusters"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNetworkEdgeClusters(val.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable))
        }
        return nil
    }
    return res
}
// GetMeta gets the meta property value. The meta property
// returns a NetworksServersItemEdgeClustersGetResponse_metaable when successful
func (m *NetworksServersItemEdgeClustersGetResponse) GetMeta()(NetworksServersItemEdgeClustersGetResponse_metaable) {
    return m.meta
}
// GetNetworkEdgeClusters gets the networkEdgeClusters property value. The networkEdgeClusters property
// returns a UntypedNodeable when successful
func (m *NetworksServersItemEdgeClustersGetResponse) GetNetworkEdgeClusters()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable) {
    return m.networkEdgeClusters
}
// Serialize serializes information the current object
func (m *NetworksServersItemEdgeClustersGetResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("meta", m.GetMeta())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("networkEdgeClusters", m.GetNetworkEdgeClusters())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *NetworksServersItemEdgeClustersGetResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetMeta sets the meta property value. The meta property
func (m *NetworksServersItemEdgeClustersGetResponse) SetMeta(value NetworksServersItemEdgeClustersGetResponse_metaable)() {
    m.meta = value
}
// SetNetworkEdgeClusters sets the networkEdgeClusters property value. The networkEdgeClusters property
func (m *NetworksServersItemEdgeClustersGetResponse) SetNetworkEdgeClusters(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)() {
    m.networkEdgeClusters = value
}
type NetworksServersItemEdgeClustersGetResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetMeta()(NetworksServersItemEdgeClustersGetResponse_metaable)
    GetNetworkEdgeClusters()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)
    SetMeta(value NetworksServersItemEdgeClustersGetResponse_metaable)()
    SetNetworkEdgeClusters(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)()
}
