// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use NetworksRoutersItemFirewallRuleGroupsGetResponseable instead.
type NetworksRoutersItemFirewallRuleGroupsResponse struct {
    NetworksRoutersItemFirewallRuleGroupsGetResponse
}
// NewNetworksRoutersItemFirewallRuleGroupsResponse instantiates a new NetworksRoutersItemFirewallRuleGroupsResponse and sets the default values.
func NewNetworksRoutersItemFirewallRuleGroupsResponse()(*NetworksRoutersItemFirewallRuleGroupsResponse) {
    m := &NetworksRoutersItemFirewallRuleGroupsResponse{
        NetworksRoutersItemFirewallRuleGroupsGetResponse: *NewNetworksRoutersItemFirewallRuleGroupsGetResponse(),
    }
    return m
}
// CreateNetworksRoutersItemFirewallRuleGroupsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateNetworksRoutersItemFirewallRuleGroupsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewNetworksRoutersItemFirewallRuleGroupsResponse(), nil
}
// Deprecated: This class is obsolete. Use NetworksRoutersItemFirewallRuleGroupsGetResponseable instead.
type NetworksRoutersItemFirewallRuleGroupsResponseable interface {
    NetworksRoutersItemFirewallRuleGroupsGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
