// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// OptionsZoneTypesRequestBuilder builds and executes requests for operations under \api\options\zoneTypes
type OptionsZoneTypesRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// OptionsZoneTypesRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type OptionsZoneTypesRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewOptionsZoneTypesRequestBuilderInternal instantiates a new OptionsZoneTypesRequestBuilder and sets the default values.
func NewOptionsZoneTypesRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*OptionsZoneTypesRequestBuilder) {
    m := &OptionsZoneTypesRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/options/zoneTypes", pathParameters),
    }
    return m
}
// NewOptionsZoneTypesRequestBuilder instantiates a new OptionsZoneTypesRequestBuilder and sets the default values.
func NewOptionsZoneTypesRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*OptionsZoneTypesRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewOptionsZoneTypesRequestBuilderInternal(urlParams, requestAdapter)
}
// Get this endpoint can be used to see which zone/cloud types are enabled for the current tenant
// Deprecated: This method is obsolete. Use GetAsZoneTypesGetResponse instead.
// returns a OptionsZoneTypesResponseable when successful
// returns a OptionsZoneTypes4XXError error when the service returns a 4XX status code
// returns a OptionsZoneTypes5XXError error when the service returns a 5XX status code
func (m *OptionsZoneTypesRequestBuilder) Get(ctx context.Context, requestConfiguration *OptionsZoneTypesRequestBuilderGetRequestConfiguration)(OptionsZoneTypesResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "4XX": CreateOptionsZoneTypes4XXErrorFromDiscriminatorValue,
        "5XX": CreateOptionsZoneTypes5XXErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateOptionsZoneTypesResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(OptionsZoneTypesResponseable), nil
}
// GetAsZoneTypesGetResponse this endpoint can be used to see which zone/cloud types are enabled for the current tenant
// returns a OptionsZoneTypesGetResponseable when successful
// returns a OptionsZoneTypes4XXError error when the service returns a 4XX status code
// returns a OptionsZoneTypes5XXError error when the service returns a 5XX status code
func (m *OptionsZoneTypesRequestBuilder) GetAsZoneTypesGetResponse(ctx context.Context, requestConfiguration *OptionsZoneTypesRequestBuilderGetRequestConfiguration)(OptionsZoneTypesGetResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "4XX": CreateOptionsZoneTypes4XXErrorFromDiscriminatorValue,
        "5XX": CreateOptionsZoneTypes5XXErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateOptionsZoneTypesGetResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(OptionsZoneTypesGetResponseable), nil
}
// ToGetRequestInformation this endpoint can be used to see which zone/cloud types are enabled for the current tenant
// returns a *RequestInformation when successful
func (m *OptionsZoneTypesRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *OptionsZoneTypesRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *OptionsZoneTypesRequestBuilder when successful
func (m *OptionsZoneTypesRequestBuilder) WithUrl(rawUrl string)(*OptionsZoneTypesRequestBuilder) {
    return NewOptionsZoneTypesRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
