// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type RolesItemUpdatePersonaPutRequestBodyMember1 struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // code of the Persona, eg. `standard` or `serviceCatalog`
    personaCode *string
}
// NewRolesItemUpdatePersonaPutRequestBodyMember1 instantiates a new RolesItemUpdatePersonaPutRequestBodyMember1 and sets the default values.
func NewRolesItemUpdatePersonaPutRequestBodyMember1()(*RolesItemUpdatePersonaPutRequestBodyMember1) {
    m := &RolesItemUpdatePersonaPutRequestBodyMember1{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateRolesItemUpdatePersonaPutRequestBodyMember1FromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateRolesItemUpdatePersonaPutRequestBodyMember1FromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewRolesItemUpdatePersonaPutRequestBodyMember1(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *RolesItemUpdatePersonaPutRequestBodyMember1) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *RolesItemUpdatePersonaPutRequestBodyMember1) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["personaCode"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPersonaCode(val)
        }
        return nil
    }
    return res
}
// GetPersonaCode gets the personaCode property value. code of the Persona, eg. `standard` or `serviceCatalog`
// returns a *string when successful
func (m *RolesItemUpdatePersonaPutRequestBodyMember1) GetPersonaCode()(*string) {
    return m.personaCode
}
// Serialize serializes information the current object
func (m *RolesItemUpdatePersonaPutRequestBodyMember1) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("personaCode", m.GetPersonaCode())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *RolesItemUpdatePersonaPutRequestBodyMember1) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetPersonaCode sets the personaCode property value. code of the Persona, eg. `standard` or `serviceCatalog`
func (m *RolesItemUpdatePersonaPutRequestBodyMember1) SetPersonaCode(value *string)() {
    m.personaCode = value
}
type RolesItemUpdatePersonaPutRequestBodyMember1able interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetPersonaCode()(*string)
    SetPersonaCode(value *string)()
}
