// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ServersItemMakeManagedPutRequestBody_server_config_customOptions struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The dbfoldername property
    dbfoldername *string
}
// NewServersItemMakeManagedPutRequestBody_server_config_customOptions instantiates a new ServersItemMakeManagedPutRequestBody_server_config_customOptions and sets the default values.
func NewServersItemMakeManagedPutRequestBody_server_config_customOptions()(*ServersItemMakeManagedPutRequestBody_server_config_customOptions) {
    m := &ServersItemMakeManagedPutRequestBody_server_config_customOptions{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateServersItemMakeManagedPutRequestBody_server_config_customOptionsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateServersItemMakeManagedPutRequestBody_server_config_customOptionsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewServersItemMakeManagedPutRequestBody_server_config_customOptions(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ServersItemMakeManagedPutRequestBody_server_config_customOptions) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetDbfoldername gets the dbfoldername property value. The dbfoldername property
// returns a *string when successful
func (m *ServersItemMakeManagedPutRequestBody_server_config_customOptions) GetDbfoldername()(*string) {
    return m.dbfoldername
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ServersItemMakeManagedPutRequestBody_server_config_customOptions) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["dbfoldername"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDbfoldername(val)
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *ServersItemMakeManagedPutRequestBody_server_config_customOptions) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("dbfoldername", m.GetDbfoldername())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ServersItemMakeManagedPutRequestBody_server_config_customOptions) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetDbfoldername sets the dbfoldername property value. The dbfoldername property
func (m *ServersItemMakeManagedPutRequestBody_server_config_customOptions) SetDbfoldername(value *string)() {
    m.dbfoldername = value
}
type ServersItemMakeManagedPutRequestBody_server_config_customOptionsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDbfoldername()(*string)
    SetDbfoldername(value *string)()
}
