// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type SubnetTypesGetResponse_subnetTypes struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The canAssignPool property
    canAssignPool *bool
    // The code property
    code *string
    // The creatable property
    creatable *bool
    // The deletable property
    deletable *bool
    // The description property
    description *string
    // The dhcpServerEditable property
    dhcpServerEditable *bool
    // The id property
    id *int64
    // The name property
    name *string
    // The optionTypes property
    optionTypes []SubnetTypesGetResponse_subnetTypes_optionTypesable
}
// NewSubnetTypesGetResponse_subnetTypes instantiates a new SubnetTypesGetResponse_subnetTypes and sets the default values.
func NewSubnetTypesGetResponse_subnetTypes()(*SubnetTypesGetResponse_subnetTypes) {
    m := &SubnetTypesGetResponse_subnetTypes{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateSubnetTypesGetResponse_subnetTypesFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSubnetTypesGetResponse_subnetTypesFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSubnetTypesGetResponse_subnetTypes(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *SubnetTypesGetResponse_subnetTypes) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCanAssignPool gets the canAssignPool property value. The canAssignPool property
// returns a *bool when successful
func (m *SubnetTypesGetResponse_subnetTypes) GetCanAssignPool()(*bool) {
    return m.canAssignPool
}
// GetCode gets the code property value. The code property
// returns a *string when successful
func (m *SubnetTypesGetResponse_subnetTypes) GetCode()(*string) {
    return m.code
}
// GetCreatable gets the creatable property value. The creatable property
// returns a *bool when successful
func (m *SubnetTypesGetResponse_subnetTypes) GetCreatable()(*bool) {
    return m.creatable
}
// GetDeletable gets the deletable property value. The deletable property
// returns a *bool when successful
func (m *SubnetTypesGetResponse_subnetTypes) GetDeletable()(*bool) {
    return m.deletable
}
// GetDescription gets the description property value. The description property
// returns a *string when successful
func (m *SubnetTypesGetResponse_subnetTypes) GetDescription()(*string) {
    return m.description
}
// GetDhcpServerEditable gets the dhcpServerEditable property value. The dhcpServerEditable property
// returns a *bool when successful
func (m *SubnetTypesGetResponse_subnetTypes) GetDhcpServerEditable()(*bool) {
    return m.dhcpServerEditable
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *SubnetTypesGetResponse_subnetTypes) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["canAssignPool"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCanAssignPool(val)
        }
        return nil
    }
    res["code"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCode(val)
        }
        return nil
    }
    res["creatable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatable(val)
        }
        return nil
    }
    res["deletable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDeletable(val)
        }
        return nil
    }
    res["description"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDescription(val)
        }
        return nil
    }
    res["dhcpServerEditable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDhcpServerEditable(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["optionTypes"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateSubnetTypesGetResponse_subnetTypes_optionTypesFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]SubnetTypesGetResponse_subnetTypes_optionTypesable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(SubnetTypesGetResponse_subnetTypes_optionTypesable)
                }
            }
            m.SetOptionTypes(res)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The id property
// returns a *int64 when successful
func (m *SubnetTypesGetResponse_subnetTypes) GetId()(*int64) {
    return m.id
}
// GetName gets the name property value. The name property
// returns a *string when successful
func (m *SubnetTypesGetResponse_subnetTypes) GetName()(*string) {
    return m.name
}
// GetOptionTypes gets the optionTypes property value. The optionTypes property
// returns a []SubnetTypesGetResponse_subnetTypes_optionTypesable when successful
func (m *SubnetTypesGetResponse_subnetTypes) GetOptionTypes()([]SubnetTypesGetResponse_subnetTypes_optionTypesable) {
    return m.optionTypes
}
// Serialize serializes information the current object
func (m *SubnetTypesGetResponse_subnetTypes) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("canAssignPool", m.GetCanAssignPool())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("code", m.GetCode())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("creatable", m.GetCreatable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("deletable", m.GetDeletable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("description", m.GetDescription())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("dhcpServerEditable", m.GetDhcpServerEditable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt64Value("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    if m.GetOptionTypes() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetOptionTypes()))
        for i, v := range m.GetOptionTypes() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("optionTypes", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *SubnetTypesGetResponse_subnetTypes) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCanAssignPool sets the canAssignPool property value. The canAssignPool property
func (m *SubnetTypesGetResponse_subnetTypes) SetCanAssignPool(value *bool)() {
    m.canAssignPool = value
}
// SetCode sets the code property value. The code property
func (m *SubnetTypesGetResponse_subnetTypes) SetCode(value *string)() {
    m.code = value
}
// SetCreatable sets the creatable property value. The creatable property
func (m *SubnetTypesGetResponse_subnetTypes) SetCreatable(value *bool)() {
    m.creatable = value
}
// SetDeletable sets the deletable property value. The deletable property
func (m *SubnetTypesGetResponse_subnetTypes) SetDeletable(value *bool)() {
    m.deletable = value
}
// SetDescription sets the description property value. The description property
func (m *SubnetTypesGetResponse_subnetTypes) SetDescription(value *string)() {
    m.description = value
}
// SetDhcpServerEditable sets the dhcpServerEditable property value. The dhcpServerEditable property
func (m *SubnetTypesGetResponse_subnetTypes) SetDhcpServerEditable(value *bool)() {
    m.dhcpServerEditable = value
}
// SetId sets the id property value. The id property
func (m *SubnetTypesGetResponse_subnetTypes) SetId(value *int64)() {
    m.id = value
}
// SetName sets the name property value. The name property
func (m *SubnetTypesGetResponse_subnetTypes) SetName(value *string)() {
    m.name = value
}
// SetOptionTypes sets the optionTypes property value. The optionTypes property
func (m *SubnetTypesGetResponse_subnetTypes) SetOptionTypes(value []SubnetTypesGetResponse_subnetTypes_optionTypesable)() {
    m.optionTypes = value
}
type SubnetTypesGetResponse_subnetTypesable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCanAssignPool()(*bool)
    GetCode()(*string)
    GetCreatable()(*bool)
    GetDeletable()(*bool)
    GetDescription()(*string)
    GetDhcpServerEditable()(*bool)
    GetId()(*int64)
    GetName()(*string)
    GetOptionTypes()([]SubnetTypesGetResponse_subnetTypes_optionTypesable)
    SetCanAssignPool(value *bool)()
    SetCode(value *string)()
    SetCreatable(value *bool)()
    SetDeletable(value *bool)()
    SetDescription(value *string)()
    SetDhcpServerEditable(value *bool)()
    SetId(value *int64)()
    SetName(value *string)()
    SetOptionTypes(value []SubnetTypesGetResponse_subnetTypes_optionTypesable)()
}
