// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type TasksPostResponse_taskMember2_taskOptions struct {
    // The ansibleGroup property
    ansibleGroup *string
    // The ansibleTowerExecuteMode property
    ansibleTowerExecuteMode *string
    // The ansibleTowerGitRef property
    ansibleTowerGitRef *string
    // The host property
    host *string
    // The localScriptGitId property
    localScriptGitId *string
    // The localScriptGitRef property
    localScriptGitRef *string
    // The password property
    password *string
    // The passwordHash property
    passwordHash *string
    // The port property
    port *string
    // The sshKey property
    sshKey *string
    // The username property
    username *string
}
// NewTasksPostResponse_taskMember2_taskOptions instantiates a new TasksPostResponse_taskMember2_taskOptions and sets the default values.
func NewTasksPostResponse_taskMember2_taskOptions()(*TasksPostResponse_taskMember2_taskOptions) {
    m := &TasksPostResponse_taskMember2_taskOptions{
    }
    return m
}
// CreateTasksPostResponse_taskMember2_taskOptionsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateTasksPostResponse_taskMember2_taskOptionsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewTasksPostResponse_taskMember2_taskOptions(), nil
}
// GetAnsibleGroup gets the ansibleGroup property value. The ansibleGroup property
// returns a *string when successful
func (m *TasksPostResponse_taskMember2_taskOptions) GetAnsibleGroup()(*string) {
    return m.ansibleGroup
}
// GetAnsibleTowerExecuteMode gets the ansibleTowerExecuteMode property value. The ansibleTowerExecuteMode property
// returns a *string when successful
func (m *TasksPostResponse_taskMember2_taskOptions) GetAnsibleTowerExecuteMode()(*string) {
    return m.ansibleTowerExecuteMode
}
// GetAnsibleTowerGitRef gets the ansibleTowerGitRef property value. The ansibleTowerGitRef property
// returns a *string when successful
func (m *TasksPostResponse_taskMember2_taskOptions) GetAnsibleTowerGitRef()(*string) {
    return m.ansibleTowerGitRef
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *TasksPostResponse_taskMember2_taskOptions) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["ansibleGroup"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAnsibleGroup(val)
        }
        return nil
    }
    res["ansibleTowerExecuteMode"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAnsibleTowerExecuteMode(val)
        }
        return nil
    }
    res["ansibleTowerGitRef"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAnsibleTowerGitRef(val)
        }
        return nil
    }
    res["host"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHost(val)
        }
        return nil
    }
    res["localScriptGitId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLocalScriptGitId(val)
        }
        return nil
    }
    res["localScriptGitRef"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLocalScriptGitRef(val)
        }
        return nil
    }
    res["password"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPassword(val)
        }
        return nil
    }
    res["passwordHash"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPasswordHash(val)
        }
        return nil
    }
    res["port"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPort(val)
        }
        return nil
    }
    res["sshKey"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSshKey(val)
        }
        return nil
    }
    res["username"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUsername(val)
        }
        return nil
    }
    return res
}
// GetHost gets the host property value. The host property
// returns a *string when successful
func (m *TasksPostResponse_taskMember2_taskOptions) GetHost()(*string) {
    return m.host
}
// GetLocalScriptGitId gets the localScriptGitId property value. The localScriptGitId property
// returns a *string when successful
func (m *TasksPostResponse_taskMember2_taskOptions) GetLocalScriptGitId()(*string) {
    return m.localScriptGitId
}
// GetLocalScriptGitRef gets the localScriptGitRef property value. The localScriptGitRef property
// returns a *string when successful
func (m *TasksPostResponse_taskMember2_taskOptions) GetLocalScriptGitRef()(*string) {
    return m.localScriptGitRef
}
// GetPassword gets the password property value. The password property
// returns a *string when successful
func (m *TasksPostResponse_taskMember2_taskOptions) GetPassword()(*string) {
    return m.password
}
// GetPasswordHash gets the passwordHash property value. The passwordHash property
// returns a *string when successful
func (m *TasksPostResponse_taskMember2_taskOptions) GetPasswordHash()(*string) {
    return m.passwordHash
}
// GetPort gets the port property value. The port property
// returns a *string when successful
func (m *TasksPostResponse_taskMember2_taskOptions) GetPort()(*string) {
    return m.port
}
// GetSshKey gets the sshKey property value. The sshKey property
// returns a *string when successful
func (m *TasksPostResponse_taskMember2_taskOptions) GetSshKey()(*string) {
    return m.sshKey
}
// GetUsername gets the username property value. The username property
// returns a *string when successful
func (m *TasksPostResponse_taskMember2_taskOptions) GetUsername()(*string) {
    return m.username
}
// Serialize serializes information the current object
func (m *TasksPostResponse_taskMember2_taskOptions) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("ansibleGroup", m.GetAnsibleGroup())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("ansibleTowerExecuteMode", m.GetAnsibleTowerExecuteMode())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("ansibleTowerGitRef", m.GetAnsibleTowerGitRef())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("host", m.GetHost())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("localScriptGitId", m.GetLocalScriptGitId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("localScriptGitRef", m.GetLocalScriptGitRef())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("password", m.GetPassword())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("passwordHash", m.GetPasswordHash())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("port", m.GetPort())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("sshKey", m.GetSshKey())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("username", m.GetUsername())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAnsibleGroup sets the ansibleGroup property value. The ansibleGroup property
func (m *TasksPostResponse_taskMember2_taskOptions) SetAnsibleGroup(value *string)() {
    m.ansibleGroup = value
}
// SetAnsibleTowerExecuteMode sets the ansibleTowerExecuteMode property value. The ansibleTowerExecuteMode property
func (m *TasksPostResponse_taskMember2_taskOptions) SetAnsibleTowerExecuteMode(value *string)() {
    m.ansibleTowerExecuteMode = value
}
// SetAnsibleTowerGitRef sets the ansibleTowerGitRef property value. The ansibleTowerGitRef property
func (m *TasksPostResponse_taskMember2_taskOptions) SetAnsibleTowerGitRef(value *string)() {
    m.ansibleTowerGitRef = value
}
// SetHost sets the host property value. The host property
func (m *TasksPostResponse_taskMember2_taskOptions) SetHost(value *string)() {
    m.host = value
}
// SetLocalScriptGitId sets the localScriptGitId property value. The localScriptGitId property
func (m *TasksPostResponse_taskMember2_taskOptions) SetLocalScriptGitId(value *string)() {
    m.localScriptGitId = value
}
// SetLocalScriptGitRef sets the localScriptGitRef property value. The localScriptGitRef property
func (m *TasksPostResponse_taskMember2_taskOptions) SetLocalScriptGitRef(value *string)() {
    m.localScriptGitRef = value
}
// SetPassword sets the password property value. The password property
func (m *TasksPostResponse_taskMember2_taskOptions) SetPassword(value *string)() {
    m.password = value
}
// SetPasswordHash sets the passwordHash property value. The passwordHash property
func (m *TasksPostResponse_taskMember2_taskOptions) SetPasswordHash(value *string)() {
    m.passwordHash = value
}
// SetPort sets the port property value. The port property
func (m *TasksPostResponse_taskMember2_taskOptions) SetPort(value *string)() {
    m.port = value
}
// SetSshKey sets the sshKey property value. The sshKey property
func (m *TasksPostResponse_taskMember2_taskOptions) SetSshKey(value *string)() {
    m.sshKey = value
}
// SetUsername sets the username property value. The username property
func (m *TasksPostResponse_taskMember2_taskOptions) SetUsername(value *string)() {
    m.username = value
}
type TasksPostResponse_taskMember2_taskOptionsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAnsibleGroup()(*string)
    GetAnsibleTowerExecuteMode()(*string)
    GetAnsibleTowerGitRef()(*string)
    GetHost()(*string)
    GetLocalScriptGitId()(*string)
    GetLocalScriptGitRef()(*string)
    GetPassword()(*string)
    GetPasswordHash()(*string)
    GetPort()(*string)
    GetSshKey()(*string)
    GetUsername()(*string)
    SetAnsibleGroup(value *string)()
    SetAnsibleTowerExecuteMode(value *string)()
    SetAnsibleTowerGitRef(value *string)()
    SetHost(value *string)()
    SetLocalScriptGitId(value *string)()
    SetLocalScriptGitRef(value *string)()
    SetPassword(value *string)()
    SetPasswordHash(value *string)()
    SetPort(value *string)()
    SetSshKey(value *string)()
    SetUsername(value *string)()
}
