// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package emailtemplates
// A unique code for the email template. This code is used to reference the email template and as a reference of the templates type.
type EmailTemplatesPostResponse_emailTemplate_code int

const (
    INSTANCEEXPIRED_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE EmailTemplatesPostResponse_emailTemplate_code = iota
    INSTANCESHUTDOWN_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
    INSTANCENOTIFYEXPIRING_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
    NOTIFYSHUTDOWNWARNINGINSTANCE_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
    FORGOTPASSWORD_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
    INACTIVEWARNING_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
    WARNOLDPASSWORD_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
    CONFIRMPASSUPDATE_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
    USERACCOUNTCONFIRMEMAIL_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
    CONFIRMEMAIL_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
    REGISTERSUCCESS_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
    INSTANCECOMPLETE_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
    INSTANCESCALECOMPLETE_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
)

func (i EmailTemplatesPostResponse_emailTemplate_code) String() string {
    return []string{"instanceExpired", "instanceShutdown", "instanceNotifyExpiring", "notifyShutdownWarningInstance", "forgotPassword", "inactiveWarning", "warnOldPassword", "confirmPassUpdate", "userAccountConfirmEmail", "confirmEmail", "registerSuccess", "instanceComplete", "instanceScaleComplete"}[i]
}
func ParseEmailTemplatesPostResponse_emailTemplate_code(v string) (any, error) {
    result := INSTANCEEXPIRED_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
    switch v {
        case "instanceExpired":
            result = INSTANCEEXPIRED_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
        case "instanceShutdown":
            result = INSTANCESHUTDOWN_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
        case "instanceNotifyExpiring":
            result = INSTANCENOTIFYEXPIRING_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
        case "notifyShutdownWarningInstance":
            result = NOTIFYSHUTDOWNWARNINGINSTANCE_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
        case "forgotPassword":
            result = FORGOTPASSWORD_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
        case "inactiveWarning":
            result = INACTIVEWARNING_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
        case "warnOldPassword":
            result = WARNOLDPASSWORD_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
        case "confirmPassUpdate":
            result = CONFIRMPASSUPDATE_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
        case "userAccountConfirmEmail":
            result = USERACCOUNTCONFIRMEMAIL_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
        case "confirmEmail":
            result = CONFIRMEMAIL_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
        case "registerSuccess":
            result = REGISTERSUCCESS_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
        case "instanceComplete":
            result = INSTANCECOMPLETE_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
        case "instanceScaleComplete":
            result = INSTANCESCALECOMPLETE_EMAILTEMPLATESPOSTRESPONSE_EMAILTEMPLATE_CODE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeEmailTemplatesPostResponse_emailTemplate_code(values []EmailTemplatesPostResponse_emailTemplate_code) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i EmailTemplatesPostResponse_emailTemplate_code) isMultiValue() bool {
    return false
}
