// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package item
// The new access level.
type RolesPutRequestBody_role_permissions_access int

const (
    FULL_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS RolesPutRequestBody_role_permissions_access = iota
    FULL_DECRYPTED_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
    GROUP_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
    LISTFILES_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
    MANAGERULES_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
    NO_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
    NONE_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
    PROVISION_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
    READ_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
    ROLEMAPPINGS_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
    USER_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
    VIEW_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
    YES_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
)

func (i RolesPutRequestBody_role_permissions_access) String() string {
    return []string{"full", "full_decrypted", "group", "listfiles", "managerules", "no", "none", "provision", "read", "rolemappings", "user", "view", "yes"}[i]
}
func ParseRolesPutRequestBody_role_permissions_access(v string) (any, error) {
    result := FULL_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
    switch v {
        case "full":
            result = FULL_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
        case "full_decrypted":
            result = FULL_DECRYPTED_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
        case "group":
            result = GROUP_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
        case "listfiles":
            result = LISTFILES_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
        case "managerules":
            result = MANAGERULES_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
        case "no":
            result = NO_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
        case "none":
            result = NONE_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
        case "provision":
            result = PROVISION_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
        case "read":
            result = READ_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
        case "rolemappings":
            result = ROLEMAPPINGS_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
        case "user":
            result = USER_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
        case "view":
            result = VIEW_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
        case "yes":
            result = YES_ROLESPUTREQUESTBODY_ROLE_PERMISSIONS_ACCESS
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeRolesPutRequestBody_role_permissions_access(values []RolesPutRequestBody_role_permissions_access) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i RolesPutRequestBody_role_permissions_access) isMultiValue() bool {
    return false
}
