gitUserId: HewlettPackard
gitRepoId: hpe-morpheus-go-sdk
packageName: sdk

additionalProperties:
  goVersion: 1.24
  isGoSubmodule: true
  withGoMod: false

files:
  errors.mustache:
    templateType: SupportingFiles
    destinationFilename: errors.go
