/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the GetIntegrations200ResponseAllOfIntegrationOneOf3Config type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIntegrations200ResponseAllOfIntegrationOneOf3Config{}

// GetIntegrations200ResponseAllOfIntegrationOneOf3Config struct for GetIntegrations200ResponseAllOfIntegrationOneOf3Config
type GetIntegrations200ResponseAllOfIntegrationOneOf3Config struct {
	Databags             []GetIntegrations200ResponseAllOfIntegrationOneOf3ConfigDatabagsInner `json:"databags,omitempty"`
	Endpoint             *string                                                               `json:"endpoint,omitempty"`
	Org                  *string                                                               `json:"org,omitempty"`
	ChefUser             *string                                                               `json:"chefUser,omitempty"`
	UserKey              *string                                                               `json:"userKey,omitempty"`
	OrgKey               *string                                                               `json:"orgKey,omitempty"`
	Version              *string                                                               `json:"version,omitempty"`
	ChefUseFqdn          *bool                                                                 `json:"chefUseFqdn,omitempty"`
	WindowsVersion       *string                                                               `json:"windowsVersion,omitempty"`
	WindowsInstallUrl    *string                                                               `json:"windowsInstallUrl,omitempty"`
	UserKeyHash          *string                                                               `json:"userKeyHash,omitempty"`
	OrgKeyHash           *string                                                               `json:"orgKeyHash,omitempty"`
	AdditionalProperties map[string]interface{}                                                `json:",remain"`
}

type _GetIntegrations200ResponseAllOfIntegrationOneOf3Config GetIntegrations200ResponseAllOfIntegrationOneOf3Config

// NewGetIntegrations200ResponseAllOfIntegrationOneOf3Config instantiates a new GetIntegrations200ResponseAllOfIntegrationOneOf3Config object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIntegrations200ResponseAllOfIntegrationOneOf3Config() *GetIntegrations200ResponseAllOfIntegrationOneOf3Config {
	this := GetIntegrations200ResponseAllOfIntegrationOneOf3Config{}
	return &this
}

// NewGetIntegrations200ResponseAllOfIntegrationOneOf3ConfigWithDefaults instantiates a new GetIntegrations200ResponseAllOfIntegrationOneOf3Config object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIntegrations200ResponseAllOfIntegrationOneOf3ConfigWithDefaults() *GetIntegrations200ResponseAllOfIntegrationOneOf3Config {
	this := GetIntegrations200ResponseAllOfIntegrationOneOf3Config{}
	return &this
}

// GetDatabags returns the Databags field value if set, zero value otherwise.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetDatabags() []GetIntegrations200ResponseAllOfIntegrationOneOf3ConfigDatabagsInner {
	if o == nil || IsNil(o.Databags) {
		var ret []GetIntegrations200ResponseAllOfIntegrationOneOf3ConfigDatabagsInner
		return ret
	}
	return o.Databags
}

// GetDatabagsOk returns a tuple with the Databags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetDatabagsOk() ([]GetIntegrations200ResponseAllOfIntegrationOneOf3ConfigDatabagsInner, bool) {
	if o == nil || IsNil(o.Databags) {
		return nil, false
	}
	return o.Databags, true
}

// SetDatabags gets a reference to the given []GetIntegrations200ResponseAllOfIntegrationOneOf3ConfigDatabagsInner and assigns it to the Databags field.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) SetDatabags(v []GetIntegrations200ResponseAllOfIntegrationOneOf3ConfigDatabagsInner) {
	o.Databags = v
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint) {
		var ret string
		return ret
	}
	return *o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.Endpoint) {
		return nil, false
	}
	return o.Endpoint, true
}

// SetEndpoint gets a reference to the given string and assigns it to the Endpoint field.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) SetEndpoint(v string) {
	o.Endpoint = &v
}

// GetOrg returns the Org field value if set, zero value otherwise.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetOrg() string {
	if o == nil || IsNil(o.Org) {
		var ret string
		return ret
	}
	return *o.Org
}

// GetOrgOk returns a tuple with the Org field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetOrgOk() (*string, bool) {
	if o == nil || IsNil(o.Org) {
		return nil, false
	}
	return o.Org, true
}

// SetOrg gets a reference to the given string and assigns it to the Org field.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) SetOrg(v string) {
	o.Org = &v
}

// GetChefUser returns the ChefUser field value if set, zero value otherwise.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetChefUser() string {
	if o == nil || IsNil(o.ChefUser) {
		var ret string
		return ret
	}
	return *o.ChefUser
}

// GetChefUserOk returns a tuple with the ChefUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetChefUserOk() (*string, bool) {
	if o == nil || IsNil(o.ChefUser) {
		return nil, false
	}
	return o.ChefUser, true
}

// SetChefUser gets a reference to the given string and assigns it to the ChefUser field.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) SetChefUser(v string) {
	o.ChefUser = &v
}

// GetUserKey returns the UserKey field value if set, zero value otherwise.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetUserKey() string {
	if o == nil || IsNil(o.UserKey) {
		var ret string
		return ret
	}
	return *o.UserKey
}

// GetUserKeyOk returns a tuple with the UserKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetUserKeyOk() (*string, bool) {
	if o == nil || IsNil(o.UserKey) {
		return nil, false
	}
	return o.UserKey, true
}

// SetUserKey gets a reference to the given string and assigns it to the UserKey field.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) SetUserKey(v string) {
	o.UserKey = &v
}

// GetOrgKey returns the OrgKey field value if set, zero value otherwise.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetOrgKey() string {
	if o == nil || IsNil(o.OrgKey) {
		var ret string
		return ret
	}
	return *o.OrgKey
}

// GetOrgKeyOk returns a tuple with the OrgKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetOrgKeyOk() (*string, bool) {
	if o == nil || IsNil(o.OrgKey) {
		return nil, false
	}
	return o.OrgKey, true
}

// SetOrgKey gets a reference to the given string and assigns it to the OrgKey field.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) SetOrgKey(v string) {
	o.OrgKey = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) SetVersion(v string) {
	o.Version = &v
}

// GetChefUseFqdn returns the ChefUseFqdn field value if set, zero value otherwise.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetChefUseFqdn() bool {
	if o == nil || IsNil(o.ChefUseFqdn) {
		var ret bool
		return ret
	}
	return *o.ChefUseFqdn
}

// GetChefUseFqdnOk returns a tuple with the ChefUseFqdn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetChefUseFqdnOk() (*bool, bool) {
	if o == nil || IsNil(o.ChefUseFqdn) {
		return nil, false
	}
	return o.ChefUseFqdn, true
}

// SetChefUseFqdn gets a reference to the given bool and assigns it to the ChefUseFqdn field.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) SetChefUseFqdn(v bool) {
	o.ChefUseFqdn = &v
}

// GetWindowsVersion returns the WindowsVersion field value if set, zero value otherwise.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetWindowsVersion() string {
	if o == nil || IsNil(o.WindowsVersion) {
		var ret string
		return ret
	}
	return *o.WindowsVersion
}

// GetWindowsVersionOk returns a tuple with the WindowsVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetWindowsVersionOk() (*string, bool) {
	if o == nil || IsNil(o.WindowsVersion) {
		return nil, false
	}
	return o.WindowsVersion, true
}

// SetWindowsVersion gets a reference to the given string and assigns it to the WindowsVersion field.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) SetWindowsVersion(v string) {
	o.WindowsVersion = &v
}

// GetWindowsInstallUrl returns the WindowsInstallUrl field value if set, zero value otherwise.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetWindowsInstallUrl() string {
	if o == nil || IsNil(o.WindowsInstallUrl) {
		var ret string
		return ret
	}
	return *o.WindowsInstallUrl
}

// GetWindowsInstallUrlOk returns a tuple with the WindowsInstallUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetWindowsInstallUrlOk() (*string, bool) {
	if o == nil || IsNil(o.WindowsInstallUrl) {
		return nil, false
	}
	return o.WindowsInstallUrl, true
}

// SetWindowsInstallUrl gets a reference to the given string and assigns it to the WindowsInstallUrl field.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) SetWindowsInstallUrl(v string) {
	o.WindowsInstallUrl = &v
}

// GetUserKeyHash returns the UserKeyHash field value if set, zero value otherwise.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetUserKeyHash() string {
	if o == nil || IsNil(o.UserKeyHash) {
		var ret string
		return ret
	}
	return *o.UserKeyHash
}

// GetUserKeyHashOk returns a tuple with the UserKeyHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetUserKeyHashOk() (*string, bool) {
	if o == nil || IsNil(o.UserKeyHash) {
		return nil, false
	}
	return o.UserKeyHash, true
}

// SetUserKeyHash gets a reference to the given string and assigns it to the UserKeyHash field.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) SetUserKeyHash(v string) {
	o.UserKeyHash = &v
}

// GetOrgKeyHash returns the OrgKeyHash field value if set, zero value otherwise.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetOrgKeyHash() string {
	if o == nil || IsNil(o.OrgKeyHash) {
		var ret string
		return ret
	}
	return *o.OrgKeyHash
}

// GetOrgKeyHashOk returns a tuple with the OrgKeyHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) GetOrgKeyHashOk() (*string, bool) {
	if o == nil || IsNil(o.OrgKeyHash) {
		return nil, false
	}
	return o.OrgKeyHash, true
}

// SetOrgKeyHash gets a reference to the given string and assigns it to the OrgKeyHash field.
func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) SetOrgKeyHash(v string) {
	o.OrgKeyHash = &v
}

func (o GetIntegrations200ResponseAllOfIntegrationOneOf3Config) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIntegrations200ResponseAllOfIntegrationOneOf3Config) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Databags) {
		toSerialize["databags"] = o.Databags
	}
	if !IsNil(o.Endpoint) {
		toSerialize["endpoint"] = o.Endpoint
	}
	if !IsNil(o.Org) {
		toSerialize["org"] = o.Org
	}
	if !IsNil(o.ChefUser) {
		toSerialize["chefUser"] = o.ChefUser
	}
	if !IsNil(o.UserKey) {
		toSerialize["userKey"] = o.UserKey
	}
	if !IsNil(o.OrgKey) {
		toSerialize["orgKey"] = o.OrgKey
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.ChefUseFqdn) {
		toSerialize["chefUseFqdn"] = o.ChefUseFqdn
	}
	if !IsNil(o.WindowsVersion) {
		toSerialize["windowsVersion"] = o.WindowsVersion
	}
	if !IsNil(o.WindowsInstallUrl) {
		toSerialize["windowsInstallUrl"] = o.WindowsInstallUrl
	}
	if !IsNil(o.UserKeyHash) {
		toSerialize["userKeyHash"] = o.UserKeyHash
	}
	if !IsNil(o.OrgKeyHash) {
		toSerialize["orgKeyHash"] = o.OrgKeyHash
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableGetIntegrations200ResponseAllOfIntegrationOneOf3Config struct {
	value *GetIntegrations200ResponseAllOfIntegrationOneOf3Config
	isSet bool
}

func (v NullableGetIntegrations200ResponseAllOfIntegrationOneOf3Config) Get() *GetIntegrations200ResponseAllOfIntegrationOneOf3Config {
	return v.value
}

func (v *NullableGetIntegrations200ResponseAllOfIntegrationOneOf3Config) Set(val *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIntegrations200ResponseAllOfIntegrationOneOf3Config) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIntegrations200ResponseAllOfIntegrationOneOf3Config) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIntegrations200ResponseAllOfIntegrationOneOf3Config(val *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) *NullableGetIntegrations200ResponseAllOfIntegrationOneOf3Config {
	return &NullableGetIntegrations200ResponseAllOfIntegrationOneOf3Config{value: val, isSet: true}
}

func (v NullableGetIntegrations200ResponseAllOfIntegrationOneOf3Config) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIntegrations200ResponseAllOfIntegrationOneOf3Config) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableGetIntegrations200ResponseAllOfIntegrationOneOf3Config) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *GetIntegrations200ResponseAllOfIntegrationOneOf3Config) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
