/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the GetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType{}

// GetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType struct for GetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType
type GetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType struct {
	Id                        *int64                 `json:"id,omitempty"`
	Name                      *string                `json:"name,omitempty"`
	Code                      *string                `json:"code,omitempty"`
	RootDiskCustomizable      *bool                  `json:"rootDiskCustomizable,omitempty"`
	AddVolumes                *bool                  `json:"addVolumes,omitempty"`
	CustomizeVolume           *bool                  `json:"customizeVolume,omitempty"`
	HasConfigurableCpuSockets *bool                  `json:"hasConfigurableCpuSockets,omitempty"`
	AdditionalProperties      map[string]interface{} `json:",remain"`
}

type _GetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType GetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType

// NewGetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionTypeWithDefaults instantiates a new GetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionTypeWithDefaults() *GetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType {
	this := GetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType{}
	return &this
}

func (o GetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.RootDiskCustomizable) {
		toSerialize["rootDiskCustomizable"] = o.RootDiskCustomizable
	}
	if !IsNil(o.AddVolumes) {
		toSerialize["addVolumes"] = o.AddVolumes
	}
	if !IsNil(o.CustomizeVolume) {
		toSerialize["customizeVolume"] = o.CustomizeVolume
	}
	if !IsNil(o.HasConfigurableCpuSockets) {
		toSerialize["hasConfigurableCpuSockets"] = o.HasConfigurableCpuSockets
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableGetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType struct {
	value *GetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType
	isSet bool
}

func (v NullableGetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType) Get() *GetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType {
	return v.value
}

func (v *NullableGetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType) Set(val *GetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType) {
	v.value = val
	v.isSet = true
}

func (v NullableGetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType) IsSet() bool {
	return v.isSet
}

func (v *NullableGetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType(val *GetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType) *NullableGetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType {
	return &NullableGetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType{value: val, isSet: true}
}

func (v NullableGetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableGetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *GetGuidances200ResponseDiscoveryAnyOfPlanBeforeActionProvisionType) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
