/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the GuidanceAzureReservationsConfigSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuidanceAzureReservationsConfigSummary{}

// GuidanceAzureReservationsConfigSummary struct for GuidanceAzureReservationsConfigSummary
type GuidanceAzureReservationsConfigSummary struct {
	TotalSavings         *float32               `json:"totalSavings,omitempty"`
	CurrencyCode         *string                `json:"currencyCode,omitempty"`
	TotalSavingsPercent  *float32               `json:"totalSavingsPercent,omitempty"`
	Term                 *string                `json:"term,omitempty"`
	PaymentOption        *string                `json:"paymentOption,omitempty"`
	Service              *string                `json:"service,omitempty"`
	OnDemandCount        *int64                 `json:"onDemandCount,omitempty"`
	OnDemandCost         *float32               `json:"onDemandCost,omitempty"`
	ReservedCount        *int64                 `json:"reservedCount,omitempty"`
	ReservedCost         *int64                 `json:"reservedCost,omitempty"`
	RecommendedCount     *int64                 `json:"recommendedCount,omitempty"`
	RecommendedCost      *float32               `json:"recommendedCost,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _GuidanceAzureReservationsConfigSummary GuidanceAzureReservationsConfigSummary

// NewGuidanceAzureReservationsConfigSummaryWithDefaults instantiates a new GuidanceAzureReservationsConfigSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuidanceAzureReservationsConfigSummaryWithDefaults() *GuidanceAzureReservationsConfigSummary {
	this := GuidanceAzureReservationsConfigSummary{}
	return &this
}

func (o GuidanceAzureReservationsConfigSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuidanceAzureReservationsConfigSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalSavings) {
		toSerialize["totalSavings"] = o.TotalSavings
	}
	if !IsNil(o.CurrencyCode) {
		toSerialize["currencyCode"] = o.CurrencyCode
	}
	if !IsNil(o.TotalSavingsPercent) {
		toSerialize["totalSavingsPercent"] = o.TotalSavingsPercent
	}
	if !IsNil(o.Term) {
		toSerialize["term"] = o.Term
	}
	if !IsNil(o.PaymentOption) {
		toSerialize["paymentOption"] = o.PaymentOption
	}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !IsNil(o.OnDemandCount) {
		toSerialize["onDemandCount"] = o.OnDemandCount
	}
	if !IsNil(o.OnDemandCost) {
		toSerialize["onDemandCost"] = o.OnDemandCost
	}
	if !IsNil(o.ReservedCount) {
		toSerialize["reservedCount"] = o.ReservedCount
	}
	if !IsNil(o.ReservedCost) {
		toSerialize["reservedCost"] = o.ReservedCost
	}
	if !IsNil(o.RecommendedCount) {
		toSerialize["recommendedCount"] = o.RecommendedCount
	}
	if !IsNil(o.RecommendedCost) {
		toSerialize["recommendedCost"] = o.RecommendedCost
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableGuidanceAzureReservationsConfigSummary struct {
	value *GuidanceAzureReservationsConfigSummary
	isSet bool
}

func (v NullableGuidanceAzureReservationsConfigSummary) Get() *GuidanceAzureReservationsConfigSummary {
	return v.value
}

func (v *NullableGuidanceAzureReservationsConfigSummary) Set(val *GuidanceAzureReservationsConfigSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableGuidanceAzureReservationsConfigSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableGuidanceAzureReservationsConfigSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuidanceAzureReservationsConfigSummary(val *GuidanceAzureReservationsConfigSummary) *NullableGuidanceAzureReservationsConfigSummary {
	return &NullableGuidanceAzureReservationsConfigSummary{value: val, isSet: true}
}

func (v NullableGuidanceAzureReservationsConfigSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuidanceAzureReservationsConfigSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableGuidanceAzureReservationsConfigSummary) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *GuidanceAzureReservationsConfigSummary) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
