/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"time"
)

// checks if the ListDeploys200ResponseAllOfAppDeploysInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDeploys200ResponseAllOfAppDeploysInner{}

// ListDeploys200ResponseAllOfAppDeploysInner struct for ListDeploys200ResponseAllOfAppDeploysInner
type ListDeploys200ResponseAllOfAppDeploysInner struct {
	Id                   *int64                                                       `json:"id,omitempty"`
	InstanceId           *int64                                                       `json:"instanceId,omitempty"`
	Instance             NullableListDeploys200ResponseAllOfAppDeploysInnerInstance   `json:"instance,omitempty"`
	Deployment           *ListDeploys200ResponseAllOfAppDeploysInnerDeployment        `json:"deployment,omitempty"`
	DeploymentVersionId  *int64                                                       `json:"deploymentVersionId,omitempty"`
	DeploymentVersion    *ListDeploys200ResponseAllOfAppDeploysInnerDeploymentVersion `json:"deploymentVersion,omitempty"`
	Config               map[string]interface{}                                       `json:"config,omitempty"`
	Status               *string                                                      `json:"status,omitempty"`
	DeployDate           *time.Time                                                   `json:"deployDate,omitempty"`
	DateCreated          *time.Time                                                   `json:"dateCreated,omitempty"`
	LastUpdated          *time.Time                                                   `json:"lastUpdated,omitempty"`
	AdditionalProperties map[string]interface{}                                       `json:",remain"`
}

type _ListDeploys200ResponseAllOfAppDeploysInner ListDeploys200ResponseAllOfAppDeploysInner

// NewListDeploys200ResponseAllOfAppDeploysInnerWithDefaults instantiates a new ListDeploys200ResponseAllOfAppDeploysInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDeploys200ResponseAllOfAppDeploysInnerWithDefaults() *ListDeploys200ResponseAllOfAppDeploysInner {
	this := ListDeploys200ResponseAllOfAppDeploysInner{}
	return &this
}

func (o ListDeploys200ResponseAllOfAppDeploysInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDeploys200ResponseAllOfAppDeploysInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.InstanceId) {
		toSerialize["instanceId"] = o.InstanceId
	}
	if o.Instance.IsSet() {
		toSerialize["instance"] = o.Instance.Get()
	}
	if !IsNil(o.Deployment) {
		toSerialize["deployment"] = o.Deployment
	}
	if !IsNil(o.DeploymentVersionId) {
		toSerialize["deploymentVersionId"] = o.DeploymentVersionId
	}
	if !IsNil(o.DeploymentVersion) {
		toSerialize["deploymentVersion"] = o.DeploymentVersion
	}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.DeployDate) {
		toSerialize["deployDate"] = o.DeployDate
	}
	if !IsNil(o.DateCreated) {
		toSerialize["dateCreated"] = o.DateCreated
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["lastUpdated"] = o.LastUpdated
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableListDeploys200ResponseAllOfAppDeploysInner struct {
	value *ListDeploys200ResponseAllOfAppDeploysInner
	isSet bool
}

func (v NullableListDeploys200ResponseAllOfAppDeploysInner) Get() *ListDeploys200ResponseAllOfAppDeploysInner {
	return v.value
}

func (v *NullableListDeploys200ResponseAllOfAppDeploysInner) Set(val *ListDeploys200ResponseAllOfAppDeploysInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListDeploys200ResponseAllOfAppDeploysInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListDeploys200ResponseAllOfAppDeploysInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDeploys200ResponseAllOfAppDeploysInner(val *ListDeploys200ResponseAllOfAppDeploysInner) *NullableListDeploys200ResponseAllOfAppDeploysInner {
	return &NullableListDeploys200ResponseAllOfAppDeploysInner{value: val, isSet: true}
}

func (v NullableListDeploys200ResponseAllOfAppDeploysInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDeploys200ResponseAllOfAppDeploysInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableListDeploys200ResponseAllOfAppDeploysInner) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *ListDeploys200ResponseAllOfAppDeploysInner) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
