/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the ListClusterWorkers200ResponseAllOfWorkersInnerStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListClusterWorkers200ResponseAllOfWorkersInnerStats{}

// ListClusterWorkers200ResponseAllOfWorkersInnerStats struct for ListClusterWorkers200ResponseAllOfWorkersInnerStats
type ListClusterWorkers200ResponseAllOfWorkersInnerStats struct {
	UsedStorage          *int64                 `json:"usedStorage,omitempty"`
	ReservedStorage      *int64                 `json:"reservedStorage,omitempty"`
	MaxStorage           *int64                 `json:"maxStorage,omitempty"`
	UsedMemory           *int64                 `json:"usedMemory,omitempty"`
	ReservedMemory       *int64                 `json:"reservedMemory,omitempty"`
	MaxMemory            *int64                 `json:"maxMemory,omitempty"`
	CpuUsage             *float32               `json:"cpuUsage,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _ListClusterWorkers200ResponseAllOfWorkersInnerStats ListClusterWorkers200ResponseAllOfWorkersInnerStats

func (o ListClusterWorkers200ResponseAllOfWorkersInnerStats) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListClusterWorkers200ResponseAllOfWorkersInnerStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UsedStorage) {
		toSerialize["usedStorage"] = o.UsedStorage
	}
	if !IsNil(o.ReservedStorage) {
		toSerialize["reservedStorage"] = o.ReservedStorage
	}
	if !IsNil(o.MaxStorage) {
		toSerialize["maxStorage"] = o.MaxStorage
	}
	if !IsNil(o.UsedMemory) {
		toSerialize["usedMemory"] = o.UsedMemory
	}
	if !IsNil(o.ReservedMemory) {
		toSerialize["reservedMemory"] = o.ReservedMemory
	}
	if !IsNil(o.MaxMemory) {
		toSerialize["maxMemory"] = o.MaxMemory
	}
	if !IsNil(o.CpuUsage) {
		toSerialize["cpuUsage"] = o.CpuUsage
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableListClusterWorkers200ResponseAllOfWorkersInnerStats struct {
	value *ListClusterWorkers200ResponseAllOfWorkersInnerStats
	isSet bool
}

func (v NullableListClusterWorkers200ResponseAllOfWorkersInnerStats) Get() *ListClusterWorkers200ResponseAllOfWorkersInnerStats {
	return v.value
}

func (v *NullableListClusterWorkers200ResponseAllOfWorkersInnerStats) Set(val *ListClusterWorkers200ResponseAllOfWorkersInnerStats) {
	v.value = val
	v.isSet = true
}

func (v NullableListClusterWorkers200ResponseAllOfWorkersInnerStats) IsSet() bool {
	return v.isSet
}

func (v *NullableListClusterWorkers200ResponseAllOfWorkersInnerStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListClusterWorkers200ResponseAllOfWorkersInnerStats(val *ListClusterWorkers200ResponseAllOfWorkersInnerStats) *NullableListClusterWorkers200ResponseAllOfWorkersInnerStats {
	return &NullableListClusterWorkers200ResponseAllOfWorkersInnerStats{value: val, isSet: true}
}

func (v NullableListClusterWorkers200ResponseAllOfWorkersInnerStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListClusterWorkers200ResponseAllOfWorkersInnerStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableListClusterWorkers200ResponseAllOfWorkersInnerStats) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *ListClusterWorkers200ResponseAllOfWorkersInnerStats) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
