/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner{}

// GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner struct for GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner
type GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner struct {
	Id                   *int32                                                            `json:"id,omitempty"`
	Name                 *string                                                           `json:"name,omitempty"`
	Type                 *string                                                           `json:"type,omitempty"`
	ExternalId           *string                                                           `json:"externalId,omitempty"`
	Path                 *string                                                           `json:"path,omitempty"`
	ExportPath           *string                                                           `json:"exportPath,omitempty"`
	Volume               *GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInnerVolume `json:"volume,omitempty"`
	DiskIndex            *int32                                                            `json:"diskIndex,omitempty"`
	AdditionalProperties map[string]interface{}                                            `json:",remain"`
}

type _GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner

// NewGetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInnerWithDefaults instantiates a new GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInnerWithDefaults() *GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner {
	this := GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner{}
	return &this
}

func (o GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.ExternalId) {
		toSerialize["externalId"] = o.ExternalId
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.ExportPath) {
		toSerialize["exportPath"] = o.ExportPath
	}
	if !IsNil(o.Volume) {
		toSerialize["volume"] = o.Volume
	}
	if !IsNil(o.DiskIndex) {
		toSerialize["diskIndex"] = o.DiskIndex
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableGetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner struct {
	value *GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner
	isSet bool
}

func (v NullableGetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner) Get() *GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner {
	return v.value
}

func (v *NullableGetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner) Set(val *GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner(val *GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner) *NullableGetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner {
	return &NullableGetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner{value: val, isSet: true}
}

func (v NullableGetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableGetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *GetHostSnpshots200ResponseSnapshotsInnerSnapshotFilesInner) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
