/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"time"
)

// checks if the AddVDIPools200ResponseAnyOfVdiPool type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddVDIPools200ResponseAnyOfVdiPool{}

// AddVDIPools200ResponseAnyOfVdiPool struct for AddVDIPools200ResponseAnyOfVdiPool
type AddVDIPools200ResponseAnyOfVdiPool struct {
	Id                               *int64                                        `json:"id,omitempty"`
	Name                             *string                                       `json:"name,omitempty"`
	Description                      NullableString                                `json:"description,omitempty"`
	MinIdle                          *int64                                        `json:"minIdle,omitempty"`
	MaxIdle                          *int64                                        `json:"maxIdle,omitempty"`
	InitialPoolSize                  *int64                                        `json:"initialPoolSize,omitempty"`
	MaxPoolSize                      *int64                                        `json:"maxPoolSize,omitempty"`
	AllocationTimeoutMinutes         *int64                                        `json:"allocationTimeoutMinutes,omitempty"`
	PersistentUser                   NullableBool                                  `json:"persistentUser,omitempty"`
	Recyclable                       NullableBool                                  `json:"recyclable,omitempty"`
	Enabled                          *bool                                         `json:"enabled,omitempty"`
	AutoCreateLocalUserOnReservation *bool                                         `json:"autoCreateLocalUserOnReservation,omitempty"`
	AllowHypervisorConsole           NullableBool                                  `json:"allowHypervisorConsole,omitempty"`
	AllowCopy                        NullableBool                                  `json:"allowCopy,omitempty"`
	AllowPrinter                     NullableBool                                  `json:"allowPrinter,omitempty"`
	AllowFileshare                   NullableBool                                  `json:"allowFileshare,omitempty"`
	GuestConsoleJumpHost             NullableString                                `json:"guestConsoleJumpHost,omitempty"`
	GuestConsoleJumpPort             NullableString                                `json:"guestConsoleJumpPort,omitempty"`
	GuestConsoleJumpUsername         NullableString                                `json:"guestConsoleJumpUsername,omitempty"`
	GuestConsoleJumpPassword         NullableString                                `json:"guestConsoleJumpPassword,omitempty"`
	GuestConsoleJumpKeypair          NullableString                                `json:"guestConsoleJumpKeypair,omitempty"`
	Gateway                          *AddVDIPools200ResponseAnyOfVdiPoolGateway    `json:"gateway,omitempty"`
	IconPath                         *string                                       `json:"iconPath,omitempty"`
	Logo                             *string                                       `json:"logo,omitempty"`
	Apps                             []AddVDIPools200ResponseAnyOfVdiPoolAppsInner `json:"apps,omitempty"`
	Owner                            *AddVDIPools200ResponseAnyOfVdiPoolOwner      `json:"owner,omitempty"`
	Config                           *AddVDIPools200ResponseAnyOfVdiPoolConfig     `json:"config,omitempty"`
	Group                            *AddVDIPools200ResponseAnyOfVdiPoolGroup      `json:"group,omitempty"`
	Cloud                            *AddVDIPools200ResponseAnyOfVdiPoolCloud      `json:"cloud,omitempty"`
	UsedCount                        *int64                                        `json:"usedCount,omitempty"`
	ReservedCount                    *int64                                        `json:"reservedCount,omitempty"`
	PreparingCount                   *int64                                        `json:"preparingCount,omitempty"`
	IdleCount                        *int64                                        `json:"idleCount,omitempty"`
	Status                           *string                                       `json:"status,omitempty"`
	DateCreated                      *time.Time                                    `json:"dateCreated,omitempty"`
	LastUpdated                      *time.Time                                    `json:"lastUpdated,omitempty"`
	AdditionalProperties             map[string]interface{}                        `json:",remain"`
}

type _AddVDIPools200ResponseAnyOfVdiPool AddVDIPools200ResponseAnyOfVdiPool

// NewAddVDIPools200ResponseAnyOfVdiPoolWithDefaults instantiates a new AddVDIPools200ResponseAnyOfVdiPool object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddVDIPools200ResponseAnyOfVdiPoolWithDefaults() *AddVDIPools200ResponseAnyOfVdiPool {
	this := AddVDIPools200ResponseAnyOfVdiPool{}
	return &this
}

func (o AddVDIPools200ResponseAnyOfVdiPool) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddVDIPools200ResponseAnyOfVdiPool) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.MinIdle) {
		toSerialize["minIdle"] = o.MinIdle
	}
	if !IsNil(o.MaxIdle) {
		toSerialize["maxIdle"] = o.MaxIdle
	}
	if !IsNil(o.InitialPoolSize) {
		toSerialize["initialPoolSize"] = o.InitialPoolSize
	}
	if !IsNil(o.MaxPoolSize) {
		toSerialize["maxPoolSize"] = o.MaxPoolSize
	}
	if !IsNil(o.AllocationTimeoutMinutes) {
		toSerialize["allocationTimeoutMinutes"] = o.AllocationTimeoutMinutes
	}
	if o.PersistentUser.IsSet() {
		toSerialize["persistentUser"] = o.PersistentUser.Get()
	}
	if o.Recyclable.IsSet() {
		toSerialize["recyclable"] = o.Recyclable.Get()
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.AutoCreateLocalUserOnReservation) {
		toSerialize["autoCreateLocalUserOnReservation"] = o.AutoCreateLocalUserOnReservation
	}
	if o.AllowHypervisorConsole.IsSet() {
		toSerialize["allowHypervisorConsole"] = o.AllowHypervisorConsole.Get()
	}
	if o.AllowCopy.IsSet() {
		toSerialize["allowCopy"] = o.AllowCopy.Get()
	}
	if o.AllowPrinter.IsSet() {
		toSerialize["allowPrinter"] = o.AllowPrinter.Get()
	}
	if o.AllowFileshare.IsSet() {
		toSerialize["allowFileshare"] = o.AllowFileshare.Get()
	}
	if o.GuestConsoleJumpHost.IsSet() {
		toSerialize["guestConsoleJumpHost"] = o.GuestConsoleJumpHost.Get()
	}
	if o.GuestConsoleJumpPort.IsSet() {
		toSerialize["guestConsoleJumpPort"] = o.GuestConsoleJumpPort.Get()
	}
	if o.GuestConsoleJumpUsername.IsSet() {
		toSerialize["guestConsoleJumpUsername"] = o.GuestConsoleJumpUsername.Get()
	}
	if o.GuestConsoleJumpPassword.IsSet() {
		toSerialize["guestConsoleJumpPassword"] = o.GuestConsoleJumpPassword.Get()
	}
	if o.GuestConsoleJumpKeypair.IsSet() {
		toSerialize["guestConsoleJumpKeypair"] = o.GuestConsoleJumpKeypair.Get()
	}
	if !IsNil(o.Gateway) {
		toSerialize["gateway"] = o.Gateway
	}
	if !IsNil(o.IconPath) {
		toSerialize["iconPath"] = o.IconPath
	}
	if !IsNil(o.Logo) {
		toSerialize["logo"] = o.Logo
	}
	if !IsNil(o.Apps) {
		toSerialize["apps"] = o.Apps
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	if !IsNil(o.Cloud) {
		toSerialize["cloud"] = o.Cloud
	}
	if !IsNil(o.UsedCount) {
		toSerialize["usedCount"] = o.UsedCount
	}
	if !IsNil(o.ReservedCount) {
		toSerialize["reservedCount"] = o.ReservedCount
	}
	if !IsNil(o.PreparingCount) {
		toSerialize["preparingCount"] = o.PreparingCount
	}
	if !IsNil(o.IdleCount) {
		toSerialize["idleCount"] = o.IdleCount
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.DateCreated) {
		toSerialize["dateCreated"] = o.DateCreated
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["lastUpdated"] = o.LastUpdated
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableAddVDIPools200ResponseAnyOfVdiPool struct {
	value *AddVDIPools200ResponseAnyOfVdiPool
	isSet bool
}

func (v NullableAddVDIPools200ResponseAnyOfVdiPool) Get() *AddVDIPools200ResponseAnyOfVdiPool {
	return v.value
}

func (v *NullableAddVDIPools200ResponseAnyOfVdiPool) Set(val *AddVDIPools200ResponseAnyOfVdiPool) {
	v.value = val
	v.isSet = true
}

func (v NullableAddVDIPools200ResponseAnyOfVdiPool) IsSet() bool {
	return v.isSet
}

func (v *NullableAddVDIPools200ResponseAnyOfVdiPool) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddVDIPools200ResponseAnyOfVdiPool(val *AddVDIPools200ResponseAnyOfVdiPool) *NullableAddVDIPools200ResponseAnyOfVdiPool {
	return &NullableAddVDIPools200ResponseAnyOfVdiPool{value: val, isSet: true}
}

func (v NullableAddVDIPools200ResponseAnyOfVdiPool) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddVDIPools200ResponseAnyOfVdiPool) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableAddVDIPools200ResponseAnyOfVdiPool) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *AddVDIPools200ResponseAnyOfVdiPool) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
