/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the AddProvisioningLicenseRequestLicense type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddProvisioningLicenseRequestLicense{}

// AddProvisioningLicenseRequestLicense struct for AddProvisioningLicenseRequestLicense
type AddProvisioningLicenseRequestLicense struct {
	// Name
	Name string `json:"name"`
	// License Type - The license type code.
	LicenseType string `json:"licenseType"`
	// License Key - The license key, to be kept a secret.
	LicenseKey string `json:"licenseKey"`
	// Org Name - The Organization Name (if applicable) related to the license key
	OrgName *string `json:"orgName,omitempty"`
	// Full Name - The Full Name (if applicable) related to the license key
	FullName *string `json:"fullName,omitempty"`
	// License Version
	LicenseVersion *string `json:"licenseVersion,omitempty"`
	// Copies - The number of times the key can be used.
	Copies *int64 `json:"copies,omitempty"`
	// Description
	Description *string `json:"description,omitempty"`
	// Virtual Images - Array of Virtual Image IDs to associate with license.
	VirtualImages []int64 `json:"virtualImages,omitempty"`
	// Tenants - Array of tenants that are allowed to use the key.
	Tenants              []int64                `json:"tenants,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _AddProvisioningLicenseRequestLicense AddProvisioningLicenseRequestLicense

func (o AddProvisioningLicenseRequestLicense) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddProvisioningLicenseRequestLicense) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["licenseType"] = o.LicenseType
	toSerialize["licenseKey"] = o.LicenseKey
	if !IsNil(o.OrgName) {
		toSerialize["orgName"] = o.OrgName
	}
	if !IsNil(o.FullName) {
		toSerialize["fullName"] = o.FullName
	}
	if !IsNil(o.LicenseVersion) {
		toSerialize["licenseVersion"] = o.LicenseVersion
	}
	if !IsNil(o.Copies) {
		toSerialize["copies"] = o.Copies
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.VirtualImages) {
		toSerialize["virtualImages"] = o.VirtualImages
	}
	if !IsNil(o.Tenants) {
		toSerialize["tenants"] = o.Tenants
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableAddProvisioningLicenseRequestLicense struct {
	value *AddProvisioningLicenseRequestLicense
	isSet bool
}

func (v NullableAddProvisioningLicenseRequestLicense) Get() *AddProvisioningLicenseRequestLicense {
	return v.value
}

func (v *NullableAddProvisioningLicenseRequestLicense) Set(val *AddProvisioningLicenseRequestLicense) {
	v.value = val
	v.isSet = true
}

func (v NullableAddProvisioningLicenseRequestLicense) IsSet() bool {
	return v.isSet
}

func (v *NullableAddProvisioningLicenseRequestLicense) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddProvisioningLicenseRequestLicense(val *AddProvisioningLicenseRequestLicense) *NullableAddProvisioningLicenseRequestLicense {
	return &NullableAddProvisioningLicenseRequestLicense{value: val, isSet: true}
}

func (v NullableAddProvisioningLicenseRequestLicense) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddProvisioningLicenseRequestLicense) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableAddProvisioningLicenseRequestLicense) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *AddProvisioningLicenseRequestLicense) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
