/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the ListClusterPods200ResponseAllOfPodsInnerOwner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListClusterPods200ResponseAllOfPodsInnerOwner{}

// ListClusterPods200ResponseAllOfPodsInnerOwner struct for ListClusterPods200ResponseAllOfPodsInnerOwner
type ListClusterPods200ResponseAllOfPodsInnerOwner struct {
	Id                   *int64                 `json:"id,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _ListClusterPods200ResponseAllOfPodsInnerOwner ListClusterPods200ResponseAllOfPodsInnerOwner

// NewListClusterPods200ResponseAllOfPodsInnerOwner instantiates a new ListClusterPods200ResponseAllOfPodsInnerOwner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListClusterPods200ResponseAllOfPodsInnerOwner() *ListClusterPods200ResponseAllOfPodsInnerOwner {
	this := ListClusterPods200ResponseAllOfPodsInnerOwner{}
	return &this
}

// NewListClusterPods200ResponseAllOfPodsInnerOwnerWithDefaults instantiates a new ListClusterPods200ResponseAllOfPodsInnerOwner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListClusterPods200ResponseAllOfPodsInnerOwnerWithDefaults() *ListClusterPods200ResponseAllOfPodsInnerOwner {
	this := ListClusterPods200ResponseAllOfPodsInnerOwner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ListClusterPods200ResponseAllOfPodsInnerOwner) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListClusterPods200ResponseAllOfPodsInnerOwner) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ListClusterPods200ResponseAllOfPodsInnerOwner) SetId(v int64) {
	o.Id = &v
}

func (o ListClusterPods200ResponseAllOfPodsInnerOwner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListClusterPods200ResponseAllOfPodsInnerOwner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableListClusterPods200ResponseAllOfPodsInnerOwner struct {
	value *ListClusterPods200ResponseAllOfPodsInnerOwner
	isSet bool
}

func (v NullableListClusterPods200ResponseAllOfPodsInnerOwner) Get() *ListClusterPods200ResponseAllOfPodsInnerOwner {
	return v.value
}

func (v *NullableListClusterPods200ResponseAllOfPodsInnerOwner) Set(val *ListClusterPods200ResponseAllOfPodsInnerOwner) {
	v.value = val
	v.isSet = true
}

func (v NullableListClusterPods200ResponseAllOfPodsInnerOwner) IsSet() bool {
	return v.isSet
}

func (v *NullableListClusterPods200ResponseAllOfPodsInnerOwner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListClusterPods200ResponseAllOfPodsInnerOwner(val *ListClusterPods200ResponseAllOfPodsInnerOwner) *NullableListClusterPods200ResponseAllOfPodsInnerOwner {
	return &NullableListClusterPods200ResponseAllOfPodsInnerOwner{value: val, isSet: true}
}

func (v NullableListClusterPods200ResponseAllOfPodsInnerOwner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListClusterPods200ResponseAllOfPodsInnerOwner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableListClusterPods200ResponseAllOfPodsInnerOwner) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *ListClusterPods200ResponseAllOfPodsInnerOwner) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
