/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the UpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig{}

// UpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig Configuration object with parameters that vary by type.
type UpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig struct {
	Monitor *UpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfigMonitor `json:"monitor,omitempty"`
	// Free-form monitor configuration content.
	MonitorConfig        NullableString         `json:"monitorConfig,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _UpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig UpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig

func (o UpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Monitor) {
		toSerialize["monitor"] = o.Monitor
	}
	if o.MonitorConfig.IsSet() {
		toSerialize["monitorConfig"] = o.MonitorConfig.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig struct {
	value *UpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig
	isSet bool
}

func (v NullableUpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig) Get() *UpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig {
	return v.value
}

func (v *NullableUpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig) Set(val *UpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig(val *UpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig) *NullableUpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig {
	return &NullableUpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig{value: val, isSet: true}
}

func (v NullableUpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableUpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *UpdateLoadBalancerMonitor200ResponseAllOfLoadBalancerMonitorConfig) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
