/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the UpdateVirtualImageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateVirtualImageRequest{}

// UpdateVirtualImageRequest struct for UpdateVirtualImageRequest
type UpdateVirtualImageRequest struct {
	VirtualImage         UpdateVirtualImageRequestVirtualImage `json:"virtualImage"`
	AdditionalProperties map[string]interface{}                `json:",remain"`
}

type _UpdateVirtualImageRequest UpdateVirtualImageRequest

func (o UpdateVirtualImageRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateVirtualImageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["virtualImage"] = o.VirtualImage

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUpdateVirtualImageRequest struct {
	value *UpdateVirtualImageRequest
	isSet bool
}

func (v NullableUpdateVirtualImageRequest) Get() *UpdateVirtualImageRequest {
	return v.value
}

func (v *NullableUpdateVirtualImageRequest) Set(val *UpdateVirtualImageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateVirtualImageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateVirtualImageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateVirtualImageRequest(val *UpdateVirtualImageRequest) *NullableUpdateVirtualImageRequest {
	return &NullableUpdateVirtualImageRequest{value: val, isSet: true}
}

func (v NullableUpdateVirtualImageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateVirtualImageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableUpdateVirtualImageRequest) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *UpdateVirtualImageRequest) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
