/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the NetworkFirewallRuleCreateRuleGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkFirewallRuleCreateRuleGroup{}

// NetworkFirewallRuleCreateRuleGroup struct for NetworkFirewallRuleCreateRuleGroup
type NetworkFirewallRuleCreateRuleGroup struct {
	// Firewall rule group for rule (*applicable to select network servers).
	Id                   *int32                 `json:"id,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _NetworkFirewallRuleCreateRuleGroup NetworkFirewallRuleCreateRuleGroup

// NewNetworkFirewallRuleCreateRuleGroup instantiates a new NetworkFirewallRuleCreateRuleGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkFirewallRuleCreateRuleGroup() *NetworkFirewallRuleCreateRuleGroup {
	this := NetworkFirewallRuleCreateRuleGroup{}
	return &this
}

// NewNetworkFirewallRuleCreateRuleGroupWithDefaults instantiates a new NetworkFirewallRuleCreateRuleGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkFirewallRuleCreateRuleGroupWithDefaults() *NetworkFirewallRuleCreateRuleGroup {
	this := NetworkFirewallRuleCreateRuleGroup{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NetworkFirewallRuleCreateRuleGroup) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkFirewallRuleCreateRuleGroup) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *NetworkFirewallRuleCreateRuleGroup) SetId(v int32) {
	o.Id = &v
}

func (o NetworkFirewallRuleCreateRuleGroup) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkFirewallRuleCreateRuleGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableNetworkFirewallRuleCreateRuleGroup struct {
	value *NetworkFirewallRuleCreateRuleGroup
	isSet bool
}

func (v NullableNetworkFirewallRuleCreateRuleGroup) Get() *NetworkFirewallRuleCreateRuleGroup {
	return v.value
}

func (v *NullableNetworkFirewallRuleCreateRuleGroup) Set(val *NetworkFirewallRuleCreateRuleGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkFirewallRuleCreateRuleGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkFirewallRuleCreateRuleGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkFirewallRuleCreateRuleGroup(val *NetworkFirewallRuleCreateRuleGroup) *NullableNetworkFirewallRuleCreateRuleGroup {
	return &NullableNetworkFirewallRuleCreateRuleGroup{value: val, isSet: true}
}

func (v NullableNetworkFirewallRuleCreateRuleGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkFirewallRuleCreateRuleGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableNetworkFirewallRuleCreateRuleGroup) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *NetworkFirewallRuleCreateRuleGroup) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
