/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the SaveCloudDatastoreRequestDatastoreResourcePermissions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SaveCloudDatastoreRequestDatastoreResourcePermissions{}

// SaveCloudDatastoreRequestDatastoreResourcePermissions struct for SaveCloudDatastoreRequestDatastoreResourcePermissions
type SaveCloudDatastoreRequestDatastoreResourcePermissions struct {
	AllGroups            *bool                                                         `json:"allGroups,omitempty"`
	DefaultStore         *bool                                                         `json:"defaultStore,omitempty"`
	AllPlans             *bool                                                         `json:"allPlans,omitempty"`
	DefaultTarget        *bool                                                         `json:"defaultTarget,omitempty"`
	MorpheusResourceType *string                                                       `json:"morpheusResourceType,omitempty"`
	MorpheusResourceId   *int64                                                        `json:"morpheusResourceId,omitempty"`
	CanManage            *bool                                                         `json:"canManage,omitempty"`
	All                  *bool                                                         `json:"all,omitempty"`
	Account              *SaveCloudDatastoreRequestDatastoreResourcePermissionsAccount `json:"account,omitempty"`
	Sites                []map[string]interface{}                                      `json:"sites,omitempty"`
	Plans                []map[string]interface{}                                      `json:"plans,omitempty"`
	AdditionalProperties map[string]interface{}                                        `json:",remain"`
}

type _SaveCloudDatastoreRequestDatastoreResourcePermissions SaveCloudDatastoreRequestDatastoreResourcePermissions

// NewSaveCloudDatastoreRequestDatastoreResourcePermissionsWithDefaults instantiates a new SaveCloudDatastoreRequestDatastoreResourcePermissions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSaveCloudDatastoreRequestDatastoreResourcePermissionsWithDefaults() *SaveCloudDatastoreRequestDatastoreResourcePermissions {
	this := SaveCloudDatastoreRequestDatastoreResourcePermissions{}
	return &this
}

func (o SaveCloudDatastoreRequestDatastoreResourcePermissions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SaveCloudDatastoreRequestDatastoreResourcePermissions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AllGroups) {
		toSerialize["allGroups"] = o.AllGroups
	}
	if !IsNil(o.DefaultStore) {
		toSerialize["defaultStore"] = o.DefaultStore
	}
	if !IsNil(o.AllPlans) {
		toSerialize["allPlans"] = o.AllPlans
	}
	if !IsNil(o.DefaultTarget) {
		toSerialize["defaultTarget"] = o.DefaultTarget
	}
	if !IsNil(o.MorpheusResourceType) {
		toSerialize["morpheusResourceType"] = o.MorpheusResourceType
	}
	if !IsNil(o.MorpheusResourceId) {
		toSerialize["morpheusResourceId"] = o.MorpheusResourceId
	}
	if !IsNil(o.CanManage) {
		toSerialize["canManage"] = o.CanManage
	}
	if !IsNil(o.All) {
		toSerialize["all"] = o.All
	}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if o.Sites != nil {
		toSerialize["sites"] = o.Sites
	}
	if o.Plans != nil {
		toSerialize["plans"] = o.Plans
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableSaveCloudDatastoreRequestDatastoreResourcePermissions struct {
	value *SaveCloudDatastoreRequestDatastoreResourcePermissions
	isSet bool
}

func (v NullableSaveCloudDatastoreRequestDatastoreResourcePermissions) Get() *SaveCloudDatastoreRequestDatastoreResourcePermissions {
	return v.value
}

func (v *NullableSaveCloudDatastoreRequestDatastoreResourcePermissions) Set(val *SaveCloudDatastoreRequestDatastoreResourcePermissions) {
	v.value = val
	v.isSet = true
}

func (v NullableSaveCloudDatastoreRequestDatastoreResourcePermissions) IsSet() bool {
	return v.isSet
}

func (v *NullableSaveCloudDatastoreRequestDatastoreResourcePermissions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSaveCloudDatastoreRequestDatastoreResourcePermissions(val *SaveCloudDatastoreRequestDatastoreResourcePermissions) *NullableSaveCloudDatastoreRequestDatastoreResourcePermissions {
	return &NullableSaveCloudDatastoreRequestDatastoreResourcePermissions{value: val, isSet: true}
}

func (v NullableSaveCloudDatastoreRequestDatastoreResourcePermissions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSaveCloudDatastoreRequestDatastoreResourcePermissions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableSaveCloudDatastoreRequestDatastoreResourcePermissions) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *SaveCloudDatastoreRequestDatastoreResourcePermissions) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
