/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the UpdateVirtualImage200ResponseAllOfVirtualImageTenant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateVirtualImage200ResponseAllOfVirtualImageTenant{}

// UpdateVirtualImage200ResponseAllOfVirtualImageTenant struct for UpdateVirtualImage200ResponseAllOfVirtualImageTenant
type UpdateVirtualImage200ResponseAllOfVirtualImageTenant struct {
	Id                   *int64                 `json:"id,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _UpdateVirtualImage200ResponseAllOfVirtualImageTenant UpdateVirtualImage200ResponseAllOfVirtualImageTenant

func (o UpdateVirtualImage200ResponseAllOfVirtualImageTenant) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateVirtualImage200ResponseAllOfVirtualImageTenant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUpdateVirtualImage200ResponseAllOfVirtualImageTenant struct {
	value *UpdateVirtualImage200ResponseAllOfVirtualImageTenant
	isSet bool
}

func (v NullableUpdateVirtualImage200ResponseAllOfVirtualImageTenant) Get() *UpdateVirtualImage200ResponseAllOfVirtualImageTenant {
	return v.value
}

func (v *NullableUpdateVirtualImage200ResponseAllOfVirtualImageTenant) Set(val *UpdateVirtualImage200ResponseAllOfVirtualImageTenant) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateVirtualImage200ResponseAllOfVirtualImageTenant) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateVirtualImage200ResponseAllOfVirtualImageTenant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateVirtualImage200ResponseAllOfVirtualImageTenant(val *UpdateVirtualImage200ResponseAllOfVirtualImageTenant) *NullableUpdateVirtualImage200ResponseAllOfVirtualImageTenant {
	return &NullableUpdateVirtualImage200ResponseAllOfVirtualImageTenant{value: val, isSet: true}
}

func (v NullableUpdateVirtualImage200ResponseAllOfVirtualImageTenant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateVirtualImage200ResponseAllOfVirtualImageTenant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableUpdateVirtualImage200ResponseAllOfVirtualImageTenant) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *UpdateVirtualImage200ResponseAllOfVirtualImageTenant) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
