/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the UserGroupCreationPolicyTypeConfiguration16 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserGroupCreationPolicyTypeConfiguration16{}

// UserGroupCreationPolicyTypeConfiguration16 Configuration settings for the following policy types: - User Group Creation
type UserGroupCreationPolicyTypeConfiguration16 struct {
	UserGroup            *string                `json:"userGroup,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _UserGroupCreationPolicyTypeConfiguration16 UserGroupCreationPolicyTypeConfiguration16

// NewUserGroupCreationPolicyTypeConfiguration16 instantiates a new UserGroupCreationPolicyTypeConfiguration16 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserGroupCreationPolicyTypeConfiguration16() *UserGroupCreationPolicyTypeConfiguration16 {
	this := UserGroupCreationPolicyTypeConfiguration16{}
	return &this
}

// NewUserGroupCreationPolicyTypeConfiguration16WithDefaults instantiates a new UserGroupCreationPolicyTypeConfiguration16 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserGroupCreationPolicyTypeConfiguration16WithDefaults() *UserGroupCreationPolicyTypeConfiguration16 {
	this := UserGroupCreationPolicyTypeConfiguration16{}
	return &this
}

// GetUserGroup returns the UserGroup field value if set, zero value otherwise.
func (o *UserGroupCreationPolicyTypeConfiguration16) GetUserGroup() string {
	if o == nil || IsNil(o.UserGroup) {
		var ret string
		return ret
	}
	return *o.UserGroup
}

// GetUserGroupOk returns a tuple with the UserGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGroupCreationPolicyTypeConfiguration16) GetUserGroupOk() (*string, bool) {
	if o == nil || IsNil(o.UserGroup) {
		return nil, false
	}
	return o.UserGroup, true
}

// SetUserGroup gets a reference to the given string and assigns it to the UserGroup field.
func (o *UserGroupCreationPolicyTypeConfiguration16) SetUserGroup(v string) {
	o.UserGroup = &v
}

func (o UserGroupCreationPolicyTypeConfiguration16) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserGroupCreationPolicyTypeConfiguration16) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserGroup) {
		toSerialize["userGroup"] = o.UserGroup
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUserGroupCreationPolicyTypeConfiguration16 struct {
	value *UserGroupCreationPolicyTypeConfiguration16
	isSet bool
}

func (v NullableUserGroupCreationPolicyTypeConfiguration16) Get() *UserGroupCreationPolicyTypeConfiguration16 {
	return v.value
}

func (v *NullableUserGroupCreationPolicyTypeConfiguration16) Set(val *UserGroupCreationPolicyTypeConfiguration16) {
	v.value = val
	v.isSet = true
}

func (v NullableUserGroupCreationPolicyTypeConfiguration16) IsSet() bool {
	return v.isSet
}

func (v *NullableUserGroupCreationPolicyTypeConfiguration16) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserGroupCreationPolicyTypeConfiguration16(val *UserGroupCreationPolicyTypeConfiguration16) *NullableUserGroupCreationPolicyTypeConfiguration16 {
	return &NullableUserGroupCreationPolicyTypeConfiguration16{value: val, isSet: true}
}

func (v NullableUserGroupCreationPolicyTypeConfiguration16) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserGroupCreationPolicyTypeConfiguration16) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableUserGroupCreationPolicyTypeConfiguration16) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *UserGroupCreationPolicyTypeConfiguration16) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
