/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the UpdateNetworkGroupRequestNetworkGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNetworkGroupRequestNetworkGroup{}

// UpdateNetworkGroupRequestNetworkGroup struct for UpdateNetworkGroupRequestNetworkGroup
type UpdateNetworkGroupRequestNetworkGroup struct {
	Name                 *string                  `json:"name,omitempty"`
	Description          *string                  `json:"description,omitempty"`
	Networks             []int64                  `json:"networks,omitempty"`
	Subnets              []map[string]interface{} `json:"subnets,omitempty"`
	AdditionalProperties map[string]interface{}   `json:",remain"`
}

type _UpdateNetworkGroupRequestNetworkGroup UpdateNetworkGroupRequestNetworkGroup

// NewUpdateNetworkGroupRequestNetworkGroupWithDefaults instantiates a new UpdateNetworkGroupRequestNetworkGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNetworkGroupRequestNetworkGroupWithDefaults() *UpdateNetworkGroupRequestNetworkGroup {
	this := UpdateNetworkGroupRequestNetworkGroup{}
	return &this
}

func (o UpdateNetworkGroupRequestNetworkGroup) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNetworkGroupRequestNetworkGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Networks) {
		toSerialize["networks"] = o.Networks
	}
	if !IsNil(o.Subnets) {
		toSerialize["subnets"] = o.Subnets
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUpdateNetworkGroupRequestNetworkGroup struct {
	value *UpdateNetworkGroupRequestNetworkGroup
	isSet bool
}

func (v NullableUpdateNetworkGroupRequestNetworkGroup) Get() *UpdateNetworkGroupRequestNetworkGroup {
	return v.value
}

func (v *NullableUpdateNetworkGroupRequestNetworkGroup) Set(val *UpdateNetworkGroupRequestNetworkGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNetworkGroupRequestNetworkGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNetworkGroupRequestNetworkGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNetworkGroupRequestNetworkGroup(val *UpdateNetworkGroupRequestNetworkGroup) *NullableUpdateNetworkGroupRequestNetworkGroup {
	return &NullableUpdateNetworkGroupRequestNetworkGroup{value: val, isSet: true}
}

func (v NullableUpdateNetworkGroupRequestNetworkGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNetworkGroupRequestNetworkGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableUpdateNetworkGroupRequestNetworkGroup) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *UpdateNetworkGroupRequestNetworkGroup) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
