/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the AddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1{}

// AddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1 Type GCP
type AddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1 struct {
	// Project ID can have lowercase letters, digits, or hyphens. It must start with a lowercase letter and end with a letter or number.
	ProjectId            NullableString         `json:"projectId,omitempty"`
	Parent               interface{}            `json:"parent"`
	BillingAccount       string                 `json:"billingAccount"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _AddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1 AddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1

// NewAddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1WithDefaults instantiates a new AddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1WithDefaults() *AddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1 {
	this := AddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1{}
	return &this
}

func (o AddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ProjectId.IsSet() {
		toSerialize["projectId"] = o.ProjectId.Get()
	}
	if o.Parent != nil {
		toSerialize["parent"] = o.Parent
	}
	toSerialize["billingAccount"] = o.BillingAccount

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableAddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1 struct {
	value *AddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1
	isSet bool
}

func (v NullableAddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1) Get() *AddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1 {
	return v.value
}

func (v *NullableAddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1) Set(val *AddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableAddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableAddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1(val *AddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1) *NullableAddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1 {
	return &NullableAddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1{value: val, isSet: true}
}

func (v NullableAddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableAddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *AddCloudResourcePool200ResponseResourcePoolAllOfConfigAnyOf1) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
