/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the CreateSubnet200ResponseSubnetType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSubnet200ResponseSubnetType{}

// CreateSubnet200ResponseSubnetType struct for CreateSubnet200ResponseSubnetType
type CreateSubnet200ResponseSubnetType struct {
	Id                   *int64                 `json:"id,omitempty"`
	Code                 *string                `json:"code,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _CreateSubnet200ResponseSubnetType CreateSubnet200ResponseSubnetType

func (o CreateSubnet200ResponseSubnetType) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSubnet200ResponseSubnetType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableCreateSubnet200ResponseSubnetType struct {
	value *CreateSubnet200ResponseSubnetType
	isSet bool
}

func (v NullableCreateSubnet200ResponseSubnetType) Get() *CreateSubnet200ResponseSubnetType {
	return v.value
}

func (v *NullableCreateSubnet200ResponseSubnetType) Set(val *CreateSubnet200ResponseSubnetType) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSubnet200ResponseSubnetType) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSubnet200ResponseSubnetType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSubnet200ResponseSubnetType(val *CreateSubnet200ResponseSubnetType) *NullableCreateSubnet200ResponseSubnetType {
	return &NullableCreateSubnet200ResponseSubnetType{value: val, isSet: true}
}

func (v NullableCreateSubnet200ResponseSubnetType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSubnet200ResponseSubnetType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableCreateSubnet200ResponseSubnetType) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *CreateSubnet200ResponseSubnetType) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
