/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the InstancesNetworkInterfaces1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstancesNetworkInterfaces1{}

// InstancesNetworkInterfaces1 struct for InstancesNetworkInterfaces1
type InstancesNetworkInterfaces1 struct {
	Network InstancesNetworkInterfaces1Network `json:"network"`
	// The id of type of the network interface.
	NetworkInterfaceTypeId *int64 `json:"networkInterfaceTypeId,omitempty"`
	// The mode for determining ip address. Can be 'static', 'dhcp' or empty string.
	IpMode *string `json:"ipMode,omitempty"`
	// The ip address. Not applicable when using DHCP or IP Pools.
	IpAddress *string `json:"ipAddress,omitempty"`
	// The MAC address.
	MacAddress *string `json:"macAddress,omitempty"`
	// The interface id. Applicable when resizing and you want to identify an interface to update that already exists.
	Id *int64 `json:"id,omitempty"`
	// The nested networkInterfaces can be used to define child virtual network interfaces. The Options API `/api/options/zoneNetworkOptions?zoneId=5&provisionTypeId=10` can be used to see which types support this (`hasVirtualInvirtualInterfaces = true` and list of available `virtualInterfaces` will be defined.
	NetworkInterfaces    []InstancesNetworkInterfaces1NetworkInterfacesInner `json:"networkInterfaces,omitempty"`
	AdditionalProperties map[string]interface{}                              `json:",remain"`
}

type _InstancesNetworkInterfaces1 InstancesNetworkInterfaces1

func (o InstancesNetworkInterfaces1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstancesNetworkInterfaces1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["network"] = o.Network
	if !IsNil(o.NetworkInterfaceTypeId) {
		toSerialize["networkInterfaceTypeId"] = o.NetworkInterfaceTypeId
	}
	if !IsNil(o.IpMode) {
		toSerialize["ipMode"] = o.IpMode
	}
	if !IsNil(o.IpAddress) {
		toSerialize["ipAddress"] = o.IpAddress
	}
	if !IsNil(o.MacAddress) {
		toSerialize["macAddress"] = o.MacAddress
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.NetworkInterfaces) {
		toSerialize["networkInterfaces"] = o.NetworkInterfaces
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableInstancesNetworkInterfaces1 struct {
	value *InstancesNetworkInterfaces1
	isSet bool
}

func (v NullableInstancesNetworkInterfaces1) Get() *InstancesNetworkInterfaces1 {
	return v.value
}

func (v *NullableInstancesNetworkInterfaces1) Set(val *InstancesNetworkInterfaces1) {
	v.value = val
	v.isSet = true
}

func (v NullableInstancesNetworkInterfaces1) IsSet() bool {
	return v.isSet
}

func (v *NullableInstancesNetworkInterfaces1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstancesNetworkInterfaces1(val *InstancesNetworkInterfaces1) *NullableInstancesNetworkInterfaces1 {
	return &NullableInstancesNetworkInterfaces1{value: val, isSet: true}
}

func (v NullableInstancesNetworkInterfaces1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstancesNetworkInterfaces1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableInstancesNetworkInterfaces1) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *InstancesNetworkInterfaces1) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
