/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the MigrationUpdateDatastoresInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MigrationUpdateDatastoresInner{}

// MigrationUpdateDatastoresInner struct for MigrationUpdateDatastoresInner
type MigrationUpdateDatastoresInner struct {
	SourceDatastore      *MigrationUpdateDatastoresInnerSourceDatastore      `json:"sourceDatastore,omitempty"`
	DestinationDatastore *MigrationUpdateDatastoresInnerDestinationDatastore `json:"destinationDatastore,omitempty"`
	AdditionalProperties map[string]interface{}                              `json:",remain"`
}

type _MigrationUpdateDatastoresInner MigrationUpdateDatastoresInner

func (o MigrationUpdateDatastoresInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MigrationUpdateDatastoresInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SourceDatastore) {
		toSerialize["sourceDatastore"] = o.SourceDatastore
	}
	if !IsNil(o.DestinationDatastore) {
		toSerialize["destinationDatastore"] = o.DestinationDatastore
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableMigrationUpdateDatastoresInner struct {
	value *MigrationUpdateDatastoresInner
	isSet bool
}

func (v NullableMigrationUpdateDatastoresInner) Get() *MigrationUpdateDatastoresInner {
	return v.value
}

func (v *NullableMigrationUpdateDatastoresInner) Set(val *MigrationUpdateDatastoresInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMigrationUpdateDatastoresInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMigrationUpdateDatastoresInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMigrationUpdateDatastoresInner(val *MigrationUpdateDatastoresInner) *NullableMigrationUpdateDatastoresInner {
	return &NullableMigrationUpdateDatastoresInner{value: val, isSet: true}
}

func (v NullableMigrationUpdateDatastoresInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMigrationUpdateDatastoresInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableMigrationUpdateDatastoresInner) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *MigrationUpdateDatastoresInner) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
