/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.10
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the InstancesChildVirtualNetworkInterfacesInner3Network type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstancesChildVirtualNetworkInterfacesInner3Network{}

// InstancesChildVirtualNetworkInterfacesInner3Network struct for InstancesChildVirtualNetworkInterfacesInner3Network
type InstancesChildVirtualNetworkInterfacesInner3Network struct {
	// id of the network to be used. A network group can be specified instead by prefixing its ID with `networkGroup-`.
	Id                   string                                                   `json:"id"`
	Pool                 *InstancesChildVirtualNetworkInterfacesInner3NetworkPool `json:"pool,omitempty"`
	AdditionalProperties map[string]interface{}                                   `json:",remain"`
}

type _InstancesChildVirtualNetworkInterfacesInner3Network InstancesChildVirtualNetworkInterfacesInner3Network

// NewInstancesChildVirtualNetworkInterfacesInner3Network instantiates a new InstancesChildVirtualNetworkInterfacesInner3Network object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstancesChildVirtualNetworkInterfacesInner3Network(id string) *InstancesChildVirtualNetworkInterfacesInner3Network {
	this := InstancesChildVirtualNetworkInterfacesInner3Network{}
	this.Id = id
	return &this
}

// NewInstancesChildVirtualNetworkInterfacesInner3NetworkWithDefaults instantiates a new InstancesChildVirtualNetworkInterfacesInner3Network object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstancesChildVirtualNetworkInterfacesInner3NetworkWithDefaults() *InstancesChildVirtualNetworkInterfacesInner3Network {
	this := InstancesChildVirtualNetworkInterfacesInner3Network{}
	return &this
}

// GetId returns the Id field value
func (o *InstancesChildVirtualNetworkInterfacesInner3Network) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InstancesChildVirtualNetworkInterfacesInner3Network) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InstancesChildVirtualNetworkInterfacesInner3Network) SetId(v string) {
	o.Id = v
}

// GetPool returns the Pool field value if set, zero value otherwise.
func (o *InstancesChildVirtualNetworkInterfacesInner3Network) GetPool() InstancesChildVirtualNetworkInterfacesInner3NetworkPool {
	if o == nil || IsNil(o.Pool) {
		var ret InstancesChildVirtualNetworkInterfacesInner3NetworkPool
		return ret
	}
	return *o.Pool
}

// GetPoolOk returns a tuple with the Pool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstancesChildVirtualNetworkInterfacesInner3Network) GetPoolOk() (*InstancesChildVirtualNetworkInterfacesInner3NetworkPool, bool) {
	if o == nil || IsNil(o.Pool) {
		return nil, false
	}
	return o.Pool, true
}

// IsSetPool returns a boolean if a field has been set.
func (o *InstancesChildVirtualNetworkInterfacesInner3Network) IsSetPool() bool {
	if o != nil && !IsNil(o.Pool) {
		return true
	}

	return false
}

// SetPool gets a reference to the given InstancesChildVirtualNetworkInterfacesInner3NetworkPool and assigns it to the Pool field.
func (o *InstancesChildVirtualNetworkInterfacesInner3Network) SetPool(v InstancesChildVirtualNetworkInterfacesInner3NetworkPool) {
	o.Pool = &v
}

func (o InstancesChildVirtualNetworkInterfacesInner3Network) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstancesChildVirtualNetworkInterfacesInner3Network) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Pool) {
		toSerialize["pool"] = o.Pool
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableInstancesChildVirtualNetworkInterfacesInner3Network struct {
	value *InstancesChildVirtualNetworkInterfacesInner3Network
	isSet bool
}

func (v NullableInstancesChildVirtualNetworkInterfacesInner3Network) Get() *InstancesChildVirtualNetworkInterfacesInner3Network {
	return v.value
}

func (v *NullableInstancesChildVirtualNetworkInterfacesInner3Network) Set(val *InstancesChildVirtualNetworkInterfacesInner3Network) {
	v.value = val
	v.isSet = true
}

func (v NullableInstancesChildVirtualNetworkInterfacesInner3Network) IsSet() bool {
	return v.isSet
}

func (v *NullableInstancesChildVirtualNetworkInterfacesInner3Network) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstancesChildVirtualNetworkInterfacesInner3Network(val *InstancesChildVirtualNetworkInterfacesInner3Network) *NullableInstancesChildVirtualNetworkInterfacesInner3Network {
	return &NullableInstancesChildVirtualNetworkInterfacesInner3Network{value: val, isSet: true}
}

func (v NullableInstancesChildVirtualNetworkInterfacesInner3Network) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstancesChildVirtualNetworkInterfacesInner3Network) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableInstancesChildVirtualNetworkInterfacesInner3Network) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}
func (o *InstancesChildVirtualNetworkInterfacesInner3Network) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
