/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the GetTenant200ResponseAccountStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTenant200ResponseAccountStats{}

// GetTenant200ResponseAccountStats struct for GetTenant200ResponseAccountStats
type GetTenant200ResponseAccountStats struct {
	InstanceCount        *int64                 `json:"instanceCount,omitempty"`
	UserCount            *int64                 `json:"userCount,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _GetTenant200ResponseAccountStats GetTenant200ResponseAccountStats

// NewGetTenant200ResponseAccountStatsWithDefaults instantiates a new GetTenant200ResponseAccountStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTenant200ResponseAccountStatsWithDefaults() *GetTenant200ResponseAccountStats {
	this := GetTenant200ResponseAccountStats{}
	return &this
}

func (o GetTenant200ResponseAccountStats) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTenant200ResponseAccountStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InstanceCount) {
		toSerialize["instanceCount"] = o.InstanceCount
	}
	if !IsNil(o.UserCount) {
		toSerialize["userCount"] = o.UserCount
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableGetTenant200ResponseAccountStats struct {
	value *GetTenant200ResponseAccountStats
	isSet bool
}

func (v NullableGetTenant200ResponseAccountStats) Get() *GetTenant200ResponseAccountStats {
	return v.value
}

func (v *NullableGetTenant200ResponseAccountStats) Set(val *GetTenant200ResponseAccountStats) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTenant200ResponseAccountStats) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTenant200ResponseAccountStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTenant200ResponseAccountStats(val *GetTenant200ResponseAccountStats) *NullableGetTenant200ResponseAccountStats {
	return &NullableGetTenant200ResponseAccountStats{value: val, isSet: true}
}

func (v NullableGetTenant200ResponseAccountStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTenant200ResponseAccountStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableGetTenant200ResponseAccountStats) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *GetTenant200ResponseAccountStats) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
