/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the GetVDIPools200ResponseVdiPoolConfigGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetVDIPools200ResponseVdiPoolConfigGroup{}

// GetVDIPools200ResponseVdiPoolConfigGroup struct for GetVDIPools200ResponseVdiPoolConfigGroup
type GetVDIPools200ResponseVdiPoolConfigGroup struct {
	Id                   *string                `json:"id,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _GetVDIPools200ResponseVdiPoolConfigGroup GetVDIPools200ResponseVdiPoolConfigGroup

// NewGetVDIPools200ResponseVdiPoolConfigGroupWithDefaults instantiates a new GetVDIPools200ResponseVdiPoolConfigGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVDIPools200ResponseVdiPoolConfigGroupWithDefaults() *GetVDIPools200ResponseVdiPoolConfigGroup {
	this := GetVDIPools200ResponseVdiPoolConfigGroup{}
	return &this
}

func (o GetVDIPools200ResponseVdiPoolConfigGroup) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetVDIPools200ResponseVdiPoolConfigGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableGetVDIPools200ResponseVdiPoolConfigGroup struct {
	value *GetVDIPools200ResponseVdiPoolConfigGroup
	isSet bool
}

func (v NullableGetVDIPools200ResponseVdiPoolConfigGroup) Get() *GetVDIPools200ResponseVdiPoolConfigGroup {
	return v.value
}

func (v *NullableGetVDIPools200ResponseVdiPoolConfigGroup) Set(val *GetVDIPools200ResponseVdiPoolConfigGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVDIPools200ResponseVdiPoolConfigGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVDIPools200ResponseVdiPoolConfigGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVDIPools200ResponseVdiPoolConfigGroup(val *GetVDIPools200ResponseVdiPoolConfigGroup) *NullableGetVDIPools200ResponseVdiPoolConfigGroup {
	return &NullableGetVDIPools200ResponseVdiPoolConfigGroup{value: val, isSet: true}
}

func (v NullableGetVDIPools200ResponseVdiPoolConfigGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVDIPools200ResponseVdiPoolConfigGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableGetVDIPools200ResponseVdiPoolConfigGroup) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *GetVDIPools200ResponseVdiPoolConfigGroup) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
