/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the ApprovalApprovalItemsInnerApproval type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApprovalApprovalItemsInnerApproval{}

// ApprovalApprovalItemsInnerApproval struct for ApprovalApprovalItemsInnerApproval
type ApprovalApprovalItemsInnerApproval struct {
	Id                   *int64                 `json:"id,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _ApprovalApprovalItemsInnerApproval ApprovalApprovalItemsInnerApproval

func (o ApprovalApprovalItemsInnerApproval) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApprovalApprovalItemsInnerApproval) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableApprovalApprovalItemsInnerApproval struct {
	value *ApprovalApprovalItemsInnerApproval
	isSet bool
}

func (v NullableApprovalApprovalItemsInnerApproval) Get() *ApprovalApprovalItemsInnerApproval {
	return v.value
}

func (v *NullableApprovalApprovalItemsInnerApproval) Set(val *ApprovalApprovalItemsInnerApproval) {
	v.value = val
	v.isSet = true
}

func (v NullableApprovalApprovalItemsInnerApproval) IsSet() bool {
	return v.isSet
}

func (v *NullableApprovalApprovalItemsInnerApproval) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApprovalApprovalItemsInnerApproval(val *ApprovalApprovalItemsInnerApproval) *NullableApprovalApprovalItemsInnerApproval {
	return &NullableApprovalApprovalItemsInnerApproval{value: val, isSet: true}
}

func (v NullableApprovalApprovalItemsInnerApproval) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApprovalApprovalItemsInnerApproval) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableApprovalApprovalItemsInnerApproval) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *ApprovalApprovalItemsInnerApproval) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
