/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the BlueprintHelmCreateHelmGit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlueprintHelmCreateHelmGit{}

// BlueprintHelmCreateHelmGit struct for BlueprintHelmCreateHelmGit
type BlueprintHelmCreateHelmGit struct {
	// Morpheus SCM Repository ID
	RepoId int64 `json:"repoId"`
	// Path to Helm Files in the Repository
	Path string `json:"path"`
	// Morpheus SCM Integration ID
	IntegrationId int64 `json:"integrationId"`
	// Branch Name
	Branch               string                 `json:"branch"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _BlueprintHelmCreateHelmGit BlueprintHelmCreateHelmGit

func (o BlueprintHelmCreateHelmGit) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlueprintHelmCreateHelmGit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["repoId"] = o.RepoId
	toSerialize["path"] = o.Path
	toSerialize["integrationId"] = o.IntegrationId
	toSerialize["branch"] = o.Branch

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableBlueprintHelmCreateHelmGit struct {
	value *BlueprintHelmCreateHelmGit
	isSet bool
}

func (v NullableBlueprintHelmCreateHelmGit) Get() *BlueprintHelmCreateHelmGit {
	return v.value
}

func (v *NullableBlueprintHelmCreateHelmGit) Set(val *BlueprintHelmCreateHelmGit) {
	v.value = val
	v.isSet = true
}

func (v NullableBlueprintHelmCreateHelmGit) IsSet() bool {
	return v.isSet
}

func (v *NullableBlueprintHelmCreateHelmGit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlueprintHelmCreateHelmGit(val *BlueprintHelmCreateHelmGit) *NullableBlueprintHelmCreateHelmGit {
	return &NullableBlueprintHelmCreateHelmGit{value: val, isSet: true}
}

func (v NullableBlueprintHelmCreateHelmGit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlueprintHelmCreateHelmGit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableBlueprintHelmCreateHelmGit) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *BlueprintHelmCreateHelmGit) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
