/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the GetSubnet200ResponseSubnetType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSubnet200ResponseSubnetType{}

// GetSubnet200ResponseSubnetType struct for GetSubnet200ResponseSubnetType
type GetSubnet200ResponseSubnetType struct {
	Id                   *int64                 `json:"id,omitempty"`
	Code                 *string                `json:"code,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _GetSubnet200ResponseSubnetType GetSubnet200ResponseSubnetType

func (o GetSubnet200ResponseSubnetType) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSubnet200ResponseSubnetType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableGetSubnet200ResponseSubnetType struct {
	value *GetSubnet200ResponseSubnetType
	isSet bool
}

func (v NullableGetSubnet200ResponseSubnetType) Get() *GetSubnet200ResponseSubnetType {
	return v.value
}

func (v *NullableGetSubnet200ResponseSubnetType) Set(val *GetSubnet200ResponseSubnetType) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSubnet200ResponseSubnetType) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSubnet200ResponseSubnetType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSubnet200ResponseSubnetType(val *GetSubnet200ResponseSubnetType) *NullableGetSubnet200ResponseSubnetType {
	return &NullableGetSubnet200ResponseSubnetType{value: val, isSet: true}
}

func (v NullableGetSubnet200ResponseSubnetType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSubnet200ResponseSubnetType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableGetSubnet200ResponseSubnetType) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *GetSubnet200ResponseSubnetType) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
