/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the GetCredentials200ResponseCredentialAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCredentials200ResponseCredentialAccount{}

// GetCredentials200ResponseCredentialAccount struct for GetCredentials200ResponseCredentialAccount
type GetCredentials200ResponseCredentialAccount struct {
	Id                   *int64                 `json:"id,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _GetCredentials200ResponseCredentialAccount GetCredentials200ResponseCredentialAccount

// NewGetCredentials200ResponseCredentialAccount instantiates a new GetCredentials200ResponseCredentialAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCredentials200ResponseCredentialAccount() *GetCredentials200ResponseCredentialAccount {
	this := GetCredentials200ResponseCredentialAccount{}
	return &this
}

// NewGetCredentials200ResponseCredentialAccountWithDefaults instantiates a new GetCredentials200ResponseCredentialAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCredentials200ResponseCredentialAccountWithDefaults() *GetCredentials200ResponseCredentialAccount {
	this := GetCredentials200ResponseCredentialAccount{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetCredentials200ResponseCredentialAccount) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCredentials200ResponseCredentialAccount) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// IsSetId returns a boolean if a field has been set.
func (o *GetCredentials200ResponseCredentialAccount) IsSetId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *GetCredentials200ResponseCredentialAccount) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetCredentials200ResponseCredentialAccount) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCredentials200ResponseCredentialAccount) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// IsSetName returns a boolean if a field has been set.
func (o *GetCredentials200ResponseCredentialAccount) IsSetName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetCredentials200ResponseCredentialAccount) SetName(v string) {
	o.Name = &v
}

func (o GetCredentials200ResponseCredentialAccount) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCredentials200ResponseCredentialAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableGetCredentials200ResponseCredentialAccount struct {
	value *GetCredentials200ResponseCredentialAccount
	isSet bool
}

func (v NullableGetCredentials200ResponseCredentialAccount) Get() *GetCredentials200ResponseCredentialAccount {
	return v.value
}

func (v *NullableGetCredentials200ResponseCredentialAccount) Set(val *GetCredentials200ResponseCredentialAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCredentials200ResponseCredentialAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCredentials200ResponseCredentialAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCredentials200ResponseCredentialAccount(val *GetCredentials200ResponseCredentialAccount) *NullableGetCredentials200ResponseCredentialAccount {
	return &NullableGetCredentials200ResponseCredentialAccount{value: val, isSet: true}
}

func (v NullableGetCredentials200ResponseCredentialAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCredentials200ResponseCredentialAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableGetCredentials200ResponseCredentialAccount) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *GetCredentials200ResponseCredentialAccount) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
