/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the GetSubnet200ResponseSubnetZone type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSubnet200ResponseSubnetZone{}

// GetSubnet200ResponseSubnetZone struct for GetSubnet200ResponseSubnetZone
type GetSubnet200ResponseSubnetZone struct {
	Id                   *int64                 `json:"id,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _GetSubnet200ResponseSubnetZone GetSubnet200ResponseSubnetZone

func (o GetSubnet200ResponseSubnetZone) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSubnet200ResponseSubnetZone) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableGetSubnet200ResponseSubnetZone struct {
	value *GetSubnet200ResponseSubnetZone
	isSet bool
}

func (v NullableGetSubnet200ResponseSubnetZone) Get() *GetSubnet200ResponseSubnetZone {
	return v.value
}

func (v *NullableGetSubnet200ResponseSubnetZone) Set(val *GetSubnet200ResponseSubnetZone) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSubnet200ResponseSubnetZone) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSubnet200ResponseSubnetZone) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSubnet200ResponseSubnetZone(val *GetSubnet200ResponseSubnetZone) *NullableGetSubnet200ResponseSubnetZone {
	return &NullableGetSubnet200ResponseSubnetZone{value: val, isSet: true}
}

func (v NullableGetSubnet200ResponseSubnetZone) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSubnet200ResponseSubnetZone) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableGetSubnet200ResponseSubnetZone) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *GetSubnet200ResponseSubnetZone) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
