/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.10
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the InstancesChildVirtualNetworkInterfacesInner4NetworkPool type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstancesChildVirtualNetworkInterfacesInner4NetworkPool{}

// InstancesChildVirtualNetworkInterfacesInner4NetworkPool struct for InstancesChildVirtualNetworkInterfacesInner4NetworkPool
type InstancesChildVirtualNetworkInterfacesInner4NetworkPool struct {
	// id of the ip pool to be used with this network
	Id                   *int64                 `json:"id,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _InstancesChildVirtualNetworkInterfacesInner4NetworkPool InstancesChildVirtualNetworkInterfacesInner4NetworkPool

// NewInstancesChildVirtualNetworkInterfacesInner4NetworkPool instantiates a new InstancesChildVirtualNetworkInterfacesInner4NetworkPool object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstancesChildVirtualNetworkInterfacesInner4NetworkPool() *InstancesChildVirtualNetworkInterfacesInner4NetworkPool {
	this := InstancesChildVirtualNetworkInterfacesInner4NetworkPool{}
	return &this
}

// NewInstancesChildVirtualNetworkInterfacesInner4NetworkPoolWithDefaults instantiates a new InstancesChildVirtualNetworkInterfacesInner4NetworkPool object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstancesChildVirtualNetworkInterfacesInner4NetworkPoolWithDefaults() *InstancesChildVirtualNetworkInterfacesInner4NetworkPool {
	this := InstancesChildVirtualNetworkInterfacesInner4NetworkPool{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InstancesChildVirtualNetworkInterfacesInner4NetworkPool) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstancesChildVirtualNetworkInterfacesInner4NetworkPool) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// IsSetId returns a boolean if a field has been set.
func (o *InstancesChildVirtualNetworkInterfacesInner4NetworkPool) IsSetId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *InstancesChildVirtualNetworkInterfacesInner4NetworkPool) SetId(v int64) {
	o.Id = &v
}

func (o InstancesChildVirtualNetworkInterfacesInner4NetworkPool) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstancesChildVirtualNetworkInterfacesInner4NetworkPool) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableInstancesChildVirtualNetworkInterfacesInner4NetworkPool struct {
	value *InstancesChildVirtualNetworkInterfacesInner4NetworkPool
	isSet bool
}

func (v NullableInstancesChildVirtualNetworkInterfacesInner4NetworkPool) Get() *InstancesChildVirtualNetworkInterfacesInner4NetworkPool {
	return v.value
}

func (v *NullableInstancesChildVirtualNetworkInterfacesInner4NetworkPool) Set(val *InstancesChildVirtualNetworkInterfacesInner4NetworkPool) {
	v.value = val
	v.isSet = true
}

func (v NullableInstancesChildVirtualNetworkInterfacesInner4NetworkPool) IsSet() bool {
	return v.isSet
}

func (v *NullableInstancesChildVirtualNetworkInterfacesInner4NetworkPool) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstancesChildVirtualNetworkInterfacesInner4NetworkPool(val *InstancesChildVirtualNetworkInterfacesInner4NetworkPool) *NullableInstancesChildVirtualNetworkInterfacesInner4NetworkPool {
	return &NullableInstancesChildVirtualNetworkInterfacesInner4NetworkPool{value: val, isSet: true}
}

func (v NullableInstancesChildVirtualNetworkInterfacesInner4NetworkPool) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstancesChildVirtualNetworkInterfacesInner4NetworkPool) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableInstancesChildVirtualNetworkInterfacesInner4NetworkPool) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}
func (o *InstancesChildVirtualNetworkInterfacesInner4NetworkPool) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
