/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the ExecuteTasks200ResponseAllOfJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExecuteTasks200ResponseAllOfJob{}

// ExecuteTasks200ResponseAllOfJob struct for ExecuteTasks200ResponseAllOfJob
type ExecuteTasks200ResponseAllOfJob struct {
	Id                   *int64                 `json:"id,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _ExecuteTasks200ResponseAllOfJob ExecuteTasks200ResponseAllOfJob

func (o ExecuteTasks200ResponseAllOfJob) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExecuteTasks200ResponseAllOfJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableExecuteTasks200ResponseAllOfJob struct {
	value *ExecuteTasks200ResponseAllOfJob
	isSet bool
}

func (v NullableExecuteTasks200ResponseAllOfJob) Get() *ExecuteTasks200ResponseAllOfJob {
	return v.value
}

func (v *NullableExecuteTasks200ResponseAllOfJob) Set(val *ExecuteTasks200ResponseAllOfJob) {
	v.value = val
	v.isSet = true
}

func (v NullableExecuteTasks200ResponseAllOfJob) IsSet() bool {
	return v.isSet
}

func (v *NullableExecuteTasks200ResponseAllOfJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecuteTasks200ResponseAllOfJob(val *ExecuteTasks200ResponseAllOfJob) *NullableExecuteTasks200ResponseAllOfJob {
	return &NullableExecuteTasks200ResponseAllOfJob{value: val, isSet: true}
}

func (v NullableExecuteTasks200ResponseAllOfJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecuteTasks200ResponseAllOfJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableExecuteTasks200ResponseAllOfJob) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *ExecuteTasks200ResponseAllOfJob) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
