/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the UpdateServicePlansRequestServicePlanPriceSetsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateServicePlansRequestServicePlanPriceSetsInner{}

// UpdateServicePlansRequestServicePlanPriceSetsInner struct for UpdateServicePlansRequestServicePlanPriceSetsInner
type UpdateServicePlansRequestServicePlanPriceSetsInner struct {
	// Price Set ID
	Id                   *int64                 `json:"id,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _UpdateServicePlansRequestServicePlanPriceSetsInner UpdateServicePlansRequestServicePlanPriceSetsInner

func (o UpdateServicePlansRequestServicePlanPriceSetsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateServicePlansRequestServicePlanPriceSetsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUpdateServicePlansRequestServicePlanPriceSetsInner struct {
	value *UpdateServicePlansRequestServicePlanPriceSetsInner
	isSet bool
}

func (v NullableUpdateServicePlansRequestServicePlanPriceSetsInner) Get() *UpdateServicePlansRequestServicePlanPriceSetsInner {
	return v.value
}

func (v *NullableUpdateServicePlansRequestServicePlanPriceSetsInner) Set(val *UpdateServicePlansRequestServicePlanPriceSetsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateServicePlansRequestServicePlanPriceSetsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateServicePlansRequestServicePlanPriceSetsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateServicePlansRequestServicePlanPriceSetsInner(val *UpdateServicePlansRequestServicePlanPriceSetsInner) *NullableUpdateServicePlansRequestServicePlanPriceSetsInner {
	return &NullableUpdateServicePlansRequestServicePlanPriceSetsInner{value: val, isSet: true}
}

func (v NullableUpdateServicePlansRequestServicePlanPriceSetsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateServicePlansRequestServicePlanPriceSetsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableUpdateServicePlansRequestServicePlanPriceSetsInner) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *UpdateServicePlansRequestServicePlanPriceSetsInner) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
