/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2{}

// AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2 - Backup Targets
type AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2 struct {
	BackupStorageIds     []int64                `json:"backupStorageIds,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2 AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2

// NewAddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2 instantiates a new AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2() *AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2 {
	this := AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2{}
	return &this
}

// NewAddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2WithDefaults instantiates a new AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2WithDefaults() *AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2 {
	this := AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2{}
	return &this
}

// GetBackupStorageIds returns the BackupStorageIds field value if set, zero value otherwise.
func (o *AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2) GetBackupStorageIds() []int64 {
	if o == nil || IsNil(o.BackupStorageIds) {
		var ret []int64
		return ret
	}
	return o.BackupStorageIds
}

// GetBackupStorageIdsOk returns a tuple with the BackupStorageIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2) GetBackupStorageIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.BackupStorageIds) {
		return nil, false
	}
	return o.BackupStorageIds, true
}

// SetBackupStorageIds gets a reference to the given []int64 and assigns it to the BackupStorageIds field.
func (o *AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2) SetBackupStorageIds(v []int64) {
	o.BackupStorageIds = v
}

func (o AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BackupStorageIds) {
		toSerialize["backupStorageIds"] = o.BackupStorageIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableAddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2 struct {
	value *AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2
	isSet bool
}

func (v NullableAddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2) Get() *AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2 {
	return v.value
}

func (v *NullableAddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2) Set(val *AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableAddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableAddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2(val *AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2) *NullableAddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2 {
	return &NullableAddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2{value: val, isSet: true}
}

func (v NullableAddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableAddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *AddPoliciesCloudRequestPolicyPolicyTypeConfigOneOf2) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
