/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the TokenAuthorizationCodeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenAuthorizationCodeRequest{}

// TokenAuthorizationCodeRequest struct for TokenAuthorizationCodeRequest
type TokenAuthorizationCodeRequest struct {
	// Client ID
	ClientId string `json:"client_id"`
	// Client Secret
	ClientSecret string `json:"client_secret"`
	// OAuth Grant Type, use authorization_code.
	GrantType string `json:"grant_type"`
	// Authorization code must be obtained with a valid request to `/oauth/authorize`. This code is used to request an access token in the OAuth 2.0 Authorization Code Flow.
	AuthorizationCode    string                 `json:"authorization_code"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _TokenAuthorizationCodeRequest TokenAuthorizationCodeRequest

// NewTokenAuthorizationCodeRequest instantiates a new TokenAuthorizationCodeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenAuthorizationCodeRequest(clientId string, clientSecret string, grantType string, authorizationCode string) *TokenAuthorizationCodeRequest {
	this := TokenAuthorizationCodeRequest{}
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	this.GrantType = grantType
	this.AuthorizationCode = authorizationCode
	return &this
}

// NewTokenAuthorizationCodeRequestWithDefaults instantiates a new TokenAuthorizationCodeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenAuthorizationCodeRequestWithDefaults() *TokenAuthorizationCodeRequest {
	this := TokenAuthorizationCodeRequest{}
	var grantType string = "authorization_code"
	this.GrantType = grantType
	return &this
}

// GetClientId returns the ClientId field value
func (o *TokenAuthorizationCodeRequest) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *TokenAuthorizationCodeRequest) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *TokenAuthorizationCodeRequest) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *TokenAuthorizationCodeRequest) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *TokenAuthorizationCodeRequest) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *TokenAuthorizationCodeRequest) SetClientSecret(v string) {
	o.ClientSecret = v
}

// GetGrantType returns the GrantType field value
func (o *TokenAuthorizationCodeRequest) GetGrantType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GrantType
}

// GetGrantTypeOk returns a tuple with the GrantType field value
// and a boolean to check if the value has been set.
func (o *TokenAuthorizationCodeRequest) GetGrantTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrantType, true
}

// SetGrantType sets field value
func (o *TokenAuthorizationCodeRequest) SetGrantType(v string) {
	o.GrantType = v
}

// GetAuthorizationCode returns the AuthorizationCode field value
func (o *TokenAuthorizationCodeRequest) GetAuthorizationCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthorizationCode
}

// GetAuthorizationCodeOk returns a tuple with the AuthorizationCode field value
// and a boolean to check if the value has been set.
func (o *TokenAuthorizationCodeRequest) GetAuthorizationCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthorizationCode, true
}

// SetAuthorizationCode sets field value
func (o *TokenAuthorizationCodeRequest) SetAuthorizationCode(v string) {
	o.AuthorizationCode = v
}

func (o TokenAuthorizationCodeRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenAuthorizationCodeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["client_id"] = o.ClientId
	toSerialize["client_secret"] = o.ClientSecret
	toSerialize["grant_type"] = o.GrantType
	toSerialize["authorization_code"] = o.AuthorizationCode

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableTokenAuthorizationCodeRequest struct {
	value *TokenAuthorizationCodeRequest
	isSet bool
}

func (v NullableTokenAuthorizationCodeRequest) Get() *TokenAuthorizationCodeRequest {
	return v.value
}

func (v *NullableTokenAuthorizationCodeRequest) Set(val *TokenAuthorizationCodeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenAuthorizationCodeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenAuthorizationCodeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenAuthorizationCodeRequest(val *TokenAuthorizationCodeRequest) *NullableTokenAuthorizationCodeRequest {
	return &NullableTokenAuthorizationCodeRequest{value: val, isSet: true}
}

func (v NullableTokenAuthorizationCodeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenAuthorizationCodeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableTokenAuthorizationCodeRequest) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *TokenAuthorizationCodeRequest) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
