/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the AddVirtualImage200ResponseAllOfVirtualImageTenant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddVirtualImage200ResponseAllOfVirtualImageTenant{}

// AddVirtualImage200ResponseAllOfVirtualImageTenant struct for AddVirtualImage200ResponseAllOfVirtualImageTenant
type AddVirtualImage200ResponseAllOfVirtualImageTenant struct {
	Id                   *int64                 `json:"id,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _AddVirtualImage200ResponseAllOfVirtualImageTenant AddVirtualImage200ResponseAllOfVirtualImageTenant

// NewAddVirtualImage200ResponseAllOfVirtualImageTenantWithDefaults instantiates a new AddVirtualImage200ResponseAllOfVirtualImageTenant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddVirtualImage200ResponseAllOfVirtualImageTenantWithDefaults() *AddVirtualImage200ResponseAllOfVirtualImageTenant {
	this := AddVirtualImage200ResponseAllOfVirtualImageTenant{}
	return &this
}

func (o AddVirtualImage200ResponseAllOfVirtualImageTenant) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddVirtualImage200ResponseAllOfVirtualImageTenant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableAddVirtualImage200ResponseAllOfVirtualImageTenant struct {
	value *AddVirtualImage200ResponseAllOfVirtualImageTenant
	isSet bool
}

func (v NullableAddVirtualImage200ResponseAllOfVirtualImageTenant) Get() *AddVirtualImage200ResponseAllOfVirtualImageTenant {
	return v.value
}

func (v *NullableAddVirtualImage200ResponseAllOfVirtualImageTenant) Set(val *AddVirtualImage200ResponseAllOfVirtualImageTenant) {
	v.value = val
	v.isSet = true
}

func (v NullableAddVirtualImage200ResponseAllOfVirtualImageTenant) IsSet() bool {
	return v.isSet
}

func (v *NullableAddVirtualImage200ResponseAllOfVirtualImageTenant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddVirtualImage200ResponseAllOfVirtualImageTenant(val *AddVirtualImage200ResponseAllOfVirtualImageTenant) *NullableAddVirtualImage200ResponseAllOfVirtualImageTenant {
	return &NullableAddVirtualImage200ResponseAllOfVirtualImageTenant{value: val, isSet: true}
}

func (v NullableAddVirtualImage200ResponseAllOfVirtualImageTenant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddVirtualImage200ResponseAllOfVirtualImageTenant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableAddVirtualImage200ResponseAllOfVirtualImageTenant) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *AddVirtualImage200ResponseAllOfVirtualImageTenant) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
