/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the WorkflowJobPayloadTargetsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowJobPayloadTargetsInner{}

// WorkflowJobPayloadTargetsInner struct for WorkflowJobPayloadTargetsInner
type WorkflowJobPayloadTargetsInner struct {
	RefId                *int64                 `json:"refId,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _WorkflowJobPayloadTargetsInner WorkflowJobPayloadTargetsInner

func (o WorkflowJobPayloadTargetsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowJobPayloadTargetsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RefId) {
		toSerialize["refId"] = o.RefId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableWorkflowJobPayloadTargetsInner struct {
	value *WorkflowJobPayloadTargetsInner
	isSet bool
}

func (v NullableWorkflowJobPayloadTargetsInner) Get() *WorkflowJobPayloadTargetsInner {
	return v.value
}

func (v *NullableWorkflowJobPayloadTargetsInner) Set(val *WorkflowJobPayloadTargetsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowJobPayloadTargetsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowJobPayloadTargetsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowJobPayloadTargetsInner(val *WorkflowJobPayloadTargetsInner) *NullableWorkflowJobPayloadTargetsInner {
	return &NullableWorkflowJobPayloadTargetsInner{value: val, isSet: true}
}

func (v NullableWorkflowJobPayloadTargetsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowJobPayloadTargetsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableWorkflowJobPayloadTargetsInner) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *WorkflowJobPayloadTargetsInner) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
