/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the AddCredentialsRequestCredentialOneOf4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddCredentialsRequestCredentialOneOf4{}

// AddCredentialsRequestCredentialOneOf4 struct for AddCredentialsRequestCredentialOneOf4
type AddCredentialsRequestCredentialOneOf4 struct {
	// Credential Type Code
	Type string `json:"type"`
	// A unique name scoped to your account for the credential
	Name string `json:"name"`
	// Optional Description
	Description *string `json:"description,omitempty"`
	// Credential enabled
	Enabled     *bool                                             `json:"enabled,omitempty"`
	Integration *AddCredentialsRequestCredentialOneOf4Integration `json:"integration,omitempty"`
	// Username
	Username string `json:"username"`
	// API Key
	Password             string                 `json:"password"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _AddCredentialsRequestCredentialOneOf4 AddCredentialsRequestCredentialOneOf4

// NewAddCredentialsRequestCredentialOneOf4WithDefaults instantiates a new AddCredentialsRequestCredentialOneOf4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddCredentialsRequestCredentialOneOf4WithDefaults() *AddCredentialsRequestCredentialOneOf4 {
	this := AddCredentialsRequestCredentialOneOf4{}
	var enabled bool = true
	this.Enabled = &enabled
	return &this
}

func (o AddCredentialsRequestCredentialOneOf4) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddCredentialsRequestCredentialOneOf4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Integration) {
		toSerialize["integration"] = o.Integration
	}
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableAddCredentialsRequestCredentialOneOf4 struct {
	value *AddCredentialsRequestCredentialOneOf4
	isSet bool
}

func (v NullableAddCredentialsRequestCredentialOneOf4) Get() *AddCredentialsRequestCredentialOneOf4 {
	return v.value
}

func (v *NullableAddCredentialsRequestCredentialOneOf4) Set(val *AddCredentialsRequestCredentialOneOf4) {
	v.value = val
	v.isSet = true
}

func (v NullableAddCredentialsRequestCredentialOneOf4) IsSet() bool {
	return v.isSet
}

func (v *NullableAddCredentialsRequestCredentialOneOf4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddCredentialsRequestCredentialOneOf4(val *AddCredentialsRequestCredentialOneOf4) *NullableAddCredentialsRequestCredentialOneOf4 {
	return &NullableAddCredentialsRequestCredentialOneOf4{value: val, isSet: true}
}

func (v NullableAddCredentialsRequestCredentialOneOf4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddCredentialsRequestCredentialOneOf4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableAddCredentialsRequestCredentialOneOf4) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *AddCredentialsRequestCredentialOneOf4) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
