/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the VRealizeOrchestratorTaskConfig4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VRealizeOrchestratorTaskConfig4{}

// VRealizeOrchestratorTaskConfig4 struct for VRealizeOrchestratorTaskConfig4
type VRealizeOrchestratorTaskConfig4 struct {
	SshKey               NullableString         `json:"sshKey,omitempty"`
	LocalScriptGitRef    NullableString         `json:"localScriptGitRef,omitempty"`
	Port                 NullableString         `json:"port,omitempty"`
	VroBody              NullableString         `json:"vroBody,omitempty"`
	Password             NullableString         `json:"password,omitempty"`
	PasswordHash         NullableString         `json:"passwordHash,omitempty"`
	Host                 NullableString         `json:"host,omitempty"`
	LocalScriptGitId     NullableString         `json:"localScriptGitId,omitempty"`
	Username             NullableString         `json:"username,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _VRealizeOrchestratorTaskConfig4 VRealizeOrchestratorTaskConfig4

func (o VRealizeOrchestratorTaskConfig4) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VRealizeOrchestratorTaskConfig4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.SshKey.IsSet() {
		toSerialize["sshKey"] = o.SshKey.Get()
	}
	if o.LocalScriptGitRef.IsSet() {
		toSerialize["localScriptGitRef"] = o.LocalScriptGitRef.Get()
	}
	if o.Port.IsSet() {
		toSerialize["port"] = o.Port.Get()
	}
	if o.VroBody.IsSet() {
		toSerialize["vroBody"] = o.VroBody.Get()
	}
	if o.Password.IsSet() {
		toSerialize["password"] = o.Password.Get()
	}
	if o.PasswordHash.IsSet() {
		toSerialize["passwordHash"] = o.PasswordHash.Get()
	}
	if o.Host.IsSet() {
		toSerialize["host"] = o.Host.Get()
	}
	if o.LocalScriptGitId.IsSet() {
		toSerialize["localScriptGitId"] = o.LocalScriptGitId.Get()
	}
	if o.Username.IsSet() {
		toSerialize["username"] = o.Username.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableVRealizeOrchestratorTaskConfig4 struct {
	value *VRealizeOrchestratorTaskConfig4
	isSet bool
}

func (v NullableVRealizeOrchestratorTaskConfig4) Get() *VRealizeOrchestratorTaskConfig4 {
	return v.value
}

func (v *NullableVRealizeOrchestratorTaskConfig4) Set(val *VRealizeOrchestratorTaskConfig4) {
	v.value = val
	v.isSet = true
}

func (v NullableVRealizeOrchestratorTaskConfig4) IsSet() bool {
	return v.isSet
}

func (v *NullableVRealizeOrchestratorTaskConfig4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVRealizeOrchestratorTaskConfig4(val *VRealizeOrchestratorTaskConfig4) *NullableVRealizeOrchestratorTaskConfig4 {
	return &NullableVRealizeOrchestratorTaskConfig4{value: val, isSet: true}
}

func (v NullableVRealizeOrchestratorTaskConfig4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVRealizeOrchestratorTaskConfig4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableVRealizeOrchestratorTaskConfig4) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *VRealizeOrchestratorTaskConfig4) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
