/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the GetCloudDatastores200ResponseAllOfDatastore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCloudDatastores200ResponseAllOfDatastore{}

// GetCloudDatastores200ResponseAllOfDatastore struct for GetCloudDatastores200ResponseAllOfDatastore
type GetCloudDatastores200ResponseAllOfDatastore struct {
	Id                   *int64                                                         `json:"id,omitempty"`
	Name                 *string                                                        `json:"name,omitempty"`
	Zone                 *GetCloudDatastores200ResponseAllOfDatastoreZone               `json:"zone,omitempty"`
	Type                 *string                                                        `json:"type,omitempty"`
	FreeSpace            *int64                                                         `json:"freeSpace,omitempty"`
	Online               *bool                                                          `json:"online,omitempty"`
	Active               *bool                                                          `json:"active,omitempty"`
	Visibility           *string                                                        `json:"visibility,omitempty"`
	Tenants              []GetCloudDatastores200ResponseAllOfDatastoreTenantsInner      `json:"tenants,omitempty"`
	ResourcePermission   *GetCloudDatastores200ResponseAllOfDatastoreResourcePermission `json:"resourcePermission,omitempty"`
	AdditionalProperties map[string]interface{}                                         `json:",remain"`
}

type _GetCloudDatastores200ResponseAllOfDatastore GetCloudDatastores200ResponseAllOfDatastore

func (o GetCloudDatastores200ResponseAllOfDatastore) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCloudDatastores200ResponseAllOfDatastore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Zone) {
		toSerialize["zone"] = o.Zone
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.FreeSpace) {
		toSerialize["freeSpace"] = o.FreeSpace
	}
	if !IsNil(o.Online) {
		toSerialize["online"] = o.Online
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Visibility) {
		toSerialize["visibility"] = o.Visibility
	}
	if o.Tenants != nil {
		toSerialize["tenants"] = o.Tenants
	}
	if !IsNil(o.ResourcePermission) {
		toSerialize["resourcePermission"] = o.ResourcePermission
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableGetCloudDatastores200ResponseAllOfDatastore struct {
	value *GetCloudDatastores200ResponseAllOfDatastore
	isSet bool
}

func (v NullableGetCloudDatastores200ResponseAllOfDatastore) Get() *GetCloudDatastores200ResponseAllOfDatastore {
	return v.value
}

func (v *NullableGetCloudDatastores200ResponseAllOfDatastore) Set(val *GetCloudDatastores200ResponseAllOfDatastore) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCloudDatastores200ResponseAllOfDatastore) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCloudDatastores200ResponseAllOfDatastore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCloudDatastores200ResponseAllOfDatastore(val *GetCloudDatastores200ResponseAllOfDatastore) *NullableGetCloudDatastores200ResponseAllOfDatastore {
	return &NullableGetCloudDatastores200ResponseAllOfDatastore{value: val, isSet: true}
}

func (v NullableGetCloudDatastores200ResponseAllOfDatastore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCloudDatastores200ResponseAllOfDatastore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableGetCloudDatastores200ResponseAllOfDatastore) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *GetCloudDatastores200ResponseAllOfDatastore) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
