/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the ListPoliciesGroup200ResponseAllOfPoliciesInnerUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPoliciesGroup200ResponseAllOfPoliciesInnerUser{}

// ListPoliciesGroup200ResponseAllOfPoliciesInnerUser struct for ListPoliciesGroup200ResponseAllOfPoliciesInnerUser
type ListPoliciesGroup200ResponseAllOfPoliciesInnerUser struct {
	Id                   *int64                 `json:"id,omitempty"`
	Username             *string                `json:"username,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _ListPoliciesGroup200ResponseAllOfPoliciesInnerUser ListPoliciesGroup200ResponseAllOfPoliciesInnerUser

// NewListPoliciesGroup200ResponseAllOfPoliciesInnerUserWithDefaults instantiates a new ListPoliciesGroup200ResponseAllOfPoliciesInnerUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPoliciesGroup200ResponseAllOfPoliciesInnerUserWithDefaults() *ListPoliciesGroup200ResponseAllOfPoliciesInnerUser {
	this := ListPoliciesGroup200ResponseAllOfPoliciesInnerUser{}
	return &this
}

func (o ListPoliciesGroup200ResponseAllOfPoliciesInnerUser) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPoliciesGroup200ResponseAllOfPoliciesInnerUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableListPoliciesGroup200ResponseAllOfPoliciesInnerUser struct {
	value *ListPoliciesGroup200ResponseAllOfPoliciesInnerUser
	isSet bool
}

func (v NullableListPoliciesGroup200ResponseAllOfPoliciesInnerUser) Get() *ListPoliciesGroup200ResponseAllOfPoliciesInnerUser {
	return v.value
}

func (v *NullableListPoliciesGroup200ResponseAllOfPoliciesInnerUser) Set(val *ListPoliciesGroup200ResponseAllOfPoliciesInnerUser) {
	v.value = val
	v.isSet = true
}

func (v NullableListPoliciesGroup200ResponseAllOfPoliciesInnerUser) IsSet() bool {
	return v.isSet
}

func (v *NullableListPoliciesGroup200ResponseAllOfPoliciesInnerUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPoliciesGroup200ResponseAllOfPoliciesInnerUser(val *ListPoliciesGroup200ResponseAllOfPoliciesInnerUser) *NullableListPoliciesGroup200ResponseAllOfPoliciesInnerUser {
	return &NullableListPoliciesGroup200ResponseAllOfPoliciesInnerUser{value: val, isSet: true}
}

func (v NullableListPoliciesGroup200ResponseAllOfPoliciesInnerUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPoliciesGroup200ResponseAllOfPoliciesInnerUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableListPoliciesGroup200ResponseAllOfPoliciesInnerUser) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *ListPoliciesGroup200ResponseAllOfPoliciesInnerUser) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
