/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the TagsPolicyTypeConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagsPolicyTypeConfiguration{}

// TagsPolicyTypeConfiguration - Tags
type TagsPolicyTypeConfiguration struct {
	Strict               bool                   `json:"strict"`
	Key                  *string                `json:"key,omitempty"`
	ValueListId          *string                `json:"valueListId,omitempty"`
	Value                *string                `json:"value,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _TagsPolicyTypeConfiguration TagsPolicyTypeConfiguration

// NewTagsPolicyTypeConfigurationWithDefaults instantiates a new TagsPolicyTypeConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagsPolicyTypeConfigurationWithDefaults() *TagsPolicyTypeConfiguration {
	this := TagsPolicyTypeConfiguration{}
	return &this
}

func (o TagsPolicyTypeConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagsPolicyTypeConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["strict"] = o.Strict
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.ValueListId) {
		toSerialize["valueListId"] = o.ValueListId
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableTagsPolicyTypeConfiguration struct {
	value *TagsPolicyTypeConfiguration
	isSet bool
}

func (v NullableTagsPolicyTypeConfiguration) Get() *TagsPolicyTypeConfiguration {
	return v.value
}

func (v *NullableTagsPolicyTypeConfiguration) Set(val *TagsPolicyTypeConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableTagsPolicyTypeConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableTagsPolicyTypeConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagsPolicyTypeConfiguration(val *TagsPolicyTypeConfiguration) *NullableTagsPolicyTypeConfiguration {
	return &NullableTagsPolicyTypeConfiguration{value: val, isSet: true}
}

func (v NullableTagsPolicyTypeConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagsPolicyTypeConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableTagsPolicyTypeConfiguration) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *TagsPolicyTypeConfiguration) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
