/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the UpdateNetworkDomainRequestNetworkDomain type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNetworkDomainRequestNetworkDomain{}

// UpdateNetworkDomainRequestNetworkDomain struct for UpdateNetworkDomainRequestNetworkDomain
type UpdateNetworkDomainRequestNetworkDomain struct {
	// Name
	Name *string `json:"name,omitempty"`
	// Description
	Description *string `json:"description,omitempty"`
	// Overrides displayed name in domain selection components. Useful if using many OU Paths.
	DisplayName *string `json:"displayName,omitempty"`
	// Public Zone
	PublicZone *bool `json:"publicZone,omitempty"`
	// Workflow ID. Workflows can be applied to an instance when associated with a domain. Useful for custom domain related scripting. (Important if wanting to ensure the computer is removed from the domain using teardown phased workflows.)
	TaskSetId *int64 `json:"taskSetId,omitempty"`
	// Active
	Active *bool `json:"active,omitempty"`
	// Join Domain Controller
	DomainController *bool `json:"domainController,omitempty"`
	// Domain Username
	DomainUsername *string `json:"domainUsername,omitempty"`
	// Domain Password
	DomainPassword *string `json:"domainPassword,omitempty"`
	// DC Server. If specified, must be the server name and not an IP Address
	DcServer *string `json:"dcServer,omitempty"`
	// OU Path. (i.e. 'OU=staging,DC=ad,DC=yourdomain,DC=com')
	OuPath *string `json:"ouPath,omitempty"`
	// Guest Username. If set, will change the instances RPC Service User after joining a Domain.
	GuestUsername *string `json:"guestUsername,omitempty"`
	// Guest Password
	GuestPassword        *string                `json:"guestPassword,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _UpdateNetworkDomainRequestNetworkDomain UpdateNetworkDomainRequestNetworkDomain

func (o UpdateNetworkDomainRequestNetworkDomain) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNetworkDomainRequestNetworkDomain) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.PublicZone) {
		toSerialize["publicZone"] = o.PublicZone
	}
	if !IsNil(o.TaskSetId) {
		toSerialize["taskSetId"] = o.TaskSetId
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.DomainController) {
		toSerialize["domainController"] = o.DomainController
	}
	if !IsNil(o.DomainUsername) {
		toSerialize["domainUsername"] = o.DomainUsername
	}
	if !IsNil(o.DomainPassword) {
		toSerialize["domainPassword"] = o.DomainPassword
	}
	if !IsNil(o.DcServer) {
		toSerialize["dcServer"] = o.DcServer
	}
	if !IsNil(o.OuPath) {
		toSerialize["ouPath"] = o.OuPath
	}
	if !IsNil(o.GuestUsername) {
		toSerialize["guestUsername"] = o.GuestUsername
	}
	if !IsNil(o.GuestPassword) {
		toSerialize["guestPassword"] = o.GuestPassword
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUpdateNetworkDomainRequestNetworkDomain struct {
	value *UpdateNetworkDomainRequestNetworkDomain
	isSet bool
}

func (v NullableUpdateNetworkDomainRequestNetworkDomain) Get() *UpdateNetworkDomainRequestNetworkDomain {
	return v.value
}

func (v *NullableUpdateNetworkDomainRequestNetworkDomain) Set(val *UpdateNetworkDomainRequestNetworkDomain) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNetworkDomainRequestNetworkDomain) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNetworkDomainRequestNetworkDomain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNetworkDomainRequestNetworkDomain(val *UpdateNetworkDomainRequestNetworkDomain) *NullableUpdateNetworkDomainRequestNetworkDomain {
	return &NullableUpdateNetworkDomainRequestNetworkDomain{value: val, isSet: true}
}

func (v NullableUpdateNetworkDomainRequestNetworkDomain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNetworkDomainRequestNetworkDomain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableUpdateNetworkDomainRequestNetworkDomain) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *UpdateNetworkDomainRequestNetworkDomain) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
