/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"time"
)

// checks if the IdentitySourcesSAMLConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentitySourcesSAMLConfig{}

// IdentitySourcesSAMLConfig struct for IdentitySourcesSAMLConfig
type IdentitySourcesSAMLConfig struct {
	Id                   *int64                                                          `json:"id,omitempty"`
	Name                 *string                                                         `json:"name,omitempty"`
	Description          *string                                                         `json:"description,omitempty"`
	Code                 *string                                                         `json:"code,omitempty"`
	Type                 *string                                                         `json:"type,omitempty"`
	Active               *bool                                                           `json:"active,omitempty"`
	Deleted              *bool                                                           `json:"deleted,omitempty"`
	AutoSyncOnLogin      *bool                                                           `json:"autoSyncOnLogin,omitempty"`
	ExternalLogin        *bool                                                           `json:"externalLogin,omitempty"`
	AllowCustomMappings  *bool                                                           `json:"allowCustomMappings,omitempty"`
	ManualRoleAssignment *bool                                                           `json:"manualRoleAssignment,omitempty"`
	Account              *AddIdentitySources200ResponseAllOfTaskOneOf5Account            `json:"account,omitempty"`
	DefaultAccountRole   *AddIdentitySources200ResponseAllOfTaskOneOf5DefaultAccountRole `json:"defaultAccountRole,omitempty"`
	Config               *AddIdentitySources200ResponseAllOfTaskOneOf5Config             `json:"config,omitempty"`
	RoleMappings         []AddIdentitySources200ResponseAllOfTaskOneOf5RoleMappingsInner `json:"roleMappings,omitempty"`
	Subdomain            *string                                                         `json:"subdomain,omitempty"`
	LoginURL             *string                                                         `json:"loginURL,omitempty"`
	ProviderSettings     *AddIdentitySources200ResponseAllOfTaskOneOf5ProviderSettings   `json:"providerSettings,omitempty"`
	DateCreated          *time.Time                                                      `json:"dateCreated,omitempty"`
	LastUpdated          *time.Time                                                      `json:"lastUpdated,omitempty"`
	AdditionalProperties map[string]interface{}                                          `json:",remain"`
}

type _IdentitySourcesSAMLConfig IdentitySourcesSAMLConfig

// NewIdentitySourcesSAMLConfigWithDefaults instantiates a new IdentitySourcesSAMLConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentitySourcesSAMLConfigWithDefaults() *IdentitySourcesSAMLConfig {
	this := IdentitySourcesSAMLConfig{}
	return &this
}

func (o IdentitySourcesSAMLConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentitySourcesSAMLConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	if !IsNil(o.AutoSyncOnLogin) {
		toSerialize["autoSyncOnLogin"] = o.AutoSyncOnLogin
	}
	if !IsNil(o.ExternalLogin) {
		toSerialize["externalLogin"] = o.ExternalLogin
	}
	if !IsNil(o.AllowCustomMappings) {
		toSerialize["allowCustomMappings"] = o.AllowCustomMappings
	}
	if !IsNil(o.ManualRoleAssignment) {
		toSerialize["manualRoleAssignment"] = o.ManualRoleAssignment
	}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.DefaultAccountRole) {
		toSerialize["defaultAccountRole"] = o.DefaultAccountRole
	}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.RoleMappings) {
		toSerialize["roleMappings"] = o.RoleMappings
	}
	if !IsNil(o.Subdomain) {
		toSerialize["subdomain"] = o.Subdomain
	}
	if !IsNil(o.LoginURL) {
		toSerialize["loginURL"] = o.LoginURL
	}
	if !IsNil(o.ProviderSettings) {
		toSerialize["providerSettings"] = o.ProviderSettings
	}
	if !IsNil(o.DateCreated) {
		toSerialize["dateCreated"] = o.DateCreated
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["lastUpdated"] = o.LastUpdated
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableIdentitySourcesSAMLConfig struct {
	value *IdentitySourcesSAMLConfig
	isSet bool
}

func (v NullableIdentitySourcesSAMLConfig) Get() *IdentitySourcesSAMLConfig {
	return v.value
}

func (v *NullableIdentitySourcesSAMLConfig) Set(val *IdentitySourcesSAMLConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentitySourcesSAMLConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentitySourcesSAMLConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentitySourcesSAMLConfig(val *IdentitySourcesSAMLConfig) *NullableIdentitySourcesSAMLConfig {
	return &NullableIdentitySourcesSAMLConfig{value: val, isSet: true}
}

func (v NullableIdentitySourcesSAMLConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentitySourcesSAMLConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableIdentitySourcesSAMLConfig) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *IdentitySourcesSAMLConfig) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
