/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the UpdateNetworkServerGroup200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNetworkServerGroup200Response{}

// UpdateNetworkServerGroup200Response struct for UpdateNetworkServerGroup200Response
type UpdateNetworkServerGroup200Response struct {
	Success              *bool                  `json:"success,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _UpdateNetworkServerGroup200Response UpdateNetworkServerGroup200Response

// NewUpdateNetworkServerGroup200ResponseWithDefaults instantiates a new UpdateNetworkServerGroup200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNetworkServerGroup200ResponseWithDefaults() *UpdateNetworkServerGroup200Response {
	this := UpdateNetworkServerGroup200Response{}
	return &this
}

func (o UpdateNetworkServerGroup200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNetworkServerGroup200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUpdateNetworkServerGroup200Response struct {
	value *UpdateNetworkServerGroup200Response
	isSet bool
}

func (v NullableUpdateNetworkServerGroup200Response) Get() *UpdateNetworkServerGroup200Response {
	return v.value
}

func (v *NullableUpdateNetworkServerGroup200Response) Set(val *UpdateNetworkServerGroup200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNetworkServerGroup200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNetworkServerGroup200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNetworkServerGroup200Response(val *UpdateNetworkServerGroup200Response) *NullableUpdateNetworkServerGroup200Response {
	return &NullableUpdateNetworkServerGroup200Response{value: val, isSet: true}
}

func (v NullableUpdateNetworkServerGroup200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNetworkServerGroup200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableUpdateNetworkServerGroup200Response) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *UpdateNetworkServerGroup200Response) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
