/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the BillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore{}

// BillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore struct for BillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore
type BillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore struct {
	Id                   *int64                 `json:"id,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	ExternalId           *string                `json:"externalId,omitempty"`
	InternalId           NullableString         `json:"internalId,omitempty"`
	ExternalPath         NullableString         `json:"externalPath,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _BillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore BillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore

// NewBillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastoreWithDefaults instantiates a new BillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastoreWithDefaults() *BillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore {
	this := BillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore{}
	return &this
}

func (o BillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.ExternalId) {
		toSerialize["externalId"] = o.ExternalId
	}
	if o.InternalId.IsSet() {
		toSerialize["internalId"] = o.InternalId.Get()
	}
	if o.ExternalPath.IsSet() {
		toSerialize["externalPath"] = o.ExternalPath.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableBillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore struct {
	value *BillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore
	isSet bool
}

func (v NullableBillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore) Get() *BillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore {
	return v.value
}

func (v *NullableBillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore) Set(val *BillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore(val *BillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore) *NullableBillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore {
	return &NullableBillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore{value: val, isSet: true}
}

func (v NullableBillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableBillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *BillingInstancesInstancesInnerContainersInnerUsagesInnerVolumesInnerDatastore) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
