/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner{}

// ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner struct for ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner
type ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner struct {
	Id                   *int64                                                                              `json:"id,omitempty"`
	Code                 *string                                                                             `json:"code,omitempty"`
	Name                 *string                                                                             `json:"name,omitempty"`
	Description          NullableString                                                                      `json:"description,omitempty"`
	Enabled              *bool                                                                               `json:"enabled,omitempty"`
	OptionTypes          []ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInnerOptionTypesInner `json:"optionTypes,omitempty"`
	AdditionalProperties map[string]interface{}                                                              `json:",remain"`
}

type _ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner

// NewListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInnerWithDefaults instantiates a new ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInnerWithDefaults() *ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner {
	this := ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner{}
	return &this
}

func (o ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.OptionTypes) {
		toSerialize["optionTypes"] = o.OptionTypes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner struct {
	value *ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner
	isSet bool
}

func (v NullableListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner) Get() *ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner {
	return v.value
}

func (v *NullableListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner) Set(val *ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner(val *ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner) *NullableListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner {
	return &NullableListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner{value: val, isSet: true}
}

func (v NullableListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *ListSecurityPackageTypes200ResponseAllOfSecurityPackageTypesInner) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
