/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the IntegrationGitHubConfigIntegrationConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrationGitHubConfigIntegrationConfig{}

// IntegrationGitHubConfigIntegrationConfig struct for IntegrationGitHubConfigIntegrationConfig
type IntegrationGitHubConfigIntegrationConfig struct {
	// Enable Git Repository Caching
	CacheEnabled         *bool                  `json:"cacheEnabled,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _IntegrationGitHubConfigIntegrationConfig IntegrationGitHubConfigIntegrationConfig

func (o IntegrationGitHubConfigIntegrationConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrationGitHubConfigIntegrationConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CacheEnabled) {
		toSerialize["cacheEnabled"] = o.CacheEnabled
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableIntegrationGitHubConfigIntegrationConfig struct {
	value *IntegrationGitHubConfigIntegrationConfig
	isSet bool
}

func (v NullableIntegrationGitHubConfigIntegrationConfig) Get() *IntegrationGitHubConfigIntegrationConfig {
	return v.value
}

func (v *NullableIntegrationGitHubConfigIntegrationConfig) Set(val *IntegrationGitHubConfigIntegrationConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationGitHubConfigIntegrationConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationGitHubConfigIntegrationConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationGitHubConfigIntegrationConfig(val *IntegrationGitHubConfigIntegrationConfig) *NullableIntegrationGitHubConfigIntegrationConfig {
	return &NullableIntegrationGitHubConfigIntegrationConfig{value: val, isSet: true}
}

func (v NullableIntegrationGitHubConfigIntegrationConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationGitHubConfigIntegrationConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableIntegrationGitHubConfigIntegrationConfig) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *IntegrationGitHubConfigIntegrationConfig) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
