/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.1.1
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the CredentialUsernamePasswordConfigIntegration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialUsernamePasswordConfigIntegration{}

// CredentialUsernamePasswordConfigIntegration Credential Store. ID of a Credential Integration. This can be set to store the credential in an external store.
type CredentialUsernamePasswordConfigIntegration struct {
	Id                   *AddCredentialsRequestCredentialOneOf1IntegrationId `json:"id,omitempty"`
	AdditionalProperties map[string]interface{}                              `json:",remain"`
}

type _CredentialUsernamePasswordConfigIntegration CredentialUsernamePasswordConfigIntegration

// NewCredentialUsernamePasswordConfigIntegration instantiates a new CredentialUsernamePasswordConfigIntegration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialUsernamePasswordConfigIntegration() *CredentialUsernamePasswordConfigIntegration {
	this := CredentialUsernamePasswordConfigIntegration{}
	return &this
}

// NewCredentialUsernamePasswordConfigIntegrationWithDefaults instantiates a new CredentialUsernamePasswordConfigIntegration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialUsernamePasswordConfigIntegrationWithDefaults() *CredentialUsernamePasswordConfigIntegration {
	this := CredentialUsernamePasswordConfigIntegration{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CredentialUsernamePasswordConfigIntegration) GetId() AddCredentialsRequestCredentialOneOf1IntegrationId {
	if o == nil || IsNil(o.Id) {
		var ret AddCredentialsRequestCredentialOneOf1IntegrationId
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialUsernamePasswordConfigIntegration) GetIdOk() (*AddCredentialsRequestCredentialOneOf1IntegrationId, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// IsSetId returns a boolean if a field has been set.
func (o *CredentialUsernamePasswordConfigIntegration) IsSetId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given AddCredentialsRequestCredentialOneOf1IntegrationId and assigns it to the Id field.
func (o *CredentialUsernamePasswordConfigIntegration) SetId(v AddCredentialsRequestCredentialOneOf1IntegrationId) {
	o.Id = &v
}

func (o CredentialUsernamePasswordConfigIntegration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialUsernamePasswordConfigIntegration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableCredentialUsernamePasswordConfigIntegration struct {
	value *CredentialUsernamePasswordConfigIntegration
	isSet bool
}

func (v NullableCredentialUsernamePasswordConfigIntegration) Get() *CredentialUsernamePasswordConfigIntegration {
	return v.value
}

func (v *NullableCredentialUsernamePasswordConfigIntegration) Set(val *CredentialUsernamePasswordConfigIntegration) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialUsernamePasswordConfigIntegration) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialUsernamePasswordConfigIntegration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialUsernamePasswordConfigIntegration(val *CredentialUsernamePasswordConfigIntegration) *NullableCredentialUsernamePasswordConfigIntegration {
	return &NullableCredentialUsernamePasswordConfigIntegration{value: val, isSet: true}
}

func (v NullableCredentialUsernamePasswordConfigIntegration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialUsernamePasswordConfigIntegration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableCredentialUsernamePasswordConfigIntegration) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *CredentialUsernamePasswordConfigIntegration) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
