/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 8.0.6
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"time"
)

// checks if the GetApprovalsItem200ResponseApprovalItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetApprovalsItem200ResponseApprovalItem{}

// GetApprovalsItem200ResponseApprovalItem struct for GetApprovalsItem200ResponseApprovalItem
type GetApprovalsItem200ResponseApprovalItem struct {
	Id *int64 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	ExternalId *string `json:"externalId,omitempty"`
	ExternalName *string `json:"externalName,omitempty"`
	InternalId *string `json:"internalId,omitempty"`
	ApprovedBy *string `json:"approvedBy,omitempty"`
	DeniedBy *string `json:"deniedBy,omitempty"`
	Status *string `json:"status,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	DateCreated *time.Time `json:"dateCreated,omitempty"`
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`
	DateApproved *time.Time `json:"dateApproved,omitempty"`
	DateDenied *time.Time `json:"dateDenied,omitempty"`
	Approval *GetAlerts200ResponseAllOfChecksInnerAccount `json:"approval,omitempty"`
	Reference *GetApprovalsItem200ResponseApprovalItemReference `json:"reference,omitempty"`
}

// NewGetApprovalsItem200ResponseApprovalItem instantiates a new GetApprovalsItem200ResponseApprovalItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetApprovalsItem200ResponseApprovalItem() *GetApprovalsItem200ResponseApprovalItem {
	this := GetApprovalsItem200ResponseApprovalItem{}
	return &this
}

// NewGetApprovalsItem200ResponseApprovalItemWithDefaults instantiates a new GetApprovalsItem200ResponseApprovalItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetApprovalsItem200ResponseApprovalItemWithDefaults() *GetApprovalsItem200ResponseApprovalItem {
	this := GetApprovalsItem200ResponseApprovalItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetApprovalsItem200ResponseApprovalItem) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// IsSetId returns a boolean if a field has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) IsSetId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *GetApprovalsItem200ResponseApprovalItem) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetApprovalsItem200ResponseApprovalItem) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// IsSetName returns a boolean if a field has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) IsSetName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetApprovalsItem200ResponseApprovalItem) SetName(v string) {
	o.Name = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *GetApprovalsItem200ResponseApprovalItem) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// IsSetExternalId returns a boolean if a field has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) IsSetExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *GetApprovalsItem200ResponseApprovalItem) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetExternalName returns the ExternalName field value if set, zero value otherwise.
func (o *GetApprovalsItem200ResponseApprovalItem) GetExternalName() string {
	if o == nil || IsNil(o.ExternalName) {
		var ret string
		return ret
	}
	return *o.ExternalName
}

// GetExternalNameOk returns a tuple with the ExternalName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) GetExternalNameOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalName) {
		return nil, false
	}
	return o.ExternalName, true
}

// IsSetExternalName returns a boolean if a field has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) IsSetExternalName() bool {
	if o != nil && !IsNil(o.ExternalName) {
		return true
	}

	return false
}

// SetExternalName gets a reference to the given string and assigns it to the ExternalName field.
func (o *GetApprovalsItem200ResponseApprovalItem) SetExternalName(v string) {
	o.ExternalName = &v
}

// GetInternalId returns the InternalId field value if set, zero value otherwise.
func (o *GetApprovalsItem200ResponseApprovalItem) GetInternalId() string {
	if o == nil || IsNil(o.InternalId) {
		var ret string
		return ret
	}
	return *o.InternalId
}

// GetInternalIdOk returns a tuple with the InternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) GetInternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.InternalId) {
		return nil, false
	}
	return o.InternalId, true
}

// IsSetInternalId returns a boolean if a field has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) IsSetInternalId() bool {
	if o != nil && !IsNil(o.InternalId) {
		return true
	}

	return false
}

// SetInternalId gets a reference to the given string and assigns it to the InternalId field.
func (o *GetApprovalsItem200ResponseApprovalItem) SetInternalId(v string) {
	o.InternalId = &v
}

// GetApprovedBy returns the ApprovedBy field value if set, zero value otherwise.
func (o *GetApprovalsItem200ResponseApprovalItem) GetApprovedBy() string {
	if o == nil || IsNil(o.ApprovedBy) {
		var ret string
		return ret
	}
	return *o.ApprovedBy
}

// GetApprovedByOk returns a tuple with the ApprovedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) GetApprovedByOk() (*string, bool) {
	if o == nil || IsNil(o.ApprovedBy) {
		return nil, false
	}
	return o.ApprovedBy, true
}

// IsSetApprovedBy returns a boolean if a field has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) IsSetApprovedBy() bool {
	if o != nil && !IsNil(o.ApprovedBy) {
		return true
	}

	return false
}

// SetApprovedBy gets a reference to the given string and assigns it to the ApprovedBy field.
func (o *GetApprovalsItem200ResponseApprovalItem) SetApprovedBy(v string) {
	o.ApprovedBy = &v
}

// GetDeniedBy returns the DeniedBy field value if set, zero value otherwise.
func (o *GetApprovalsItem200ResponseApprovalItem) GetDeniedBy() string {
	if o == nil || IsNil(o.DeniedBy) {
		var ret string
		return ret
	}
	return *o.DeniedBy
}

// GetDeniedByOk returns a tuple with the DeniedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) GetDeniedByOk() (*string, bool) {
	if o == nil || IsNil(o.DeniedBy) {
		return nil, false
	}
	return o.DeniedBy, true
}

// IsSetDeniedBy returns a boolean if a field has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) IsSetDeniedBy() bool {
	if o != nil && !IsNil(o.DeniedBy) {
		return true
	}

	return false
}

// SetDeniedBy gets a reference to the given string and assigns it to the DeniedBy field.
func (o *GetApprovalsItem200ResponseApprovalItem) SetDeniedBy(v string) {
	o.DeniedBy = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetApprovalsItem200ResponseApprovalItem) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// IsSetStatus returns a boolean if a field has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) IsSetStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetApprovalsItem200ResponseApprovalItem) SetStatus(v string) {
	o.Status = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *GetApprovalsItem200ResponseApprovalItem) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// IsSetErrorMessage returns a boolean if a field has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) IsSetErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *GetApprovalsItem200ResponseApprovalItem) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetDateCreated returns the DateCreated field value if set, zero value otherwise.
func (o *GetApprovalsItem200ResponseApprovalItem) GetDateCreated() time.Time {
	if o == nil || IsNil(o.DateCreated) {
		var ret time.Time
		return ret
	}
	return *o.DateCreated
}

// GetDateCreatedOk returns a tuple with the DateCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) GetDateCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateCreated) {
		return nil, false
	}
	return o.DateCreated, true
}

// IsSetDateCreated returns a boolean if a field has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) IsSetDateCreated() bool {
	if o != nil && !IsNil(o.DateCreated) {
		return true
	}

	return false
}

// SetDateCreated gets a reference to the given time.Time and assigns it to the DateCreated field.
func (o *GetApprovalsItem200ResponseApprovalItem) SetDateCreated(v time.Time) {
	o.DateCreated = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *GetApprovalsItem200ResponseApprovalItem) GetLastUpdated() time.Time {
	if o == nil || IsNil(o.LastUpdated) {
		var ret time.Time
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}

// IsSetLastUpdated returns a boolean if a field has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) IsSetLastUpdated() bool {
	if o != nil && !IsNil(o.LastUpdated) {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given time.Time and assigns it to the LastUpdated field.
func (o *GetApprovalsItem200ResponseApprovalItem) SetLastUpdated(v time.Time) {
	o.LastUpdated = &v
}

// GetDateApproved returns the DateApproved field value if set, zero value otherwise.
func (o *GetApprovalsItem200ResponseApprovalItem) GetDateApproved() time.Time {
	if o == nil || IsNil(o.DateApproved) {
		var ret time.Time
		return ret
	}
	return *o.DateApproved
}

// GetDateApprovedOk returns a tuple with the DateApproved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) GetDateApprovedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateApproved) {
		return nil, false
	}
	return o.DateApproved, true
}

// IsSetDateApproved returns a boolean if a field has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) IsSetDateApproved() bool {
	if o != nil && !IsNil(o.DateApproved) {
		return true
	}

	return false
}

// SetDateApproved gets a reference to the given time.Time and assigns it to the DateApproved field.
func (o *GetApprovalsItem200ResponseApprovalItem) SetDateApproved(v time.Time) {
	o.DateApproved = &v
}

// GetDateDenied returns the DateDenied field value if set, zero value otherwise.
func (o *GetApprovalsItem200ResponseApprovalItem) GetDateDenied() time.Time {
	if o == nil || IsNil(o.DateDenied) {
		var ret time.Time
		return ret
	}
	return *o.DateDenied
}

// GetDateDeniedOk returns a tuple with the DateDenied field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) GetDateDeniedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateDenied) {
		return nil, false
	}
	return o.DateDenied, true
}

// IsSetDateDenied returns a boolean if a field has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) IsSetDateDenied() bool {
	if o != nil && !IsNil(o.DateDenied) {
		return true
	}

	return false
}

// SetDateDenied gets a reference to the given time.Time and assigns it to the DateDenied field.
func (o *GetApprovalsItem200ResponseApprovalItem) SetDateDenied(v time.Time) {
	o.DateDenied = &v
}

// GetApproval returns the Approval field value if set, zero value otherwise.
func (o *GetApprovalsItem200ResponseApprovalItem) GetApproval() GetAlerts200ResponseAllOfChecksInnerAccount {
	if o == nil || IsNil(o.Approval) {
		var ret GetAlerts200ResponseAllOfChecksInnerAccount
		return ret
	}
	return *o.Approval
}

// GetApprovalOk returns a tuple with the Approval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) GetApprovalOk() (*GetAlerts200ResponseAllOfChecksInnerAccount, bool) {
	if o == nil || IsNil(o.Approval) {
		return nil, false
	}
	return o.Approval, true
}

// IsSetApproval returns a boolean if a field has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) IsSetApproval() bool {
	if o != nil && !IsNil(o.Approval) {
		return true
	}

	return false
}

// SetApproval gets a reference to the given GetAlerts200ResponseAllOfChecksInnerAccount and assigns it to the Approval field.
func (o *GetApprovalsItem200ResponseApprovalItem) SetApproval(v GetAlerts200ResponseAllOfChecksInnerAccount) {
	o.Approval = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *GetApprovalsItem200ResponseApprovalItem) GetReference() GetApprovalsItem200ResponseApprovalItemReference {
	if o == nil || IsNil(o.Reference) {
		var ret GetApprovalsItem200ResponseApprovalItemReference
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) GetReferenceOk() (*GetApprovalsItem200ResponseApprovalItemReference, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// IsSetReference returns a boolean if a field has been set.
func (o *GetApprovalsItem200ResponseApprovalItem) IsSetReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given GetApprovalsItem200ResponseApprovalItemReference and assigns it to the Reference field.
func (o *GetApprovalsItem200ResponseApprovalItem) SetReference(v GetApprovalsItem200ResponseApprovalItemReference) {
	o.Reference = &v
}

func (o GetApprovalsItem200ResponseApprovalItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetApprovalsItem200ResponseApprovalItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ExternalId) {
		toSerialize["externalId"] = o.ExternalId
	}
	if !IsNil(o.ExternalName) {
		toSerialize["externalName"] = o.ExternalName
	}
	if !IsNil(o.InternalId) {
		toSerialize["internalId"] = o.InternalId
	}
	if !IsNil(o.ApprovedBy) {
		toSerialize["approvedBy"] = o.ApprovedBy
	}
	if !IsNil(o.DeniedBy) {
		toSerialize["deniedBy"] = o.DeniedBy
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	if !IsNil(o.DateCreated) {
		toSerialize["dateCreated"] = o.DateCreated
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["lastUpdated"] = o.LastUpdated
	}
	if !IsNil(o.DateApproved) {
		toSerialize["dateApproved"] = o.DateApproved
	}
	if !IsNil(o.DateDenied) {
		toSerialize["dateDenied"] = o.DateDenied
	}
	if !IsNil(o.Approval) {
		toSerialize["approval"] = o.Approval
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	return toSerialize, nil
}

type NullableGetApprovalsItem200ResponseApprovalItem struct {
	value *GetApprovalsItem200ResponseApprovalItem
	isSet bool
}

func (v NullableGetApprovalsItem200ResponseApprovalItem) Get() *GetApprovalsItem200ResponseApprovalItem {
	return v.value
}

func (v *NullableGetApprovalsItem200ResponseApprovalItem) Set(val *GetApprovalsItem200ResponseApprovalItem) {
	v.value = val
	v.isSet = true
}

func (v NullableGetApprovalsItem200ResponseApprovalItem) IsSet() bool {
	return v.isSet
}

func (v *NullableGetApprovalsItem200ResponseApprovalItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetApprovalsItem200ResponseApprovalItem(val *GetApprovalsItem200ResponseApprovalItem) *NullableGetApprovalsItem200ResponseApprovalItem {
	return &NullableGetApprovalsItem200ResponseApprovalItem{value: val, isSet: true}
}

func (v NullableGetApprovalsItem200ResponseApprovalItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetApprovalsItem200ResponseApprovalItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


